### ISSUE TITLE
Remove USVI and Guam territories from data and include/show on map American Samoa and Mariana Islands

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1003]
There are issues with the underlying data for USVI and Guam, so we do not want to include these two island territories in the data / on the map. 

[UPDATE January 11]
- We want score generation to run for all territories and written to the full `usa.csv` per @lucasmbrown-usds 
- We want to strip these territories right before tile generation, probably somewhere on score_post

**Comment by vim-usds** [comment]
@jorge and @shelby making this a data ticket as there's another one for the FE work

**Comment by lucasmbrown-usds** [comment]
@esfoobar-usds Would be helpful to only remove these at the "last minute" before we write the downloadable Excel file and the tiles.

**Comment by esfoobar-usds** [comment]
@lucasmbrown-usds what about the download packet? Should all territories be written on the CSV/Excel, or exclude these from there as well?

**Comment by lucasmbrown-usds** [comment]
All territories should be written to the huge `usa.csv` but only Virgin Islands, American Samoa, and Puerto Rico to the downloadable Excel file/CSV or to the tiles.

**Comment by lucasmbrown-usds** [comment]
From Beth: the problem is with Guam (is on the map, shouldn't be) and American Samoa (is not on the map, should be).

**Comment by vim-usds** [comment]
- updated local fips to latest fips
- re-running full pipeline...

- [ ] does full csv have all territory data, make a note of ones that are missing
- [ ] does tile csv have the ones we want (meaning, not GU, but yes to AS)
- [ ] is the SP_FPS value accurate in the ones we want?

**Comment by vim-usds** [comment]
@jorge, @lucas and @beth,

Here are the codes for each of the territories:

## Territory codes from FIPS file from S3:
```
60, American Samoa,AS,American Samoa,American Samoa
66, Guam,GU,Guam,Guam
69, Northern Mariana Islands,MP,Northern Mariana Islands,Northern Mariana Islands
72, Puerto Rico,PR,Puerto Rico,Puerto Rico
78, Virgin Islands,VI,Virgin Islands,Virgin Islands
```

## CSV Files
The ✅  indicates if the data is in the CSV file
The ❌ indicates if the data is NOT in the CSV file

### CSV full
60, American Samoa,AS,American Samoa,American Samoa ✅ 
66, Guam,GU,Guam,Guam ✅ 
69, Northern Mariana Islands,MP,Northern Mariana Islands,Northern Mariana Islands ✅ 
72, Puerto Rico,PR,Puerto Rico,Puerto Rico ✅ 
78, Virgin Islands,VI,Virgin Islands,Virgin Islands ✅ 

### CSV tiles
60, American Samoa,AS,American Samoa,American Samoa ❌ 
66, Guam,GU,Guam,Guam ✅ 
69, Northern Mariana Islands,MP,Northern Mariana Islands,Northern Mariana Islands ✅ 
72, Puerto Rico,PR,Puerto Rico,Puerto Rico ✅ 
78, Virgin Islands,VI,Virgin Islands,Virgin Islands ✅ 

_Could this explain why there are weird things going on with GU and AS?_

**Comment by vim-usds** [comment]
Paired today with @Lucas (driving) and @emma-nechamkin . When running the ETL locally, it seemed that the AS's FIPS code of `60` was showing in the tiles CSV. 

We plan to investigate more on Monday. Still getting my bearings on the backend stuff.

**Comment by lucasmbrown-usds** [comment]
FYI it looked like geographies with a FIPS code of '60' were showing up in the geojson files of the TIGER census tract boundaries too.
