### ISSUE TITLE
Base map label on North Capitol Street in DC

### ISSUE THREAD

**Issue by glennettec** [usds/justice40-tool#1009]
**Describe the bug**
The base map inaccurately show up North Capitol Street Northeast and North Capitol Street Northwest as sections of one street. In fact, it is one street with two sides because of the quadrant layout of DC. The northeast side of the street is North Capitol Street NE, the northwest side of the street is North Capitol Street NW.

**To Reproduce**
1. Go to the map on explore the tools
2. Search for ZIP - 20001
3. Click the zoom "+" five times 
4. Move up and down the viewport to see how the name changes along the from northeast to northwest

**Expected behavior**
screenshot from google maps of ZIP 20001
![google - north capitol st.png](https://images.zenhubusercontent.com/60e71e455052ef541fcc40c3/e487bb71-2810-4ce0-b807-0c75c924dbec)

**Screenshots**
from current map of ZIP 20001
![nominatium.png](https://images.zenhubusercontent.com/60e71e455052ef541fcc40c3/c31ad61f-8ab2-4563-9ae1-4477af2a9d9e)

**Comment by vim-usds** [comment]
@glennettec , I wonder if this could be emailed to carto as we are using their basemaps

https://carto.com/help/building-maps/basemap-list/#carto-vector-basemaps

**Comment by BethMattern** [comment]
@vim-usds this could also be used as a specific example when reviewing other base maps.

**Comment by BethMattern** [comment]
We will submit this to Mapbox as we can't control the data on this map.
