### ISSUE TITLE
Investigate NHPD Database as a potential resource for foreclosure rates

### ISSUE THREAD

**Issue by ahlusar1989** [usds/justice40-tool#1011]
**Is your feature request related to a problem? Please describe.**

This is related to #994 by @lucasmbrown-usds 

Contemporary foreclosure datasets that capture the current status of housing insecurity are necessary for improving Score L and ensuring we capture the current state of the United States. We have a confluence of the current pandemic, unemployment, and natural disasters that affect vulnerable communities. This dataset and the forthcoming analysis would provide some alternatives.

**Describe the solution you'd like**

Derive foreclosure rates using NHPD.

**Describe alternatives you've considered**

Looking at[ HUD Low-Income Housing Tax Credit Qualified Census Tracts](https://www.huduser.gov/portal/datasets/qct.html)

**Additional context**

Please see #1012.

**Comment by lucasmbrown-usds** [comment]
Only applies to 3 states.
