### ISSUE TITLE
Update FE site with Spanish - post launch

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#1019]
Tasks

- [ ] Add [FormattedMessage] component to all Categories in Meth copy for RespParty and UsedIn fields
- [ ] add survey monkey form
- [ ] create es.json
- [ ] modify es.json to remove curly
- [ ] send to translation team
- [ ] unmodify es.json
- [ ] test

**Comment by katherinedm-usds** [comment]
Latest we've heard is that there are additional edits coming soon for English copy, so moving to lower priority for now
