### ISSUE TITLE
Research changing denominator in housing cost burden equation per HUD advice

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1024]
Per Blair Russell at HUD:

We may want to rethink the denominator of our equation for housing cost burden. 

"Right now it’s all housing units with a cost burden computed. Alternatively, you could use low-income households (with cost burden computed) as the denominator, which would be a measure of relative cost burden just for low-income households. Both approaches are appropriate, but they tell a different story. You can imagine an area with few low-income households but a vast majority of them being cost burdened. In your calculation, you’d get a small percentage. In the alternative approach, it’s a large percentage. Just something to think about. It depends on the story you want to tell."

**Comment by lucasmbrown-usds** [comment]
Closed. Saran's recommendation was not to use the new methodology.
