### ISSUE TITLE
As a data developer, I want to remove the `data-roadmap` directory that is no longer used very often.

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#1032]
**Description**
`data/data-roadmap` is a legacy item that is badly out of date. Should we just remove the whole directory so as to reduce confusion for new developers? 

I think deleting that folder will have no impacts on any other part of the codebase.

**Comment by esfoobar-usds** [comment]
I agree.

**Comment by saran-ahluwalia** [comment]
I can take care of that.

**Comment by lucasmbrown-usds** [comment]
Thanks @saran-ahluwalia !
