### ISSUE TITLE
Update CDC Places data to newest version

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1036]
CDC Places data was updated on Dec. 1 2021. New data source is here:
https://chronicdata.cdc.gov/500-Cities-Places/PLACES-Census-Tract-Data-GIS-Friendly-Format-2021-/yjkw-uj5s

Closing because this was automatically done.

**Comment by saran-ahluwalia** [comment]
@BethMattern I believe that according to @lucasmbrown-usds we are indeed using the latest.
