### ISSUE TITLE
As a developer, I want to know exactly our plan for building and hosting the ETL and scoring code and infrastructure, so that I can plan my work.

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#104]
**Description**
We need a very clear architecture diagram, with clear plans for infrastructure, for the whole backend processes of ETL, scoring, APIs, etc. 

**Solution**
A clear and concise description of the planned process for building the backend, including questions such as:

* The exact infrastructure (e.g., RDS with PostGIS, EC2 for running ETL scripts) with level of access needed  
* Code hosting (which repos)
* Build server
* How front-end accesses data

**Tasks**
* Build architecture diagram with clear descriptions

**Definition of "Done"**
* We feel like every question we need to answer about the where/what of the plan is answered and documented, so that we can start building with confidence.

**Comment by switzersc-usds** [comment]
Blocked by some outstanding questions for geoplatform, which we should answer in our meeting tomorrow.

**Comment by switzersc-usds** [comment]
Blocked until our convo with Geoplatform today.

**Comment by lucasmbrown-usds** [comment]
See https://app.mural.co/t/kameronkerger2998/m/kameronkerger2998/1623359377360/fb8f608c3a261dfba835bde3772d20d0dfabcf61
