### ISSUE TITLE
As a developer, I want `black` to run before every commit.

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#1050]
**Description**
Sometimes developers forget to run `black`. We should setup a pre-commit hook to run `black` before every commit.

**Comment by sverchdotgov** [comment]
If someone is working on something besides the python part of the codebase, they might not have the python dependencies installed to run this, so I'm not sure what the best way would be to do this.

If we have a github action that runs `black --check` then that could at least prevent PRs that black would format from making it into main, and the action could control the dependencies.

**Comment by sverchdotgov** [comment]
```
data-pipeline % poetry run black --check .
Skipping .ipynb files as Jupyter dependencies are not installed.
You can fix this by running ``pip install black[jupyter]``
would reformat data_pipeline/score/score_l.py
Oh no! 💥 💔 💥
1 file would be reformatted, 91 files would be left unchanged.
```

**Comment by sverchdotgov** [comment]
Some notes from discussion:

- Want to document some of the important things about tox, like `tox -e lint` can run the lint, and that subsequent runs after the dependencies are installed should be fast (unless you do `tox -r`).
- Doing this as a pre-commit hook would make code reviews easier.
- Two tox targets would be useful, `tox lint` that runs in a pre-commit to auto format, and `tox lint-check` which runs in CI and fails when it's not formatted.

**Comment by lucasmbrown-usds** [comment]
Example pre-commit config: https://github.com/usdigitalresponse/covid-exit-strategy/blob/master/.pre-commit-config.yaml
