### ISSUE TITLE
State/Territory and County fields are blank for all American Samoa and Northern Mariana Islands

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#1052]
**Describe the bug**
In the Excel and .csv spreadsheets in the download package, the fields for State (column name which should be changed to State/Territory), and county are blank, and the only thing that indicates where the community is the census tract ID

**To Reproduce**
1. Download communities list package
2. Start to filter rows based on column names, look at what field values are there - and that though states, DC, Puerto Rico are listed, American Samoa and Northern Mariana Islands are not listed
3. Filter to view only rows that are blank for State
4. Observe the rows that are left have census tract IDs that correspond to American Samoa or Northern Mariana Islands

**Expected behavior**
 - [ ] Either American Samoa or Northern Mariana Islands are listed in the State/Territory column
 - [ ] Appropriate county (or district) is shown in County for that census tract

**Comment by vim-usds** [comment]
Will talk about this on Territory THu
