### ISSUE TITLE
Shortcuts broken after tract selection

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#1056]
**Describe the bug**
When I zoom in anywhere and select a tract to view, and THEN click the "AS" shortcut, the map moves to the left slightly instead of taking me to American Samoa.

**To Reproduce**
1. Go to the Explore the Tool page.
2. Zoom into any census tract NOT near American Samoa. 
3. Click the tract.
4. Click the AS shortcut
5. See that the map only moves slightly to the left.

**Expected behavior**
I expected the map to immediately jump to and zoom in on American Samoa. If you click the AS shortcut multiple times, it finally will move you to American Samoa, but it should only need one click.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Mojave
 - Browser [e.g. chrome, safari]- Firefox
 - Version [e.g. 22] - 89

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
Unable to reproduce on desktop. 

Mobile experience seems to be registering the clicks on the shortcuts as taps on the map. Needs more investigation

**Comment by vim-usds** [comment]
Tasks 

- [ ] make sure 48's initial load and clicking on 48 are equivalent with equal exposure to east and west coast
- [ ] Center HI as well
