### ISSUE TITLE
Double scroll bar on certain browser heights

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#1059]
**Describe the bug**
There are two scrollbars now for different components of the side panel on the Explore the Tool page, but ONLY for under a certain height. 

**To Reproduce**
1. Make your browser window be smaller than 9 inches high (the height of a 13in macbook pro)
2. Go to Explore the Tool page. 
3. See double scroll bar in side panel

**Expected behavior**
There should only be one scroll bar

**Screenshots**
https://user-images.githubusercontent.com/25443529/145618531-13c6419f-92d1-4b19-b187-d314ff0a4567.png 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - MacOS
 - Browser [e.g. chrome, safari] - Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BethMattern** [comment]
@vim-usds will do some cross browser/device testing
