### ISSUE TITLE
Side panel covers state/territory shortcut buttons on map in mobile

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#1060]
**Describe the bug**
When viewing the map on mobile, you can only see the shortcut for "48", not for any of the states or territories. This makes it difficult to find and navigate to those states/territories.

**To Reproduce**
1. Open the site on a mobile device
2. Go to Explore the Tool
3. Try to select the Alaska shortcut
4. You can't!

**Expected behavior**
You should be able to see and click/tap on shortcuts on map.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Android
 - Browser [e.g. chrome, safari] - Firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by katherinedm-usds** [comment]
@KameronKerger will sync up with @vim-usds on potential design to handle this on mobile, it's pretty impactful to community members trying to look up their territory if they don't have access to the shortcut on mobile devices

**Comment by vim-usds** [comment]
@katherinedm-usds - agreed. Having a holistic approach to mobile will be better than these one offs. However the holistic approach will take longer. Looking forward on chatting about how to balance the two.

**Comment by KameronKerger** [comment]
<img width="464" alt="Screen Shot 2022-01-06 at 1 10 22 PM" src="https://user-images.githubusercontent.com/77702996/148452567-824808f3-b726-40c8-9a8c-47c4d191ea45.png">

**Comment by vim-usds** [comment]
Note to myself - look at detecting device type first, if not, fall back to device width

**Comment by vim-usds** [comment]
Also, originally the mock was showing that the territories would slide on mobile however, this is native mobile action, so we're looking into making the current vertical territories horizontal.

**Comment by glennettec** [comment]
@vim-usds agreed that a more holistic approach to mobile is optimal instead of one-offs. we should do an exploration of a redesign for the page to address problematic issues. cc: @katherinedm-usds @KameronKerger

**Comment by vim-usds** [comment]
Tasks

- [ ] center search on mobile
- [ ] remove zoom on mobile
- [ ] move up territory shortcuts
- [ ] possible remove their current mapbox overrides?

**Comment by glennettec** [comment]
@vim-usds here is the last analysis that i did. is this what you're referring to?

[Breakpoint values.xlsx](https://github.com/usds/justice40-tool/files/7868102/Breakpoint.values.xlsx)
[filtered browser stats.xlsx](https://github.com/usds/justice40-tool/files/7868105/filtered.browser.stats.xlsx)
.
