### ISSUE TITLE
Add total number of thresholds exceeded to side panel

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1063]
Add total number of thresholds exceeded to side panel

![Screen Shot 2021-12-16 at 8 42 48 AM](https://user-images.githubusercontent.com/86254807/146412728-b04b8270-8d1f-4fd1-ba24-7e9ed9af97c7.png)

- [ ] Calculate the number of indicators 
- [ ] update component

**Comment by KameronKerger** [comment]
updated mock (I was still asleep)
![updated_side_panel_threshold_count](https://user-images.githubusercontent.com/77702996/146419845-985403a5-cd39-4939-8700-fa7fcb3b1a87.png)
