### ISSUE TITLE
Geoplatform AWS throws errors on load

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#107]
**Describe the bug**
Since issue [#97](https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/97), we are now deploying to Geoplatform AWS on every push, at the following address: http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/en/ . 

However, there are several issues: 
* The seal is not loading
* The site is not redirecting from / to /en
* The disclosure link at the top is not loading
* The site is not https (I believe this is the cause of the others)

**To Reproduce**
1. Push a build of justice40-tool
2. Go to http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/ , then http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/en
3. Inspect the console, see 404s for links like `http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/framework-a3da6a89099751fcddf3.js` . 

**Expected behavior**
The same static site content is being posted to both Github Pages and to AWS, so the content and behavior should match. The files are located in the same place on disk and the folder structure matches, so the behavior should as well. 

A few notes:
a. The equivalent link on github pages, https://usds.github.io/justice40-tool/framework-a3da6a89099751fcddf3.js , does work, and 
b. the file does exist on AWS itself at https://s3.console.aws.amazon.com/s3/object/usds-geoplatform-justice40-website?region=us-east-1&prefix=framework-a3da6a89099751fcddf3.js 

Another note is that S3 only supports HTTP out of the gate; we need to configure CloudFront to support HTTPS, and there are several facets to this.

The suspicion at present is that bucket permissions and/or HTTPS are interfering with our ability to load the content we need to load, we should correctly configure HTTPS, as we need to do this anyway, then reasesss.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 N/A

**Comment by NatHillardUSDS** [comment]
Diagnosis: we configured a `prefix-path` for use with github pages, but this didn't match the path within the s3 bucket. 

Solution: for now at least, add files to a subfolder called `justfice40-tool`. Going forward, after this is merged you can access via the CloudFront link at https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/en/ .

**Comment by switzersc-usds** [comment]
@NatHillardUSDS Status here?

**Comment by NatHillardUSDS** [comment]
This has been merged and is no longer an issue! Can be closed
