### ISSUE TITLE
Update FEMA data indicators to be a little more plain language

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1074]
**Describe the bug**
I do not want to make this change now but 
Percent of agriculture value at risk from losses due to natural hazards. Calculated by dividing the agriculture value at risk in a census tract by the total agriculture value in that census tract. Fourteen natural hazards that have some link to climate change include: avalanche, coastal flooding, cold wave, drought, hail, heat wave, hurricane, ice storm, landslide, riverine flooding, strong wind, tornado, wildfire, and winter weather.

sounds better as
Percent of agriculture value at risk from losses due to natural hazards which include fourteen natural hazards that have some link to climate change include: avalanche, coastal flooding, cold wave, drought, hail, heat wave, hurricane, ice storm, landslide, riverine flooding, strong wind, tornado, wildfire, and winter weather.. Calculated by dividing the agriculture value at risk in a census tract by the total agriculture value in that census tract. 

This applies to all the FEMA ones, I am just tired and only included this one as an example.

**To Reproduce**
1. Go to 'Methodology & data page'
3. Scroll down to 'FEMA related data indicators'

**Expected behavior**
Updated wording, example above.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by katherinedm-usds** [comment]
Copy change, @KameronKerger will make updates to living copy, this is something we'd want to get in for launch

**Comment by KameronKerger** [comment]
suggested updates made to living copy in suggest mode. sketch files also updated.

**Comment by BethMattern** [comment]
@KameronKerger and @vim-usds -Should this be in the sprint backlog? It looks like the suggested changes have been put in the living copy document?

**Comment by vim-usds** [comment]
@BethMattern - yes, moving over now
