### ISSUE TITLE
Task (or bug?): Investigate Exception Raised during Concurrent processing of datasets

### ISSUE THREAD

**Issue by saran-ahluwalia** [usds/justice40-tool#1079]
## Describe the task

This is related to #1038 and the now-closed PR #1039.

During the experimental runs for parallelizing the ETL tasks, a common exception was raised. After discussion with @lucasmbrown-usds, an initial diagnosis was made that the temporary directory file writes are raising the exception. More specifically, the naming scheme for the temporary file paths seems to be the same across datasets (see below for screenshots of trackback logs). Hence the goal is to ensure that the file paths are unique and to potentially prevent such exceptions during the simultaneous reads and writes across all threads that are spawned from the main ETL process.

## Acceptance Criteria

To be discussed after consultation with @esfoobar-usds and @lucasmbrown-usds. 

## Additional context

Please see here for references to the same temporary path:

<img width="762" alt="evidence_2" src="https://user-images.githubusercontent.com/94847739/146775466-ff46c8e5-9316-4ba1-a7d4-663cd1f84455.png">
<img width="1197" alt="evidence_1" src="https://user-images.githubusercontent.com/94847739/146775468-6721f634-8409-4c9b-b00c-80eb0df45fc7.png">

**Comment by lucasmbrown-usds** [comment]
This bug comes from expected behavior given that all the ETLs write to (and delete) the same directory
