### ISSUE TITLE
Add "Indicators" and "Percentile" column headers to the side panel

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1080]
- [x] Add headers under each category so the user knows what they are looking at.
- [x] modify description for one field as it's percent (see mock below)
- [x] add flag to indicator component to specify if it's a percentile or percentage

**Comment by KameronKerger** [comment]
<img width="276" alt="Screen Shot 2021-12-20 at 11 09 59 AM" src="https://user-images.githubusercontent.com/77702996/146819791-b77c423f-d802-4571-a42f-ae79edfa5a00.png">
<img width="300" alt="Screen Shot 2021-12-20 at 11 10 44 AM" src="https://user-images.githubusercontent.com/77702996/146819885-27a69b26-cc5a-4e6b-8ad0-1f70837d887e.png">

**Comment by vim-usds** [comment]
engineering review needed
