### ISSUE TITLE
As an EVCM, I want to get a sense of prioritized communities at the national (zoomed out) level, so that I get quick indication of whether my community is on the list. 

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#109]
**Description**

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**

**Comment by katherinedm-usds** [comment]
Sending this to the Icebox as we haven't conceptualized enough how this would be done. We have talked about and reviewed mockups of the national view showing pins of the most prioritized spots, but there's a lot to do to flesh that out.
