### ISSUE TITLE
As a repo contributor, I want to make sure my frontend code passes checks before/after it is merged, so that we maintain a high standard of quality and consistency

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#11]
**Description**
We should implement the best practices of continuous integration of source code, meaning performing a series of checks for PRs

**Solution**
Set up minimal pipelines with a chosen CI tool such as Github Actions/Jenkins/TravisCI that implement the above checks

**Describe alternatives you've considered**
The alternative is to not perform these checks, which can lead to ruin.

**Links to user research or other resources**
N/A

**Tech Tasks**
- [x] Linting/formatting (eg eslnt, prettier)
- [x] Security auditing (eg `npm audit`)
- [x] License check (eg `license-checker`)
- [x] Dependency updating (eg dependabot etc)
- [x] Container-based unit testing / reporting (eg jest, junit)
- [x] Integration testing (e.g. puppeteer)
- [x] Snapshot testing (jest-snapshot, etc)

**Definition of "Done"**
- [ ] Checks run on every PR
- [ ] We have identified a basic set of tests that run on every PR / Commit and these are running regularly and producing results

**Comment by switzersc-usds** [comment]
Status update: In progress, some of these may be higher priority than others.
