### ISSUE TITLE
Tabbing should move through the site navigation headers before moving to an element like search

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1105]
**Describe the bug**
This is better experienced than written but I will give it a go. Basically per the USWDS guidelines "tabbing" is an important accessibility feature that lets users move through the site (that may need assistance in doing so). I'm seeing this behave a little differently on the different pages so I will try to capture what I am seeing.

**To Reproduce**
1. Go to 'About' page
2. Click 'tab' key
3. Focus seems to go to the browser

1. Go to 'Explore the tool' page
2. Click 'tab' key
3. Focus seems to move to the search bar

1. Go to the 'Methodology & data' page
2. Click 'tab' key
3. Focus seems to move to the browser

1. Go to the 'Contact' page
2. Click 'tab' key
3. Focus seems to move to the browser

**Expected behavior**
Per the USWSD header component guidance
_Include tab focus for all top-level navigation navigation items — this will allow keyboard-reliant users to easily navigate interactive items.
_Ensure your horizontal navigation is keyboard compatible; test to make sure users can use Tab to navigate and Space (or Enter) to open pages.__

**Screenshots**
<img width="993" alt="Screen Shot 2022-01-05 at 2 48 36 PM" src="https://user-images.githubusercontent.com/77702996/148300705-0def746d-851f-420e-9495-fc3ef07d7647.png">

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Safari

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger - seems like tabbing is working well now! Closing this!
