### ISSUE TITLE
Implement new copy for Methodology & Data page for handling territories

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1106]

**Comment by KameronKerger** [comment]
[Methodology_+_Territories.pdf](https://github.com/usds/justice40-tool/files/7823454/Methodology_%2B_Territories.pdf)

**Comment by KameronKerger** [comment]
updated version to show a line break when there are multiple sources for a data category
[Methodology_+_Territories_v2.pdf](https://github.com/usds/justice40-tool/files/7842145/Methodology_%2B_Territories_v2.pdf)
