### ISSUE TITLE
Funny business is happening with the territory side panel 

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1118]
**Describe the bug**
For some reason (this is maybe on purpose) but census tracts in Guam are no longer selectable. When I was able to select them, tracts were showing up as disadvantaged but there was no data being used to make that designation. I will also posit that the side panel design can be improved for the territories.

**To Reproduce**
1. Go to 'Explore the tool'
2. Click on 'Guam'
3. Zoom in 'Can't select census tract + designation is off.'

**Expected behavior**
Census tracts should be selectable and there should be some better way to understand / represent the data beyond just -- especially when it is not expected to be there (like the whole category)

**Screenshots**
<img width="835" alt="Screen Shot 2022-01-10 at 1 47 39 PM" src="https://user-images.githubusercontent.com/77702996/148844617-9e4eb698-86fd-41b4-94fb-e341e8f06c28.png">
<img width="175" alt="Screen Shot 2022-01-10 at 1 47 48 PM" src="https://user-images.githubusercontent.com/77702996/148844626-ba0237c4-1500-487f-a127-cc5ee25ff42e.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Safari

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger - are we still seeing this?

**Comment by KameronKerger** [comment]
no because we don't have data for Guam @vim-usds
