### ISSUE TITLE
As a comparison tool user, I want to remove `other_census_tract_fields_to_keep` which doesn't do anything

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#1129]
**Description**
`other_census_tract_fields_to_keep` is part of some old code and is no longer used anywhere. This ticket removes it.

**Comment by saran-ahluwalia** [comment]
I think we can close this @lucasmbrown-usds?

**Comment by lucasmbrown-usds** [comment]
Closed in #1130
