### ISSUE TITLE
Make the free version of the map enabled by default so that open source contributors/users don't have to have API key for paid version

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1133]
From slack - possible solution:

Free map is always on -> switch to paid
- for staging and production env
     - feature flag is set to switch to a paid map via URL, e.g, ?flags=map_type_paid
          - this flag loads API key from the .env.prod file and loads paid map.
- since the API key is placed in .env files and .env files are placed into .gitignore (see note)
- for a local dev that tries to load the map locally
     - it works by default as the free map
     - when trying to set the feature flag to paid via ?flags=map_type_paid
          - map will not load unless they have the our key OR
          - they create an account and get their own API key and place into .env.dev

currently the .env.* are in .gitignore so this will break the docker map

**Comment by vim-usds** [comment]
closed with the last PR 1155
