### ISSUE TITLE
High school degree achievement rate is not blue in the side panel when it should be

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1148]
The high school degree achievement rate should be blue if it is between the values of 0 and 89. 

Example tract where it should be blue and isn't:
https://d29zfl8cj7y1zf.cloudfront.net/en/cejst#14.65/24.55716/-81.78308

**Comment by KameronKerger** [comment]
here are some additional non blue but should be things. happening for [this tract](https://d29zfl8cj7y1zf.cloudfront.net/en/cejst/?#9.8/29.3822/-103.5352).
<img width="206" alt="Screen Shot 2022-01-20 at 12 03 20 PM" src="https://user-images.githubusercontent.com/77702996/150414144-ec4ee4c5-6981-4758-aaf4-fa96532ddb45.png">
<img width="207" alt="Screen Shot 2022-01-20 at 12 05 27 PM" src="https://user-images.githubusercontent.com/77702996/150414148-8b0078d5-0436-4f7f-adbd-2764b26a6b18.png">

**Comment by vim-usds** [comment]
Hi  @esfoobar-usds, @lucas and @BethMattern 

I was incorrect in stating that this was controlled by a threshold value in the frontend. It's actually sent as a boolean by the backend. See the pic below:

![Screen Shot 2022-01-20 at 3.42.35 PM.png](https://images.zenhubusercontent.com/60d4d92c1bf5e498d6e808ba/f14636ed-f536-4d68-b6dd-40594b98584e)

We can see that the boolean that is controlling this "High School degree ... rate" indicator is `false`, which is why it's not blue. _Is there a new boolean for this indicator?_

My guess is, if there is a new boolean, it's not in this selected CBT. Here's why I'm thinking that:

Here's the full list of indicator / values from this selected CBT:

```
AF_PFS: 0.09
ALI: false
CF: "Monroe County"
DF_PFS: 0.48
DLI: false
DPMLI: false
DSF_PFS: 0.49
EALRLI: false
EBF_PFS: 0.08
EBLI: false
EBLRLI: false
EBLR_PFS: 0.85
EPLRLI: false
EPLR_PFS: 0.97
FPL200S: false
GEOID10: "12087972200"
HBF_PFS: 0.74
HBLI: false
HDF_PFS: 0.51
HDLI: false
HSEF: 0.1384434884630426
HWLI: false
IALHE: 0
IALMILHSE: false
IAULHSE: false
ISPLHSE: false
LHE: 1
LIF_PFS: 0.92
LILHSE: true
LLEF_PFS: 0.4
LLELI: false
LMILHSE: false
LMI_PFS: 0.15
LPF_PFS: 0.73
LPMHVLI: false
MHVF_PFS: 0.88
M_CLT: false
M_ENY: false
M_HLTH: false
M_HSG: false
M_PLN: false
M_TRN: false
M_WKFC: true
M_WTR: false
NPL_PFS: 0.02
P100_PFS: 0.6
P200_PFS: 0.36
PLHSE: false
PM25F_PFS: 0.17
PM25LI: false
RMPLI: false
RMP_PFS: 0.56
SF: "Florida"
SFLI: false
SM_C: true
SM_PFS: 1
TC: 1
TF_PFS: 0.76
TPF: 3361
TPLI: false
TSDF_PFS: 0.4
UF_PFS: 0.09
ULHSE: false
WDLI: false
```

Filtering out the truthy values from this leads to:
```
LHE: 1  // not being used in frontend - should it be?
LILHSE: true //  being used to signal that linguistic iso should be blue
M_WKFC: true // being used to signal that the category should be blue
SM_PFS: 1 // being used to shade in the DAC
TC: 1 // being used as the total number of DACs
```

So maybe `LHE` should be used? If this [file](https://justice40-data.s3.amazonaws.com/data-pipeline/data/score/csv/tiles/tile_indexes.json) represents the latest indicators (which I'm not sure if it does), LHE stands for "Low high school education and low college attendance"

Two reasons I think LHE may not be the right one to use:
1. It's not a boolean
2. college attendance seems to be TDB?

### Solutions
1. The frontend can start to determine if indicators should be blue 
2. The backend can send the appropriate boolean

Lastly, If we do this, I would like to suggest that we add a column to our shared drive file "Indicators for UI and Export", with the abbreviated terms for each side panel indicator. Adding this to our discussion board topic.

**Comment by vim-usds** [comment]
@KameronKerger - you posted some screenshots of other fields that should be blue. Can you write out which fields exactly and their threshold? Like this:

> The high school degree achievement rate should be blue if it is between the values of 0 and 89.

**Comment by vim-usds** [comment]
@Lucas and @Beth need to investigate some things to solidify Def M. Once these things have been identified, please update this ticket.

**Comment by lucasmbrown-usds** [comment]
Arlight, so to create a user experience like this: 

![Screen Shot 2022-02-02 at 12.07.16 PM.png](https://images.zenhubusercontent.com/60994884083be1f80a1e4211/b939d675-c62c-4bff-86e2-36a142f30a35)

Note (cc @KameronKerger ): this screenshot is actually wrong, it's not a percentile, it's a percent, so it should not have the "th" and it should have a %. 

You're gonna need the percent for high-school degree achievement -- this has the same name as before: 

```
field_names.HIGH_SCHOOL_ED_FIELD: "HSEF"
```

Where `field_names.HIGH_SCHOOL_ED_FIELD = (
    "Percent individuals age 25 or over with less than high school degree"
)`. 

You'll also need the boolean for high school degree achievement AND low higher ed. The short name for this field is "LHE". That's the same short-name as, in Def L, what was just high school degree achievement.

In defintion M this will be: 

```
    field_names.LOW_HS_EDUCATION_LOW_HIGHER_ED_FIELD: "LHE",
```

where Where `field_names.LOW_HS_EDUCATION_LOW_HIGHER_ED_FIELD = (
    "Low high school education and low percent of higher ed students"
)`.

This was updated as part of https://github.com/usds/justice40-tool/pull/1190 so should be ready when the GHA finishes.

Does this unblock you?

**Comment by vim-usds** [comment]
@lucasmbrown-usds - I believe it does yes. 

A little nitty nit is that when decoding the tiles, the `LHE` field seems to be of type `int` and not `boolean` (see the bottom of the decoded tile below):

```json
{
  "type": "Feature",
  "properties": {
    "GEOID10": "47057500300",
    "SF": "Tennessee",
    "CF": "Grainger County",
    "DF_PFS": 0.85,
    "AF_PFS": 0.7,
    "HDF_PFS": 0.9,
    "DSF_PFS": 0.21,
    "EBF_PFS": 0.72,
    "EALR_PFS": 0.77,
    "EBLR_PFS": 0.62,
    "EPLR_PFS": 0.67,
    "HBF_PFS": 0.13,
    "LLEF_PFS": 0.86,
    "LIF_PFS": 0.38,
    "LMI_PFS": 0.49,
    "MHVF_PFS": 0.21,
    "PM25F_PFS": 0.91,
    "HSEF": 0.2232356134636265,
    "P100_PFS": 0.71,
    "P200_PFS": 0.65,
    "LPF_PFS": 0.42,
    "NPL_PFS": 0.17,
    "RMP_PFS": 0.12,
    "TSDF_PFS": 0.12,
    "TPF": 6519,
    "UF_PFS": 0.29,
    "WF_PFS": 0.85,
    "M_WTR": false,
    "M_WKFC": false,
    "M_CLT": false,
    "M_ENY": true,
    "M_TRN": false,
    "M_HSG": false,
    "M_PLN": false,
    "M_HLTH": true,
    "SM_C": true,
    "SM_PFS": 1,
    "EPLRLI": false,
    "EALRLI": false,
    "EBLRLI": false,
    "PM25LI": true,
    "EBLI": false,
    "DPMLI": false,
    "TPLI": false,
    "LPMHVLI": false,
    "HBLI": false,
    "RMPLI": false,
    "SFLI": false,
    "HWLI": false,
    "WDLI": false,
    "DLI": false,
    "ALI": false,
    "HDLI": true,
    "LLELI": false,
    "LILHSE": false,
    "PLHSE": false,
    "LMILHSE": false,
    "ULHSE": false,
    "LHE": 1,  //    <-- HERE
    "FPL200S": true,
    "TC": 2,
    "IAULHSE": false,
    "ISPLHSE": false,
    "IALMILHSE": false,
    "IALHE": 0
  }
}
  ```
  
Decoding 3 random tiles (from S3 after cache invalidation) resulted in values `0,0,1`. So it might be safe to assume that the `LHE` field will always have values of either `0` or `1`. ❓ 
  
 I can coerce (0 = false and >0 is true) this easily on the frontend, however it might be better to have these be explicitly boolean, aka `true` or `false`, as this might better capture the field's purpose.

**Comment by vim-usds** [comment]
Will move forward with coercing on frontend until I hear otherwise

**Comment by vim-usds** [comment]
@emma-nechamkin - can you validate my understanding that the LHE field is indeed an `int` and not `boolean`. No rush as it's not a blocker

**Comment by emma-nechamkin** [comment]
@vim-usds just confirming -- this aligns with what I see in the tiles csv (only values of 0 and 1). I think this is because we coerce it to a float in the back end (see line 194 of `constants.py`) and I will make an issue to fix it.

**Comment by vim-usds** [comment]
@emma-nechamkin yeah let's see what Lucas comes back with
