### ISSUE TITLE
add tribal note to the UI

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1174]
see copy / email from Sharmila

**Comment by KameronKerger** [comment]
[two_territories_notes_near_term.pdf](https://github.com/usds/justice40-tool/files/7966525/two_territories_notes_near_term.pdf)
[two_territories_notes_stretch_goal.pdf](https://github.com/usds/justice40-tool/files/7966527/two_territories_notes_stretch_goal.pdf)

**Comment by vim-usds** [comment]
Use living copy for this
