### ISSUE TITLE
Front end updates to variables used by definition M

### ISSUE THREAD

**Issue by emma-nechamkin** [usds/justice40-tool#1183]
**Description**

When implementing Definition M, I (Lucas) took a few shortcuts.

In order to quickly finish Definition M, I continued to use fields like the following:

```
UNEMPLOYMENT_LOW_HS_EDUCATION_FIELD = (
    f"Greater than or equal to the {PERCENTILE}th percentile for unemployment"
    " and has low HS education"
)
```

However, this is inaccurate now, because it should now be something like:

```
UNEMPLOYMENT_LOW_HS_LOW_HIGHER_ED_FIELD = (
    f"Greater than or equal to the {PERCENTILE}th percentile for unemployment"
    " and has low HS education and low higher ed attendance"
)
```

Note the change in both the variable name AND the field string value.

We need to keep the "old" field names/values so they can continue to be used for Score L, but then update these for score M.

I believe this involves touching all of the following parts of the code on the front end:

- [ ] Update text descriptions of data on methodology page
- [ ] Update the reverse dictionary translating short names on tiles back to full names (maybe not necessary if we keep the abbreviations in TILES_SCORE_COLUMNS the same)
- [ ] Update full names of variables in side bar
- [ ] Update text descriptions of variables in side bar

**Comment by lucasmbrown-usds** [comment]
Need design input from @KameronKerger @glennettec on what these changes should look like.

**Comment by vim-usds** [comment]
@lucasmbrown-usds , @BethMattern , @glennettec and @KameronKerger 

Here are some of the UI changes Emma and I came up with to incorporate Def M. This has also been captured in the living document. All feedback welcome!

# Low income box:
## From this
![Screen Shot 2022-01-31 at 11 37 03 AM](https://user-images.githubusercontent.com/86254807/151861895-650e2ed4-bd44-435d-a79c-1fda03c33a63.png)

## To this
![Screen Shot 2022-01-31 at 11 44 16 AM](https://user-images.githubusercontent.com/86254807/151861920-4c76cb7a-e98d-4fd9-9d77-bc3c27c68540.png)


# Categories
## All categories
### FROM
![Screen Shot 2022-01-31 at 11 47 55 AM](https://user-images.githubusercontent.com/86254807/151862306-44d7ca18-27e9-481b-b7b8-fc22d66c348e.png)

### TO
![Screen Shot 2022-01-31 at 11 48 06 AM](https://user-images.githubusercontent.com/86254807/151862324-cab4c19a-ad64-4978-b563-9125eb0d8fe1.png)

## Workforce category
### FROM
![Screen Shot 2022-01-31 at 11 50 20 AM](https://user-images.githubusercontent.com/86254807/151862756-496f7a0d-a6d1-46bd-9b74-18f8d8997d68.png)

### TO
![Screen Shot 2022-01-31 at 11 51 30 AM](https://user-images.githubusercontent.com/86254807/151862797-35200016-8f46-406f-9b0c-ce50ab050668.png)


# new Dataset
![Screen Shot 2022-01-31 at 11 57 32 AM](https://user-images.githubusercontent.com/86254807/151863754-5ef846aa-e61b-4e59-9c83-198ecec2440a.png)

**Comment by vim-usds** [comment]
The above UI changes are no longer applicable. @KameronKerger will update this ticket with mocks and point to the various places in the Living Copy doc along with the Indicators doc. 

The tiles (on S3) should now have certain fields required to implement this ticket. Once the mocks are available. Will work with @emma-nechamkin on identifying the proper fields to use.

**Comment by KameronKerger** [comment]
[Methodology_scoreM.pdf](https://github.com/usds/justice40-tool/files/7989801/Methodology_scoreM.pdf)
[Updated_side_panel_text_Score_M.pdf](https://github.com/usds/justice40-tool/files/7989802/Updated_side_panel_text_Score_M.pdf)

**Comment by KameronKerger** [comment]
sorry cut&paste error on top of methodology 
[Methodology_scoreM.pdf](https://github.com/usds/justice40-tool/files/7990415/Methodology_scoreM.pdf)
