### ISSUE TITLE
Make sure workforce development fields for Island areas appear in the UI sidebar

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#1189]
**Description**
Right now, the sidebar panel in the island areas does *not* show any data from the workforce development category even if that data exists for the tract one of those territories. 

This is because that data for the territories is written to a differently named column: eg., in data/data-`pipeline/data_pipeline/score/score_m.py`, the two fields are `field_names.ISLAND_AREAS_UNEMPLOYMENT_LOW_HS_EDUCATION_FIELD` versus `field_names.UNEMPLOYMENT_LOW_HS_EDUCATION_FIELD`. 

`field_names.UNEMPLOYMENT_LOW_HS_EDUCATION_FIELD` is what gets written to the tiles and interpreted by the UI to show up in the sidebar. 

**Solution**
TBD.

**Describe alternatives you've considered**
Possible approaches: 

1. In the backend, create a single field that combines both, e.g., field_names.ISLAND_AREAS_UNEMPLOYMENT_LOW_HS_EDUCATION_FIELD and field_names.UNEMPLOYMENT_LOW_HS_EDUCATION_FIELD into a single field that can be shown by the UI. 

2. In the backend, write both fields to the tiles, and in the frontend, write some logic that uses one of the two fields depending on which one is present (or whether or not you're in the island areas).

**Comment by emma-nechamkin** [comment]
PROPOSED SOLUTION: For the front end to best produce sidebars that vary based on what type of data is being shown -- three source variable will specify whether a file pertains to Islands (USVI, GU, AS, MP), Puerto Rico (PR), or the rest of the US.

**Comment by lucasmbrown-usds** [comment]
A couple other small notes from that discussion: 

1. Put total number of possible thresholds as a column in the tiles data (in US: 21, in PR: 5, in Island Areas: 4)
2. Add island areas workforce development percentile columns to tiles
