### ISSUE TITLE
Update copy based on updates from CEQ provided 1/28/22

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1197]
**Describe the bug**
Update copy based on changes from CEQ

**To Reproduce**
1. Go to 'website'
2. Click on 'any page.'
3. See previous copy

**Expected behavior**
Update copy based on changes from CEQ 1/28/22 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KameronKerger** [comment]
updated so I can add the issue # to the living copy doc

**Comment by BethMattern** [comment]
At CEQ for final approval/lockdown
