### ISSUE TITLE
The linguistic isolation short description in the side panel is weird / needs updating

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1203]
**Describe the bug**
The words "limited" and "speaking" are weird and it could be shortened / improved

**To Reproduce**
1. Go to 'Explore the tool'
2. Click on 'a census tract'
3. Scroll down to 'Workforce development > Linguistic isolation.'
4. See error - Percent of limited speaking households, which are households where no one over age 14 speaks English well

**Expected behavior**
Update to 
Percent of households where no one over the age 14 speaks English well

**Screenshots**
<img width="232" alt="Screen Shot 2022-01-29 at 10 27 10 AM" src="https://user-images.githubusercontent.com/77702996/151672974-7dcb04dc-3aed-426e-b6e4-a69afe5955ee.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
This was merged in a previous ticket

**Comment by vim-usds** [comment]
This was merged in a previous ticket
