### ISSUE TITLE
Download Packet Changes Round 3

### ISSUE THREAD

**Issue by esfoobar-usds** [usds/justice40-tool#1215]
@KameronKerger requested the following changes to the download packet:

- [x] GEOID10_TRACT should be Census tract ID
- [ ] Can the alignment of all the fields be consistent? headers centered, words centered, numerical values right aligned
- [x] Can we change "Total threshold criteria exceeded" to "Total number of at or above thresholds criteria" so it is consistent with the site content?
- [ ] Can we change low college attendance to high college enrollment? I'll bring this up during score M discussions today but "attendance" makes it seem like people aren't going to school... this should be done already?
- [ ] I think the FEMA data is just "NationalRisk Index" and not "Natural Hazards Risk Index"
- [ ] We should spell out the Superfund acronym since we do the others. it's National Priorities List
- [ ] For asthma we can probably remove "Current" so it just starts with "Asthma"
- [ ] Same for "Diagnosed diabetes" so just "Diabetes" (this will make it more consistent with the site
- [ ] Overall can we make the columns a little smaller? Do if it is at like 30 make it more of a 20

**Comment by BethMattern** [comment]
@esfoobar-usds to pair with @emma-nechamkin

**Comment by esfoobar-usds** [comment]
Assigning to @KameronKerger until we get a solid list of changes.
