### ISSUE TITLE
Set up domain + SSL cert on Geoplatform

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#123]
Once we have our domain, we need to configure or make the request to Geoplatform to set up the SSL cert for our domain. 

**Definition of Done**
A user can navigate to our domain with `https` and see our website.

**Comment by BethMattern** [comment]
@switzersc-usds Joel needs to know the name of the load balancer or cloudfront to point the name to

**Comment by switzersc-usds** [comment]
Closing as a duplicate of the more detailed #207
