### ISSUE TITLE
Implement Backend Staging Hash on Frontend

### ISSUE THREAD

**Issue by esfoobar-usds** [usds/justice40-tool#1239]
We need to be able to communicate to the frontend app via the URL to pull from a different S3 endpoint, which would be the variable staging folder generated on a backend PR.

@vim-usds to coordinate with @esfoobar-usds

**Comment by vim-usds** [comment]
@jorge - one way to implement this could be to set a feature flag?

So let's say the I want the data source to point the staging data source. One way could be to add the following to the URL:

`?stage-hash=1323/asdf987asdferybhiuyv23455`

the staging URL is uniquely identifiable by it's PR and hash. This would allow us to change from prod data to staging endpoints.

Is this what you were thinking?

**Comment by esfoobar-usds** [comment]
That's a totally perfect implementation route!
