### ISSUE TITLE
As a developer, I want to deploy certain (or all) parts of my data pipeline continuously, so that I don't have to rely on manual steps.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#124]
**Description**
We have the artifacts for deployment from geoplatform; now we just need to get them deployed. At minimum the core pieces of the data and score pipeline need to be deployed and integrated into CI/CD using Github Actions: changes to score code merged to `main` should trigger a re-run of the ETL and scoring algorithm, so that new data shows up automatically on the deployed map.

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**
- [ ] Update the CI/CD pipeline
- [ ] Push to AWS

**Definition of "Done"**
- Code is deployed to AWS
- Updated CI/CD code
- Specifically, changes to the score code that are merged to `main` trigger a re-run of the ETL and scoring algorithm in the coud, and new data shows up on automatically on our deployed map

**Comment by switzersc-usds** [comment]
@ginabeena Closing this since we were able to deploy. Let's sync tomorrow to see if there are smaller follow up tickets out of this.

**Comment by ginabeena** [comment]
https://s3.console.aws.amazon.com/s3/buckets/j40-stg-us-east-1-justice40-data-harvester?region=us-east-1&prefix=serverless/justice40-data-harvester/stg/&showversions=false

is the link for viewing our data from the harvester function
