### ISSUE TITLE
Fix failing automated job, part 1: Cypress tests

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#125]
**Describe the bug**
Our nightly e2e cypress tests are failing: https://github.com/usds/justice40-tool/actions/runs/934539208 

**To Reproduce**
See above builds - (1) occurs every day 4am, (2) occurs when you commit a diagram to a PR branch and then merge to main

**Expected behavior**
Builds should succeed

**Screenshots**
N/A

**Desktop (please complete the following information):**
 All

**Smartphone (please complete the following information):**
N/A

**Additional context**
None

**Comment by vim-usds** [comment]
was able to change the working directory so the tests now find the `package-lock` file. This was the initial error.

The next layer of the onion is now github actions are not able to see the server. Investigating that next.

**Comment by vim-usds** [comment]
The cypress tests in CI (via GH actions) now match the local tests. All 4 of our cypress tests fail locally. Another ticket should look into why the cypress tests are failing locally.

Once those tests pass, we may want to look into turning this 4 am cron job into something that happens on every push or PR.

**Comment by vim-usds** [comment]
Also due to a fairly crazy commit history of trying and failing various things that don't mean anything now, all commits were rebased into a single commit.
