### ISSUE TITLE
Puerto Rico missing data

### ISSUE THREAD

**Issue by emma-nechamkin** [usds/justice40-tool#1278]
In issue 1189, we assumed that island areas only had workforce development (except AMI) and Puerto Rico also had AMI. This doesn't seem to bear out in the data. First, PR has >5 threshold criteria. Second, PR doesn't have AMI. 

In this ticket, we will update map to reflect only information we have for PR that we are confident in. 

IN A FUTURE TICKET:
(1) identify what information we have to show on the map for PR, and (2) update the three state variables to include the *proper* information.

**Comment by BethMattern** [comment]
Emma would like a peer review on this.
