### ISSUE TITLE
As a repo contributor, I want to be able to install and run all code locally, so that I can actively contribute.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#13]
**Description**
This is about making sure internal and external contributors can onboard to the codebase quickly and easily.

**Solution**
- [x] Add clear install steps and dependencies to the README.
- [ ] Containerize app so that it's easily portable across machines.

**Describe alternatives you've considered**
N/A

**Links to user research or other resources**
N/A

**Definition of "Done"**
- [ ] A new developer confirms they can get up and running locally with the code base in a container with no support from a team member

**Comment by NatHillardUSDS** [comment]
There is a push and pull here with github actions, which uses its own container. 

There is the tool [act](https://github.com/nektos/act) that let you run gha locally in docker, but this seems a bit imperfect, and has a few limitations, like not allowing you to use the upload/download actions...

Something like [this setup](https://valenciandigital.com/blog/containerizing-a-gatsbyjs-site-with-docker-compose) would work locally - we would want both dev and prod variants - and I've been experimenting with this. It has the added benefit of abstracting away local dev environment, which has already caused a few headaches. We should probably do this anyway.

A remaining task is to bundle together all the checks currently run on gha so we can run them locally as well. 

We should timebox this - simplest is to update readme, second most is to add a single action that runs all CI actions, third most is to create a local dev docker container, hardest is to unite these together. I can progress through these in this order this afternoon and see how far I get.

**Comment by switzersc-usds** [comment]
@ginabeena - this card is related to the convo we had today on adding install steps, etc, to the README.

**Comment by ginabeena** [comment]
yeah, thanks for assigning :) I'll be commenting on this and working through it @NatHillardUSDS @switzersc-usds

**Comment by ginabeena** [comment]
Any one else getting transitive dependency issues during `npm install` in `/client` right now? I'm getting issues resolving from the lock. I can paste `node v16.3.0` and `npm v 7.15.1`

**Comment by NatHillardUSDS** [comment]
We've been on v14.17.0 because Trussworks seems to require a version <14 - the format of the lockfile and the way dependencies are resolved appears to have changed between those versions . With 14.17.0 at least I'm not seeing these issues, can you try with that?

**Comment by switzersc-usds** [comment]
@NatHillardUSDS @ginabeena status here?
