### ISSUE TITLE
Color key missing from legend box above the map

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1303]
**Describe the bug**
Somewhere along the way we lost the words "Color key" above the blue dot in the legend box above the map on the Explore the tool page.

**To Reproduce**
1. Go to 'Explore the tool'
2. Scroll down to 'above the map'
4. See error in legend

**Expected behavior**
Add the words "Color key" back above the blue dot (see screenshot)

**Screenshots**
Error -
<img width="420" alt="Screen Shot 2022-02-17 at 3 03 18 PM" src="https://user-images.githubusercontent.com/77702996/154586108-baea4eda-e2fe-4bb1-a2ee-84f01449ff04.png">
Design - 
<img width="503" alt="Screen Shot 2022-02-17 at 3 01 40 PM" src="https://user-images.githubusercontent.com/77702996/154586132-94e290bc-c57c-4427-9e22-500f13ee2156.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KameronKerger** [comment]
also we can add the stroke back in around the circle.
same color as inside (1A4480), just 100% alpha.

**Comment by vim-usds** [comment]
ok cool! 

Wondering that the side panel also has this circle.. we'll want to change it there as well right?

**Comment by KameronKerger** [comment]
we had a reason to remove it and now I don't remember why... let's leave that as is for now? I don't know. I am decided out for today.
