### ISSUE TITLE
SEO for screeningtool.geoplatform.gov

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1312]

**Comment by glennettec** [comment]
![image.png](https://images.zenhubusercontent.com/60e71e455052ef541fcc40c3/3225522b-c592-47a5-aa1e-abab2c9f9c0b)

**Comment by glennettec** [comment]
most search engines use the hierarchy of "H" tags during indexing in addition to the meta tags.
Quick fixes
about page
[ ] update H1 tag to "about CEJST" 
[ ] update the h2 tag to "climate and economic justice screening tool"

Explore the tool
[ ] update H1 tag to "explore CEJST" or "explore the Climate and Economic Screening Tool"
[ ] use keywords in the H2 tags 

Methodology & data
[ ] update H1 tag to "methodology & data"
[ ] update H2 tag for "categories" to be more descriptive
