### ISSUE TITLE
Get team members access to Google Analytics

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1313]
All team members need to have access.

https://digital.gov/guides/dap/

**Comment by BethMattern** [comment]
@vim-usds will attach details on how to access this here

**Comment by vim-usds** [comment]
Here's how we can all access the analytics:

https://github.com/usds/environmental-justice/blob/main/engineering/software/GoogleAnalytics.md

it's also pinned in our analytics channel in slack
