### ISSUE TITLE
Add "the" in front of the percentiles in several places in the categories

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1315]
**Describe the bug**
See living copy for the "the"s that need to be added.

**To Reproduce**
1. Go to 'Methodology'
2. Scroll down to 'formulas'

**Expected behavior**
**IF** the census tract is above the threshold for one or more environmental or  climate indicators 
**AND** the tract is above the threshold for the socioeconomic indicators. 

**Screenshots**

one examp
<img width="527" alt="Screen Shot 2022-02-18 at 11 30 54 AM" src="https://user-images.githubusercontent.com/77702996/154750977-5bfe8f76-a8c0-4d12-a660-ce61dc5531b9.png">
le of the missing the

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger 

## Change 1
Is my understanding correct, that we saying that we want to replace "is above" with "exceeds" in all places on the methodology page?

Also is my understanding correct that if it says "is at or above" that we will NOT change that?

## Change 2 
Is my understanding correct that we should place "the" before every instance of a percentile value on the methodology page. Ie, change from "is above 65% percentile" to "is above **the** 65th percentile"?

**Comment by KameronKerger** [comment]
### change 1
no, just the main methodology section
<img width="566" alt="Screen Shot 2022-02-22 at 2 38 39 PM" src="https://user-images.githubusercontent.com/77702996/155231512-6a85268c-adeb-4d59-b24b-1d0de064f452.png">

### change 2
yes, this impacts each of the categories. you should be able to get there by referencing living copy and this ticket number. For example, in climate change (note, it should not be bolded just bolding here so you can note the change):
IF at or above **the** 90th percentile for [expected agriculture loss rate](https://screeningtool.geoplatform.gov/en/#exp-agr-loss-rate) OR [expected building loss rate](https://screeningtool.geoplatform.gov/en/#exp-bld-loss-rate) OR [expected population loss rate](https://screeningtool.geoplatform.gov/en/#exp-pop-loss-rate)
AND is above **the** 65th percentile for [low income](https://screeningtool.geoplatform.gov/en/#low-income) AND at or below 20% for [higher ed enrollment rate](https://screeningtool.geoplatform.gov/en/#high-ed-enroll-rate)

**Comment by BethMattern** [comment]
Moving this out of the sprint because now this is in question.

**Comment by vim-usds** [comment]
@KameronKerger - this issue will only add "the" to various places in the copy
