### ISSUE TITLE
As an app developer, I want the uploads to S3 and deletions of S3 files to be parallelized, so I can reduce the app deploy times by up to 20 minutes. 

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#1319]
**Description**
The parts of the full score and tiles deployment process that take the longest are: 

1. Deleting all previous tiles from S3 
2. Uploading all new tiles to S3 

This takes a long amount of time (20 minutes?). 

There are a few well-known solutions to addressing this: https://stackoverflow.com/a/53336858/1569221.  In that example they took upload times from 10 minutes to 18 seconds. There might be some other known approaches. 

Also as part of this PR, will add invalidation of backend cloudfront

**Comment by esfoobar-usds** [comment]
There's also a parallel delete library here:
https://github.com/eschwim/s3wipe
