### ISSUE TITLE
DACs don't show up for WY until you zoom > 7

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1320]
It appears to not show any disadv. communities for zoom < 7, and then shows them for zoom > 7. This is the transition point from “low zoom” to “high zoom” tiles.

This doesn't seem to be the case for other states.

**Comment by esfoobar-usds** [comment]
The reduction algorithm is working as intended. The issue with WY is that it's a huge state with few DACs that sit next to each other, so there are no visible "blotches" when you zoom out.

@emma-nechamkin, @vim-usds and I proposed to do a count of DACs over total tracts and if the number is less than a threshold, to promote the DACs geometries and transpose them in the high zoom layer.

**Comment by vim-usds** [comment]
@esfoobar-usds and @emma-nechamkin - I'm not sure about any of this, wondering if we need to take the size of the state into account as well?

**Comment by esfoobar-usds** [comment]
@vim-usds no need to take into consideration state size, per our post-standup discussion
