### ISSUE TITLE
Add RFI link (once it becomes available)

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1321]
**Describe the bug**
Link to federalregister.gov/whatever the link is to link to the CEJST RFI.

**To Reproduce**
1. Go to 'Explore the tool'
2. Scroll down to 'links below the map'

**Expected behavior**
Once the RFI is available, we need to link to it.

**Screenshots**
<img width="580" alt="Screen Shot 2022-02-22 at 9 32 29 AM" src="https://user-images.githubusercontent.com/77702996/155186628-231f055e-c214-4ea4-8ca4-cec50411a6d2.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@BethMattern and/or @KameronKerger - is this the right link for the RFI?

https://www.federalregister.gov/documents/2021/05/05/2021-09109/methods-and-leading-practices-for-advancing-equity-and-support-for-underserved-communities-through

**Comment by KameronKerger** [comment]
nope @vim-usds , ours isn't live yet but it will be at: 
https://www.federalregister.gov/d/2022-03920
