### ISSUE TITLE
(Comparison tool 0.1) As a stakeholder interested in the CEJST score, I want to see a report comparing the CEJST score to one other index, so that I can understand where the CEJST score generates results that are very different than another index.

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#135]
**Description**

This is essentially the "MVP" of the comparison tool. We want to see some basic analytics comparing one version of the CEJST score to one known index. 

In a future ticket, we will add support for multiple draft versions of the CEJST score for comparison.  We will also add support for more comparison indices, and more detailed analytics on the comparison. These other indices have been peer-reviewed and validated  through years of academic research; comparing different versions of the CEJST score to them provides a quick way to flag potential outliers in the CEJST score where it may need to be tweaked to provide a more reliable designation of overburdened and underserved communities.

Note that most of these indices are created at a higher geographic unit than census block group, such as census tract. This report will require a methodology for comparing indices at the unit of census tract (or county, etc) against a CEJST score at the unit of census block group.

**Solution**
A Python script or notebook that loads (1) a comparison index and (2) a current CEJST score and produces a report based on the differences between the two scores. 

**Describe alternatives you've considered**
Not having a quantitative comparison method and relying on qualitative feedback about whether the score looks representative of the most overburdened and underserved communities. Qualitative feedback is more piecemeal and moves slower, but is an important piece of feedback in combination with this work. 

**Tasks**
* Identify the top index as prioritized by https://github.com/usds/justice40-tool/issues/133. 
* Load that index.
* Load the initial CEJST score as created by https://github.com/usds/justice40-tool/issues/48
* Calculate comparison metrics between the scores
* Produce a report (such as a CSV, or a map with differences visualized, etc) that summarizes the difference between these scores

**Definition of "Done"**
* Report is ready for review with internal stakeholders

**Comment by switzersc-usds** [comment]
Waiting on scoring code.
