### ISSUE TITLE
Research additional data sources from CEJST feedback 

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1356]
The following data sources have been raised as potential additions to the methodology:

- Abandoned Mines
- Public transit / clean transit

**Comment by KameronKerger** [comment]
From the survey as of 3/3/22:
(ideas)
- Clean Transit Indicators (does not include income, higher-ed pursuit). I would like to see this for the other categories as well.
- Water Systems with violations, National Walkability Index, School District Performance 
- I am looking at NASA products that might also give some information on current conditions
- 2022 Sea Level Rise Technical Report
- access to clean water, access to locally grown food, access to healthy food, access to grocery store, access to microgrid, access to sustainable energy
-  Density vs rural/less populated but more sensitive maps
-  Walkable and bike friendly data set.
-   Flood Factor
-  consider adding nuclear waste sites
-  cdc social vulnerability, climate data (NOT THE NRI data) but data from NOAA or the US climate assessment report, specifically flood, heat, drought, and wildfire data.

(links)

-  https://www.epa.gov/sdwa/national-contaminant-occurrence-database-ncod, 
-  https://edg.epa.gov/EPADataCommons/public/OA/SLD/SmartLocationDatabaseV3.zip
-  https://www.nationsreportcard.gov/profiles/districtprofile
-  https://oceanservice.noaa.gov/hazards/sealevelrise/sealevelrise-tech-report.html
-  https://rgk-center.shinyapps.io/A2SI_Explorer/
-  https://www.fema.gov/flood-maps
-  https://www.fema.gov/flood-maps
-  https://www.cdc.gov/nceh/tracking/topics/ClimateChange.htm
-  https://www.atsdr.cdc.gov/placeandhealth/svi/index.html
