### ISSUE TITLE
Tracking an in meeting request from Sharmila - make the RFI link more prominent 

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1360]
**Describe the bug**
The RFI link is small and below the map. This could be improved.

**To Reproduce**

**Expected behavior**
Kameron to think of something.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by katherinedm-usds** [comment]
Adding note for @KameronKerger to think about how a link to EO 140008 with also at least use of "Justice40" could also go into the footer, which is one path to use being able to use "Justice40" and "140008" as SEO keywords
