### ISSUE TITLE
Add link to the existing FAQ to the about page

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1369]
## Describe the task
Add link to the existing FAQ to the about page in the screening tool section

## Acceptance Criteria

- [ ] Write copy for link
- [ ] Add link
- [ ] Test link
- [ ] Deploy

## Additional context

* Is this something we want to do "now" @BethMattern?

**Comment by BethMattern** [comment]
@KameronKerger I think we should do this soon. CEQ will probably be referencing the FAQs in the upcoming public sessions, and they will plan on enhancing the FAQs if there are questions asked in the sessions that would be good additions to the document. I'm totally fine if this goes in next sprint.
