### ISSUE TITLE
Design for additional resources that need to be made available on CEJST

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1384]
Determine design for making additional resources available and/or more prominent on CEJST, including:
FAQs
RFI link
Others?

**Comment by BethMattern** [comment]
@KameronKerger since you are basically done with this, should this be closed as part of this sprint?

**Comment by KameronKerger** [comment]
I will try to remember to mark this done once I've added the designs to the development tickets @BethMattern
