### ISSUE TITLE
Public Engagement page v2

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#1394]
- [x] Gray out past events (2 points)
- [x] Remove the 'new' graphic and the button
- [ ] Move page to "About"

**Comment by KameronKerger** [comment]
@vim-usds here are some disabled states for the dates that have (or are going to pass). I believe it was the svgs that worked but I can make pngs no bother.
![april_15_off](https://user-images.githubusercontent.com/77702996/158239826-04832f04-2a41-4303-835d-f2a3ff383872.svg)
![march_9_off](https://user-images.githubusercontent.com/77702996/158239827-2d8aa8c6-0630-4604-b4cc-75e403bf2bc4.svg)
![march_10_off](https://user-images.githubusercontent.com/77702996/158239828-5562102d-29f2-4aff-a7b7-d101391970b7.svg)
![march_15_off](https://user-images.githubusercontent.com/77702996/158239830-fb20e4b4-e716-45d9-ad49-b0ae08042f39.svg)
![march_16_off](https://user-images.githubusercontent.com/77702996/158239833-8681819d-d442-4ab2-bf4a-1042d061781a.svg)
![march_22_off](https://user-images.githubusercontent.com/77702996/158239837-b91cef86-5df0-4ccb-82f3-6d2c416e5ba9.svg)

**Comment by BethMattern** [comment]
@KameronKerger do you want to just gray out the past events or do you also want to move them so they aren't at the top?

**Comment by KameronKerger** [comment]
for now I would just gray them and leave them as is. there aren't that many but eventually we should archive them somehow.

**Comment by KameronKerger** [comment]
![Screen Shot 2022-03-18 at 4.09.35 PM.png](https://images.zenhubusercontent.com/60a81149dee122a5d67208e5/97213dbb-d3b6-4368-8dc2-660458945499)
