### ISSUE TITLE
As a data developer, I want to add the New York State draft list of DACs to the comparison tool, so I can understand how they compare against other indices.

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#1408]
**Description**
New York just released its draft definition of DACs with a 120-day comment period, including: 

Documentation: https://climate.ny.gov/DAC-Criteria 
Map: https://climate.ny.gov/Our-Climate-Act/Disadvantaged-Communities-Criteria/Disadvantaged-Communities-Map 
Data download: https://data.ny.gov/Energy-Environment/Draft-Disadvantaged-Communities-DAC-2021/xj7e-q8ja 

Add this to the comparison tool to generate comparison results.

**Comment by emma-nechamkin** [comment]
This is ready to go but currently is in emma-nechamkin/1149-pairwise-comparison-tool.
