### ISSUE TITLE
Should the census tract feedback button be yellow? discuss.

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1413]
**Describe the bug**
A couple of times the census tract feedback button has been not highlighted during the public engagement demos. I'm asking if we can get usage numbers but in the mean time, and somewhat regardless, do we think it would be more prominent if it was yellow?

**To Reproduce**
1. Go to 'Explore the tool'
2. Click on 'a census tract'
3. See blue button

**Expected behavior**
Maybe the button is yellow? 

**Screenshots**
Blue current, more orangey yellow USWDS accent button in warm, more yellow yellow button would be more similar to what we are using for the beta pill and the new tag on the public engagement link 
<img width="281" alt="Screen Shot 2022-03-15 at 10 47 57 AM" src="https://user-images.githubusercontent.com/77702996/158441065-dd782d55-5d60-4ddf-9f05-5cfa101a604b.png">
<img width="279" alt="Screen Shot 2022-03-15 at 10 48 07 AM" src="https://user-images.githubusercontent.com/77702996/158441070-c41f28f5-2ad1-4a9a-a642-b51d9cbc5829.png">
<img width="281" alt="Screen Shot 2022-03-15 at 10 48 17 AM" src="https://user-images.githubusercontent.com/77702996/158441073-e7f8e41a-9271-46f3-8693-8a0293b43aaf.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger - there's a part of me that agrees. Maybe all CTAs (call to actions) should be yellow? Also wondering if there's any correlation of yellow buttons to the beta pill? If not, we may want to change the color of the beta pill to reflect something else? Just some ideas

**Comment by katherinedm-usds** [comment]
Yellow send feedback button would be great IMO @KameronKerger
