### ISSUE TITLE
Move About in the navigation & make Explore the Tool the default page

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1425]

**Comment by BethMattern** [comment]
New order will be Explore the Tool -> Methodology & Data -> About -> Contact

**Comment by KameronKerger** [comment]
![Screen Shot 2022-03-18 at 4.08.22 PM.png](https://images.zenhubusercontent.com/60a81149dee122a5d67208e5/23a2bc52-71be-43d9-9636-031a0cb24f24)
Top nav goes
Explore the tool (landing page)
Methodology & data >
About >
Contact
