### ISSUE TITLE
Add new sub pages under "Methodology and Data"

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1426]

**Comment by KameronKerger** [comment]
![Screen Shot 2022-03-18 at 4.03.49 PM.png](https://images.zenhubusercontent.com/60a81149dee122a5d67208e5/0b632295-f51b-47c4-8b4d-0185e2dd5969)
Methodology & data
Downloads (internal - methodology/downloads)
Technical support documentation (internal - methodology/technical-support)
Frequently asked questions (internal - methodology/faqs or external https://www.whitehouse.gov/wp-content/uploads/2022/02/CEQ-CEJST-QandA.pdf TBD)

**Comment by BethMattern** [comment]
Do not implement Previous Versions page yet.
