### ISSUE TITLE
As an EVCM, I want to be able to download any published version of the prioritized list. 

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#143]
**Description**

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**
https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/131
https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/142

**Tasks**

**Definition of "Done"**

**Comment by katherinedm-usds** [comment]
Moving to product backlog because we'll have to ensure that the site design on July 27th and list download interaction can be expanded potentially in August and beyond to include the ability to download multiple versions of the .csv

**Comment by BethMattern** [comment]
@katherinedm-usds is this story needed or is everything covered in #111?

**Comment by katherinedm-usds** [comment]
@BethMattern This is not needed for July 27th, but presumably we'll need to support multiple versions of the community list if there will be any change to scoring methodology post July 27th. Can go to icebox but just want to make sure folks are aware of the hopefully likely scenario of there being multiple versions of the CBG list
