### ISSUE TITLE
There is still random intermittent instances of the UI not being blue when it should be. 

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1430]
**Describe the bug**
I fear this will continue and make the new side panel design more confusing. 

**To Reproduce**
1. Go to '[...](https://d2zjid6n5ja2pt.cloudfront.net/en/cejst#13.45/27.52882/-97.88037)'
2. Click on 'Climate change"
3. Scroll down to 'Pop loss - is 94, is not blue'

**Expected behavior**
Can Emma spend some time thinking about why this is happening and how to fix it? 

**Screenshots**
<img width="243" alt="Screen Shot 2022-03-16 at 3 03 35 PM" src="https://user-images.githubusercontent.com/77702996/158699145-fc466113-9f70-43f0-8437-a03f8e255516.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@kameron - just validated that this may no longer be happening? Does it still happen for you?

**Comment by KameronKerger** [comment]
I don't think I've seen it since the update was made to get the flags via some Emma sorcery @vim-usds
