### ISSUE TITLE
Add Public Engagement Calendar and RFI to the footer

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1436]

**Comment by KameronKerger** [comment]
![Screen Shot 2022-03-18 at 3.06.59 PM.png](https://images.zenhubusercontent.com/60a81149dee122a5d67208e5/cf79a636-8839-4ed4-935a-32c533b2ae87)

Engagement calendar (about/public-engagement/)
Request for Information (external link - https://www.federalregister.gov/d/2022-03920)
