### ISSUE TITLE
Add RFI to contact page

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1442]
Kameron to add mocks.

**Comment by KameronKerger** [comment]
![Screen Shot 2022-03-18 at 3.05.38 PM.png](https://images.zenhubusercontent.com/60a81149dee122a5d67208e5/2e3db9d8-d9f6-4d88-9244-3f71e58615e1)
Request for information
During the beta period, comments may be submitted on the Climate and Economic Justice Screening Tool via CEQ’s Request for Infomation on available on federalregister.gov (external link).
