### ISSUE TITLE
Spanish improvements for site

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1444]
- [x] Add Spanish translation link: https://www.surveymonkey.com/r/cejst-survey-es
- [ ] "Additional documentation now available" | "Download new technical support..." banner at the top of each page
- [ ] "Public comment period extended" banner is in English
- [ ] on map side panel "At or above at least one threshold"
- [ ] on map side panel "At or above both associated thresholds?"
- [x] on MetodologÍa "Download technical support document" link box
- [ ] on MetodologÍa "UPDATED" labels
- [ ] on MetodologÍa "Last updated: " labels under download links
- [ ] on Contacto "The public comment period for sending feedback..."
- [ ] On Oportunidades de participatión pública once it's up, the link to the slides from the training

**Comment by vim-usds** [comment]
https://www.surveymonkey.com/r/cejst-survey-es

**Comment by katherinedm-usds** [comment]
Hi @esfoobar-usds not sure if the survey link is something you or Tom could update once or soon after the Spanish version is up?
