### ISSUE TITLE
Add Previous Versions page

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1447]
This page will make the download files from previous methodology versions available for download.

There should be 2 download options:
1.  zip file that contains the .xls, .csv, .pdf, tech support document, checksum file
2.  zip file that contains the shapefiles, codebook and checksum file

**Comment by KameronKerger** [comment]
<img width="511" alt="Screen Shot 2022-06-06 at 12 49 44 PM" src="https://user-images.githubusercontent.com/77702996/172236835-c635ef69-8313-4c1f-80ec-5633480b196f.png">

**Comment by esfoobar-usds** [comment]
After a standup conversation with @BethMattern and @KameronKerger, we won't have the checksum as part of the zip files.

**Comment by vim-usds** [comment]
@esfoobar-usds - can you attach the links that are associated with the two buttons (in the mock) please?
