### ISSUE TITLE
As a federal agency program officer (FAPO), I want to see the list of prioritized CBGs so that I can begin planning my programs. (agency user research)

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#145]
**Description**

TO DO:
User research on what info is minimum necessary for FAPOs to use the list as a downloadable CSV.
User research on other formats FAPOs want to see/use this data.

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**

**Comment by katherinedm-usds** [comment]
I think this can be closed because it's covered in other cards - @switzersc-usds what do you think?

**Comment by katherinedm-usds** [comment]
Closing, @KameronKerger has started work on federal program officer research as well as options involving user research with FPO participants that when more solidified should be tracked elsewhere. Until we have FPO input to inform further changing the .csv and Excel spreadsheet formats, we'll go with what's been spec'd.
