### ISSUE TITLE
low income should be "at or above" and not just "above"

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1456]
**Describe the bug**
In all the methodologies the thresholds need to be "at or above" but for low income it just says "above." Emma checked and it is in fact at or above so the methodologies need to be updated for clarity and consistency.

**To Reproduce**
1. Go to 'Methodology & Data'
2. Scroll down to 'any methodology except for training and workforce development'
3. See error

**Expected behavior**
Update all the "above"s to be "at or above"s

**Screenshots**
<img width="395" alt="Screen Shot 2022-03-17 at 12 20 06 PM" src="https://user-images.githubusercontent.com/77702996/158879478-8cb08a51-762e-4910-ba2c-dd9da0c9c916.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger - is this still valid?

**Comment by KameronKerger** [comment]
yes @vim-usds - note this is all the categories not just climate chang
<img width="500" alt="Screen Shot 2022-06-01 at 4 18 48 PM" src="https://user-images.githubusercontent.com/77702996/171517195-79fded7d-2c4a-4f4e-a9c2-9a6878588cc8.png">
e
