### ISSUE TITLE
Reorder poetry list so packages are alphabetically listed

### ISSUE THREAD

**Issue by emma-nechamkin** [usds/justice40-tool#1459]
nit: not your fault but at some point we should sort these dependencies alphabetically so they're easier to find when you look for a specific dependency

_Originally posted by @lucasmbrown-usds in https://github.com/usds/justice40-tool/pull/1400#r829253739_

**Comment by esfoobar-usds** [comment]
I just did that on my last PR for parallel uploads/deletions?

**Comment by esfoobar-usds** [comment]
We are doing this as we add packages
