### ISSUE TITLE
Higher ed data is available for the three territories

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1462]
**Describe the bug**
We should say in the training and workforce development methodology that low higher ed attainment rate is *not available for American Samoa and the Northern Mariana Islands

**To Reproduce**
1. Go to 'Methodology & data'
2. Scroll down to 'Higher ed enrollment rate.'
3. See error

**Expected behavior**
<img width="414" alt="Screen Shot 2022-03-18 at 2 42 13 PM" src="https://user-images.githubusercontent.com/77702996/159086604-e449e290-2787-42b4-9ff4-6a63fad8f4f3.png">

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I will update living copy

**Comment by KameronKerger** [comment]
never mind

**Comment by KameronKerger** [comment]
never mind

**Comment by KameronKerger** [comment]
I change it so now it is valid.

**Comment by BethMattern** [comment]
@KameronKerger will this need to be revisited when we add USVI and Guam?

**Comment by KameronKerger** [comment]
yes @BethMattern

**Comment by vim-usds** [comment]
We will be removing Higher Ed across all

Lower income - but not college students. We measure by those below 200% poverty line

New - whoever is in low income and subtract the college attendance and then rank that %

**Comment by KameronKerger** [comment]
closing and opening a new ticket to figure out how to handle this in the copy now that higher ed is a part of low income.
