### ISSUE TITLE
Further analysis on FEMA data

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1475]
BuildValue might need a similar adjustment to AgriValue.

**Comment by emma-nechamkin** [comment]
A few notes here:

1. We do not have to restrict the percent of tracts identified: Essentially every tract has building value (unlike agricultural value). In fact, only about 50 tracts in the NRI dataset do NOT have building value. 
2. There's not a clear "cutpoint" for building value: at 20th percentile build value as the lower clip, about 9% of low value tracts and about 10% of high value tracts are included. That is 272,485,800 of value, yikes!
3. At a lower clip (3%), there's roughly equal representation between low-value and high-value tracts. This value is about 140M. This seems reasonable to me but it doesn't deal with the underlying issue Kameron identified. 

Another option would be to say, you need to have at least $10,119,090 in value (the 0.25th percentile for build value) to be included. Although this is different than agriculture, it might be a better fix and WOULD address the problem Kameron identified while remaining wealth neutral.

**Comment by emma-nechamkin** [comment]
(this doesn't actually change the identified communities significantly though... pending updates)

**Comment by emma-nechamkin** [comment]
Update: changing the definition of build value here does not appear to be necessary; clipping it will only impact 1 community total. The vast majority of tracts have build value as well, and so a straight 90th percentile is also logically consistent.
