### ISSUE TITLE
As a developer, I want to run MVT creation in AWS so that I don't have to send files to S3 from my local machine. 

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#150]
**Previous Description**
We need to easily spin up and run the code to generate MVT tiles from GeoJSON in the cloud. The output of uncompressed files is around 80k files and in a local environment this could take upward of an entire day to upload to S3 just because of bandwidth. This may eventually be owned/run by the geoplatform folks, but for the time being let's get this containerized and running in lambda with EC2 and we can hand this over to them later (e.g. they could read the relevant Dockerfile from our repo). 

**Updated Description - midway through week 1 of Sprint**
Review and merge in the work from Geoplatform and test locally that serverless CLI is able to package app and push to AWS. 

**Solution**
Set up our AWS resources in geoplatform to run a lambda function that spins up and cleans up the EC2 instance that runs the MVT generation code. 

**Describe alternatives you've considered**

**Links to user research or other resources**
Check out the following diagram. The part to be put into the cloud is the tippecanoe and Create + Send MVT. Check with @esfoobar-usds for which code exactly is the relevant code to be run. 

![mermaid-diagram-20210617100349.svg](https://images.zenhubusercontent.com/60994445b305970bf293d619/68d69204-7e79-4f45-b1a9-e95201733030)

**Tasks**
- [x] Discuss orchestration as dev team

**Definition of "Done"**
- [ ] Uncompressed MVT generation is happening in the cloud

**Comment by ginabeena** [comment]
@switzersc-usds @esfoobar-usds @NatHillardUSDS @TomNUSDS 

How do we want to call this lambda? Do you want it to wake for an event of getting new data in? Or do you want it to run on-demand via Jenkins? Do you want it to happen from your editor?

**Comment by switzersc-usds** [comment]
This should be triggered by new GeoJSON available from ticket #152 eventually. In the short term it could probably happen from a local command?

**Comment by switzersc-usds** [comment]
@switzersc-usds will schedule a followup convo for early next week

**Comment by ginabeena** [comment]
Currently blocked by permission errors, but this is code complete and merged.

**Comment by switzersc-usds** [comment]
Moving this to Closed because the work here is done. We can separate out pushing the artifact and instrumenting the app for serverless, and Gina has confirmed this is working as expected.
