### ISSUE TITLE
Add the recorded version of the CEJST training to the PEC

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1500]
**Is your feature request related to a problem? Please describe.**
Add the recorded version of the CEJST training to the PEC

**Describe the solution you'd like**
A new tab should open and go to this page on YouTube.

**Describe alternatives you've considered**

**Additional context**
Screenshot
<img width="513" alt="Screen Shot 2022-03-28 at 9 42 42 AM" src="https://user-images.githubusercontent.com/77702996/160446845-6860dfa2-dd42-4a3d-96cd-48269f5d77e5.png">

**Comment by vim-usds** [comment]
@Kameron - would it possible to expand on the reasoning behind when are buttons are yellow vs blue? I've heard about primary and secondary colors, however not sure if it's applicable here or if its something else entirely? TY

**Comment by KameronKerger** [comment]
@vim-usds no rationale really. I suppose they could all be yellow? I just grabbed the default card component which has the blue buttons.

**Comment by vim-usds** [comment]
@KameronKerger and/or @Beth - how do I find the link to the youtube video?

**Comment by KameronKerger** [comment]
sorry I could have swore I put it in the ticket @vim-usds 
https://www.youtube.com/watch?v=QwHWcXbhw28

**Comment by vim-usds** [comment]
@KameronKerger - can this be an 8:4 column layout?

Also, can the box be blue as the default summary box or is the white background required?

**Comment by KameronKerger** [comment]
I'd prefer the white background @vim-usds - I actually think the dark blue makes the box less noticeable.

**Comment by vim-usds** [comment]
@KameronKerger - is there a link to that video in Spanish?

**Comment by KameronKerger** [comment]
@vim-usds no, they just did ASL no translation.

**Comment by vim-usds** [comment]
@KameronKerger how does this look?
![Screen Shot 2022-03-31 at 5 34 37 PM](https://user-images.githubusercontent.com/86254807/161172111-1f373def-4ea0-48e4-bfb6-bd1ef6eb2fdd.png)

**Comment by vim-usds** [comment]
@KameronKerger - trying out the baby blue that comes default in the SummaryBox component from USWDS. Also the yellow button. If either of these don't bring joy, please let me know. We can easily change it!

**Comment by vim-usds** [comment]
The thinking about the yellow buttons is to have consistency on what means "action" for the user. Maybe if every handle that the user can interact with is yellow, it might make it easier for them to use that handle? I'm also speculating that multiple colors for buttons is even an issue. 🤷‍♂️

**Comment by vim-usds** [comment]
@KameronKerger - breaking new from a11y:

![Screen Shot 2022-03-31 at 6 53 12 PM](https://user-images.githubusercontent.com/86254807/161179514-b6d62265-aa67-4a6d-8f2e-64c2c783fc35.png)
