### ISSUE TITLE
Add demographics / additional data to census tract sidebar on map

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1516]
We are going to move forward with adding race/ethnicity and age to the UI. Reports are the ultimate solution for additional demographics.

**Comment by KameronKerger** [comment]
@vim-usds updated the proposed demographics design after the conversation this morning. when we previously discussed there was some issue with using the dropdown style arrow (from the header) and not the accordion. we feel it is pretty important for it to have a distinct look and feel. would you be able to lay out some of the issues with using this different style so we can better assess what we need to do to move forward with this implementation. thank you!
<img width="616" alt="Screen Shot 2022-07-08 at 1 16 35 PM" src="https://user-images.githubusercontent.com/77702996/178064344-cb5c9c79-c653-4fba-82b1-644c76cb6b21.png">

**Comment by vim-usds** [comment]
@Kameron - yes will do!

**Comment by KameronKerger** [comment]
<img width="943" alt="Screen Shot 2022-07-18 at 9 05 50 AM" src="https://user-images.githubusercontent.com/77702996/179554218-8510adff-8059-4314-acf9-e17789d05e84.png">

**Comment by vim-usds** [comment]
@esfoobar-usds and/or @emma-nechamkin, 

Some questions:
1. Do we know all the race and age fields that will available to us?
2. Do we know how this data will be baked into tiles? Meaning are we using the usual _short-name_ pattern ? 
3. Let's assume yes to the usual short-name pattern, I'm assuming we will define some short-name for each demographic and it will have a corresponding decimal (float) value? 

Currently the tiles have data like this

```
AF_PFS: 0.73
ALI: false
A_ET: false
CA: 0.05
CA_LT20: true
CC: 1
CF: "Bulloch County"
DB_ET: false
DF_PFS: 0.64
DLI: false
DPMLI: false
 :
 :
 
 ```
 
 Would the new demographics data be like this?
 
 ```
RACE_WHITE: 0.80
RACE_ASIAN: 0.30
RACE_NATIVE: 0.01
RACE_HISP: 0.40
AGE_LT_10: .20
AGE_10_64: .50
AGE_GT_65: .30
```

**Comment by emma-nechamkin** [comment]
@vim-usds these are all great questions! I haven't thought much about this (@esfoobar-usds did you have a plan?) and am happy to defer to you here in terms of what you want to name things (and I think we need to make a backend ticket for this). 

As for what demographics we can show -- we have this data. Those are the census terms as well.

**Comment by vim-usds** [comment]
@emma-nechamkin and @esfoobar-usds :

Feel free to add a BE ticket that makes sense to you.

Great!  Updated the proposed names in the spreadsheet! The shared spreadsheet is called "Indicators for UI and Export" and the sheet is called "Side panel BE SIgnals".

![Screen Shot 2022-07-28 at 4 43 37 PM](https://user-images.githubusercontent.com/86254807/181655203-eeaa1318-4ee4-473c-b4f0-f270c36bcd62.png)

Everything in green will be added in 1.0 and everything in red needs to be removed for 1.0. We can totally change these names anytime as well. I agree that this spreadsheet should be the single source of truth. 


Added a few columns:
- Merged to BE release branch?
- BE staging link available?
- Validated by FE?
- Merged to FE release branch?

These can be marked yes as we move along each indicator! I feel good when I have a spreadsheet tracking stuff!

**Comment by esfoobar-usds** [comment]
Looks overall good. My only question is: are we including these on the side effects? @lucasmbrown-usds @KameronKerger

**Comment by snowcoding** [comment]
@esfoobar-usds - sorry I don't think I follow what you mean by "side effects"?

**Comment by esfoobar-usds** [comment]
Excel + CSV downloadable assets is what I call side effects, sorry!

**Comment by esfoobar-usds** [comment]
Per our convo in standup, we will be treating these indicators as "informational" and thus separate from score ETL files, using something similar to `etl_score_post`, which would take the `usa.json` and tack on the demographics indicators to that file, prior to tile baking. After that, the information will be on the tiles baked in, so @vim-usds can use them like any other indicator.

Furthermore, @KameronKerger suggested we use a different color treatment for these indicators on the Excel file (a different font and background color, to denote it's not part of the score).

**Comment by BethMattern** [comment]
Assigning this to @lucasmbrown-usds who will be doing the backend work
