### ISSUE TITLE
HOTFIX - Update wording about the WHEJAC meetings on the public engagement page

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1520]
The wording under both of the Pubic WHEJAC meetings needs to be changed to say:

The White House Environmental Justice Advisory Council is also soliciting feedback on the beta version of the Climate and Economic Justice Screening Tool at its public meeting. The link above has additional details.

**Comment by KameronKerger** [comment]
QA passed @vim-usds
