### ISSUE TITLE
Analyze impact of adding transportation cost burden and transportation access burden data to methodology

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1539]
The transportation cost burden data is from HUD Location Affordability Index. The cost for transit and non-transit users was combined with monetized commute time)

The transportation access burden is an indicator that DOT created that uses the following data indicators:
No personal vehicle from CDC Social Vulnerability Index
Average commute time to work from Census ACS 
Walkability from EPA Smart Location Map

I'm waiting to hear back from DOT on exactly how they calculate this.

DOT recommendation is to revise the "Clean transit" formula to be:
IF 
at or above the 90th percentile for diesel particulate matter exposure OR
at or above the 90th percentile or traffic proximity and volume OR
at or above the 50th percentile for transportation cost burden OR
at or above the 50th percentile for transportation access burden

**Comment by BethMattern** [comment]
@emma-nechamkin I think we'd like to only add transportation access burden, but I didn't want to make a new ticket.

**Comment by emma-nechamkin** [comment]
awaiting data
