### ISSUE TITLE
As a developer, I want to enhance the score formula to incorporate newly added datasets, so that we can continue to get feedback on the score and refine the formula.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#155]
**Description**
The cumulative impact score formula needs to be enhanced to add the additional data sets (all linked to the milestone "Ingest new data sets"

This formula  follows the CalEnviroScreen methodology:

1. Average all the normalized national percentile values in each bucket (Exposure, Environmental, Sensitive Populations, and Socioeconomic) into a single score for each bucket.
2. Combine the score from the two Exposure and Environmental Effects buckets into a single score called "Pollution Burden". The math for this score is: (1.0 * Exposures Score + 0.5 * Environment Effects score) / 1.5.
3. Average the score from the two Sensitive populations and Socioeconomic factors buckets into a single score called "Population Characteristics".
4. Multiply the "Pollution Burden" score and the "Population Characteristics" together to produce the cumulative impact score.

Handling missing values:
- If a census block group is missing values on one of the indicators in a bucket, use the remaining indicators for the purposes of averaging.
- If a census block group is missing values on all of the indicators in a bucket, the census block group gets a null score.

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**
- [ ] outputs of this new score formula can be viewed in some way by USDS team and CEQ (export file, other)

**Comment by switzersc-usds** [comment]
@lucasmbrown-usds will take the lead on this and once there is a draft, he will sync with @esfoobar-usds for an hour or so to review and discuss next steps.
