### ISSUE TITLE
Implement HOLC indicator once category decision is made

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1553]

**Comment by emma-nechamkin** [comment]
Right now, I've implemented this from the sources. not in a category yet.

**Comment by emma-nechamkin** [comment]
Note -- waiting on NCRC team to ok posting data to s3

**Comment by emma-nechamkin** [comment]
Citation is: Meier, Helen C.S., University of Michigan Institute for Social Research, Mitchell, Bruce Coffyn., National Community Reinvestment Coalition. Approval 5/2.
