### ISSUE TITLE
As a developer, I want to create a population-weighted formula for determining a disadvantaged community, so that the thresholds include X% of population rather than X% of census block groups.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#156]
**Description**
The system needs to have logic for identifying disadvantaged communities.  This logic using population-weighting rather than just the top 25% of CBGs, which may not represent the top 25% of population.

Formula:
1. Calculate the total population across all census block groups.
2. Calculate 25% of the total population across all census block groups.
3. Rank the census block groups in descending order based on their score.
4. Calculate the cumulative sum of the population in the census block groups.
5. For all census block groups in the top 25% of the total population with the highest scores, mark these census block groups as "disadvantaged communities".
6. For all census block groups in the top 25.1% to 40% of the total population with the highest scores, mark these census block groups as "on the cusp of disadvantaged communities"
7. For the purposes of iterating on this score formula, it should be easy to change these thresholds (mentioned in #5 and #6 above) so that we could change the thresholds and regenerate the results.

Note that this work is dependent on having the census block group population data which is in card #158

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**
- [ ] other USDS team members and CEQ can see the results of this designation in some way (on the map is ideal, in a data export of some kind is OK)
- [ ] we can change the threshold % ranges for determining disadvantages and cusp communities and regenerate the data

**Comment by switzersc-usds** [comment]
This will be tackled likely as part of the PR that tackles #155

**Comment by switzersc-usds** [comment]
@lucasmbrown-usds can you clarify in the card how this relates to the other score-related cards?

**Comment by BethMattern** [comment]
@switzersc-usds I created this because I thought there would need to be a place where we specifically detail the threshold for being considered prioritized or not, and to explain that we might have to play around with the % thresholds before we land on a true definition of what makes a census block group in or out. And finally, to call out that this data has to be available to be seen in the UI of the map but also exported as part of the list. 

If that is properly described elsewhere then we can certainly call this a duplicate.
