### ISSUE TITLE
Extended comment period

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1566]
**Describe the bug**
If the comment period is extended, add an alert to the CEJST.

**To Reproduce**
1. Go to 'any page'
2. See no extended alert

**Expected behavior**
If the comment period is extended, add an alert to the CEJST

**Screenshots**
![public_comment](https://user-images.githubusercontent.com/77702996/163605715-7a8ac889-0ecd-4104-8ed6-42bcb64598e5.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KameronKerger** [comment]
fixed a typo
![public_comment](https://user-images.githubusercontent.com/77702996/165128083-1d1b769e-605e-49e1-966c-f8c0cc124ad4.png)

**Comment by TomNUSDS** [comment]
@KameronKerger is it May 11th or May 25th?

**Comment by TomNUSDS** [comment]
Sending feedback link: `https://www.federalregister.gov/documents/2022/04/25/2022-08774/climate-and-economic-justice-screening-tool-beta-version`
