### ISSUE TITLE
Changes for new documentation

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1567]
**Describe the bug**
Once the new documentation is added, follow the changes protocol outlined below.

**To Reproduce**
1. Go to 'any page'
2. See no banner

1. Go to 'methodology & data
2. See old download files content

1. Go to 'explore the tool / map'
2. See under the map 

**Expected behavior**
The download files box on the methodology and data page needs to be updated, the info alert needs to be updated and the string under the map needs to be updated as follows:
Download the current list of communities, datasets used, and information about how to use the list (ZIP file will contain one .xlsx, one .csv, and one .pdf (NEW tag) with a size of ##MB unzipped). Last updated: ##/##/##.

NOTE: there is a separate issue that has additional updates to the string under the map. This assumes these haven't been made yet.

NOTE: the dates and the file sizes need to be updated to be accurate

**Screenshots**
![Files_download](https://user-images.githubusercontent.com/77702996/163606216-8f660936-43f4-4ac6-9ab2-440da6e62599.png)
![New_documentation](https://user-images.githubusercontent.com/77702996/163606218-583eab5d-cc25-4cd2-b30f-fe62a751df00.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KameronKerger** [comment]
[Draft_Communities_List_V23.pdf](https://github.com/usds/justice40-tool/files/8497901/Draft_Communities_List_V23.pdf)

**Comment by KameronKerger** [comment]
fixing a spelling boo boo on the banner
![New_documentation](https://user-images.githubusercontent.com/77702996/164519344-d8287857-105c-421c-b619-e72c79469d8e.png)

**Comment by katherinedm-usds** [comment]
@esfoobar-usds would it be ok to ask Tom to help with adding this "Additional documentation now available..." banner (which goes under the "Climate and Economic Justice Screening Tool" logo and top nav, the previous banners had expired)
<img width="586" alt="image" src="https://user-images.githubusercontent.com/74208851/164521089-62a34011-b994-405a-bad4-cecbb29a7675.png">

And if possible, could he make the "Download technical support document" button the same width as the other download buttons? It's ok to keep the label "document" as opposed to "documentation" as shown in the design @KameronKerger had included in this ticket.

<img width="163" alt="image" src="https://user-images.githubusercontent.com/74208851/164521235-87cb2ac5-76da-4231-8a74-3c4c86c6af93.png">

**Comment by TomNUSDS** [comment]
Two things:

1. Embedding the "New" inline in the text is tricky in the code. This is not a gif/image, it's markup (with an existing translation entry that's hard to recursively reference from the paragraph text that's being translated). 
Just a gentle push-back to see if it's really needed inline in the body of text AND as a button callout?

2. Check the colors for the gray? See [USWDS colors for reference](https://designsystem.digital.gov/utilities/color/). (NOTE: the Text "New" and "Update" are actually BLUE in the code:
```scss
    @include u-text("blue-70v");
    @include u-bg("yellow-20v");
```

<img width="279" alt="image" src="https://user-images.githubusercontent.com/74203452/165161677-675c19c1-e3ba-4256-82c0-ce233199093b.png">

This screenshot is currently using:
```scss
    @include u-text("blue-70v");
    @include u-bg("gray-10");
```

**Comment by KameronKerger** [comment]
ok with not adding the NEW inline tag. 
do we like this or no? 
<img width="336" alt="Screen Shot 2022-04-25 at 12 48 02 PM" src="https://user-images.githubusercontent.com/77702996/165163292-a2662825-ee1d-4eba-bb19-d0a80b39ebda.png">
ok with the updates being in the more blue color.

**Comment by TomNUSDS** [comment]
@KameronKerger Adding the new in the middle was easier than I thought, but thanks for being flexible!

What do you think?
<img width="376" alt="image" src="https://user-images.githubusercontent.com/74203452/165355158-2a3104d0-0da7-4936-84d1-7e105e635edc.png">

**Comment by KameronKerger** [comment]
@TomNUSDS looks good to me. if you want to just left align them all that is fine with me also. I think the date for the first two will be today's after @esfoobar-usds finishes the build.

**Comment by esfoobar-usds** [comment]
Build is done, @TomNUSDS please make the first two dates today's date

**Comment by KameronKerger** [comment]
@TomNUSDS 
Download the data sources used in the CEJST (.csv, .xlxs, .pdf that describes how to use the list, and a codebook, 53MB unzipped), the shapefile, along with a codebook (.zip, 742MB unzipped) or the technical support document (.pdf, 2.5MB unzipped).
