### ISSUE TITLE
"Could not load data" error upon opening shapefile in ArcMAP 

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#1570]
**Describe the bug**
3 support emails representing 4 people have reported the error after downloading and attempting to open https://static-data-screeningtool.geoplatform.gov/data-pipeline/data/score/shapefile/usa.zip in ArcMAP (desktop ArcGIS)

> Loading table data
> 
> Could not load data from the data source. If you can correct the problem, press the refresh button to reload data. Possible problems can include bad network connection, invalid field, etc.
> A column was specified that does not exist.
> A column was specified that does not exist.

![image (1).png](https://images.zenhubusercontent.com/609ab603576fa56647137b9e/744b66a7-db66-4a9c-99df-ff4b7d0b2c23)

**Expected behavior**
Shapefile opens, this does seem to work correctly on ArcGIS online

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - ArcMAP 10.8.1 and 10.8.2

**Comment by JimKuiper** [comment]
The solution to this is to rename (or delete) the "FPL200S.1" field. The "." character field is not supported by the shapefile format (actually the dBase format). The only special character allowed in field names is "_".
