### ISSUE TITLE
add link to download TSD

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#1571]
TSD = Tech Support Document

**Comment by katherinedm-usds** [comment]
@KameronKerger to confirm/finalize when she's back but in the meantime, for prep for final TSD, @esfoobar-usds to use a placeholder file and plan to make available on Methodology & data with direct link to download the unzipped file, styled similar to shapefile link, but with "Download technical support document" label.

![image.png](https://images.zenhubusercontent.com/609ab603576fa56647137b9e/81782e98-fefe-4afd-b4e0-d69b66c7f97f)

**Comment by TomNUSDS** [comment]
@esfoobar-usds Need the link URI to use.

**Comment by esfoobar-usds** [comment]
Use this one for now for both English and Spanish: https://justice40-data.s3.amazonaws.com/data-pipeline/data/score/downloadable/communities-2022-03-30-0033GMT.xlsx

**Comment by TomNUSDS** [comment]
@KameronKerger @katherinedm-usds 
"Download technical support document" is a lot of text for this button. Does it look ok?

<img width="791" alt="image" src="https://user-images.githubusercontent.com/74203452/163874099-f82680f7-b5c0-4f33-a5ac-a7749268151c.png">

**Comment by TomNUSDS** [comment]
Also, notice the text above the buttons?
Does this need tweaking?

```
Download the data sources used in the CEJST (.csv and .xlsx, 52MB unzipped) or the shapefile, along with a codebook (.zip, 742MB unzipped).
```

The current TSD (`.xlsx` type) looks to be 24.9MB (edited)

**Comment by esfoobar-usds** [comment]
That's a temporary one, we haven't received the real one yet
