### ISSUE TITLE
Minor copy edits to site

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1572]
All edits have been made by Beth Mattern in the Living copy of J40 document. They are also outlined in the attached.[https://app.zenhub.com/files/358242767/57235fe6-37d2-4a51-b73e-aaf439288c75/download](https://app.zenhub.com/files/358242767/57235fe6-37d2-4a51-b73e-aaf439288c75/download)

**Comment by TomNUSDS** [comment]
Checklist:

- [ ] 1
<img width="433" alt="image" src="https://user-images.githubusercontent.com/74203452/163860845-fbc16512-e272-4071-85ea-3d43b9e37716.png">

- [ ] 2
<img width="439" alt="image" src="https://user-images.githubusercontent.com/74203452/163860909-20a2b88f-431c-4c1c-81be-5a2545ce474b.png">

- [ ] 3
<img width="327" alt="image" src="https://user-images.githubusercontent.com/74203452/163860957-d3690402-0948-45e3-bc21-5779daa65121.png">

- [ ] 4
<img width="425" alt="image" src="https://user-images.githubusercontent.com/74203452/163861099-d49289d4-2508-48b1-8d78-3e3e74a52a3a.png">

- [ ] 5
<img width="436" alt="image" src="https://user-images.githubusercontent.com/74203452/163861137-dcdf7ae2-bd10-40d1-84d2-c610d2fecc71.png">

- [ ] 6
<img width="434" alt="image" src="https://user-images.githubusercontent.com/74203452/163861323-673f0221-4863-4381-acf1-3c7782e5fdd0.png">

- [ ] 7
<img width="438" alt="image" src="https://user-images.githubusercontent.com/74203452/163861348-865eb1b4-8e4d-4b9f-9a6f-d3084ec3bb3a.png">

- [ ] 8
<img width="395" alt="image" src="https://user-images.githubusercontent.com/74203452/163861370-2cef8ee8-489d-48c9-961e-267d66bbdac6.png">

- [ ] 9
<img width="431" alt="image" src="https://user-images.githubusercontent.com/74203452/163861397-6e774b3e-8875-424c-a5ab-fac3dd11f7f1.png">

**Comment by TomNUSDS** [comment]
@BethMattern item 7 above has multiple occurrences of "agriculture value". Should all of them be changed in that block of text?

<img width="820" alt="image" src="https://user-images.githubusercontent.com/74203452/163863181-839b540b-09ee-4a99-bc22-69366bc14a38.png">
