### ISSUE TITLE
Modify RFI language to indicate that the comment period has been extended

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1583]
**Describe the bug**
Modify the RFI language on the Contact page to indicate that the comment period has been extended.
During the beta period, comments may be submitted on the Climate and Economic Justice Screening Tool via CEQ's Request for Information available on [federalregister.gov](http://federalregister.gov/). The comment period has been [extended to May 25](https://www.federalregister.gov/documents/2022/04/25/2022-08774/climate-and-economic-justice-screening-tool-beta-version).

**To Reproduce**
1. Go to 'Contact'
2. See error

**Expected behavior**
see above 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KameronKerger** [comment]
<img width="1182" alt="update_contact" src="https://user-images.githubusercontent.com/77702996/165147181-6e3b2a60-8d2d-4e64-8ec6-4bdf9184e5c9.png">

**Comment by TomNUSDS** [comment]
<img width="788" alt="image" src="https://user-images.githubusercontent.com/74203452/165151728-b7f96b87-4c27-4e39-8870-ab3be7ae3d1e.png">
