### ISSUE TITLE
[SPIKE] Visualize tribal boundaries on the map - research options

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1604]
We want to visualize the tribal boundaries on our map, ideally as a separate layer.

The boundaries aren't always inclusive of tract boundaries.

Dev should figure out the options so the team can decide the best implementation.

**Comment by emma-nechamkin** [comment]
We have figured out how to do this

## Backend 

1. Pull the tribal boundaries down from https://www2.census.gov/geo/tiger/TIGER2021/AIANNH/tl_2021_us_aiannh.zip
2. Create tiles: `ogr2ogr`, then tilefy using `tippecanoe` (see `generate_map_tiles`)
3. Post tiles to s3 in a new directory: `data/tribal/tiles`

## Frontend
1. Create a layer pointing to new directory (defined above)
2. Add the layer to the map 

## TODO
1. Emma to confirm on census that shapefile uses BAS data
2. Vim to check if there's a way to avoid using the pipeline and read the shapefile directly

**Comment by vim-usds** [comment]
Feedback from today's discussion hour

Goal - should be able to quickly see how much of a tribal land overlaps with our DACs.

1. Add borders
2. Look into labels
