### ISSUE TITLE
Column headers need updating

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1607]
**Describe the bug**
A few outstanding issues with the column headers. Assumption is that they are the same in the .csv and the .xlsx. These may all be fixable via the YAML file?
- [x] higher ed, included with every boolean needs to be changed from "and has a low percent of higher ed students?" to "a high percent of residents that are not higher ed students?"
- [x] Proximity to NPL sites (percentile) should be Proximity to NPL (Superfund) sites (percentile)
- [x] Proximity to NPL sites should be Proximity to NPL (Superfund) sites
- [x] Percent of individuals < 100% Federal Poverty Line needs to move one column to the left
- [x] ~All of the island data is missing, it is just the booleans~ -- created #1617 

**To Reproduce**
1. Go to '.xlxs or .csv'
2. See errors

**Expected behavior**
See above

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by esfoobar-usds** [comment]
@KameronKerger On task #4 if I move that column to the left, the column order looks weird to me: it would be 200%, 100%, 100%, 200%. Is this intended?

<img width="688" alt="image" src="https://user-images.githubusercontent.com/83969469/166722521-d111504d-8b87-4c85-9e47-8269cd8cdbe4.png">
