### ISSUE TITLE
Backend tribal work

### ISSUE THREAD

**Issue by emma-nechamkin** [usds/justice40-tool#1609]
1. Pull the tribal boundaries down from https://www2.census.gov/geo/tiger/TIGER2021/AIANNH/tl_2021_us_aiannh.zip
2. Create tiles: `ogr2ogr`, then tilefy using `tippecanoe` (see `generate_map_tiles`)
3. Post tiles to s3 in a new directory: `data/tribal/tiles`

## TODO
1. Confirm on census that shapefile uses BAS data

_Originally posted by @emma-nechamkin in https://github.com/usds/justice40-tool/issues/1604#issuecomment-1115334305_

**Comment by emma-nechamkin** [comment]
```You can tell the customer that the Boundary and Annexation Survey (BAS) is a tool that we use to collect data about state, county, city, and tribal boundaries. We then integrate that data into our database. Our TIGER/line shapefiles are created from our database and use the BAS data that have been made consistent with the rest of our data.```

**Comment by emma-nechamkin** [comment]
Jorge meeting: 
- `bas` with shapefile, geojson, and tile files

**Comment by esfoobar-usds** [comment]
Small nit: inside `bas` we would have subfolders:
- `shapefile`
- `geojson`
- `tiles`

**Comment by emma-nechamkin** [comment]
ty @esfoobar-usds 

@vim-usds may be able to pull shapefiles into front-end, making this superfluous.

**Comment by BethMattern** [comment]
Closing this because we've changed to a different data source.
