### ISSUE TITLE
Add two additional public listening sessions to the public engagement calendar on the CEJST and change the updated indicator to yellow

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1615]
**Is your feature request related to a problem? Please describe.**
There are now two additional public listening sessions available.

May 10, 2022 at 4 PM EST (https://pitc.zoomgov.com/webinar/register/WN_dt0xRNioR8SugY2hrDk1JA)
May 19, 2022 at 4 PM PST (https://pitc.zoomgov.com/webinar/register/WN_1PR73vLDQpq1zoAWkhKB5g)

No end time was given. Previously we've put them for an hour but the actually time varies so just put the start time

No descriptions were given so probably just use this
CEQ is hosting public listening sessions to seek input and feedback on the beta version of the tool, including on the datasets it includes and the methodology it uses. This feedback is critical to the development and enhancement of the tool. This feedback will help CEQ update and refine the tool to ensure that it reflects the environmental, climate and other challenges that communities are experiencing.

We still don't have a point of contact for these meetings.

Change Updated in this
<img width="209" alt="Screen Shot 2022-05-03 at 11 27 07 AM" src="https://user-images.githubusercontent.com/77702996/166518603-d5c43d09-27a8-4e16-92ee-b6d9e6ebe1a2.png">
to yellow background

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger - would it be possible to get the SVGs for these two dates? For each date a blue and grey one would be ideal, for active and expired respectfully. TY!

**Comment by KameronKerger** [comment]
@vim-usds here you go
<img width="80" alt="may_10_off@2x" src="https://user-images.githubusercontent.com/77702996/167460484-9ad0fd81-ea98-4fbf-b383-9f6f687a7a95.png">
<img width="80" alt="may_10@2x" src="https://user-images.githubusercontent.com/77702996/167460485-0e6dd0bb-4bb5-4b78-b8e8-4029c52d3259.png">
<img width="80" alt="may_19_off@2x" src="https://user-images.githubusercontent.com/77702996/167460487-33e0ad5b-304d-43e5-8004-fc60ef2566ae.png">
<img width="80" alt="may_19@2x" src="https://user-images.githubusercontent.com/77702996/167460488-f50215e5-1029-492a-9068-1212f0c73489.png">
