### ISSUE TITLE
Include all available indictors for Puerto Rico from existing data sources

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1621]
# Purpose
- From EJScreen: proximity to superfund sites, proximity to RMP sites, traffic proximity and volume, and diesel particulate matter exposure.
- From DOE LEAD data set: energy cost burden
- From HUD:  Housing cost burden 

# Tasks
- [ ] Frontend work to add the 3rd use case
- [x] Data work to add data

**Comment by switzersc-usds** [comment]
@emma-nechamkin Can you confirm whether the data part of this is already done in the narwhal branch? Our meeting notes suggest it is.

**Comment by emma-nechamkin** [comment]
Yes, I have confirmed that for FIPS code 72, we have percentiles for EJScreen, Housing Burden, and Energy Burden. These are already also percentiles.

**Comment by emma-nechamkin** [comment]
There is an outstanding change -- the "Experience" for PR has to be updated (and the threshold count variable)

**Comment by emma-nechamkin** [comment]
https://github.com/usds/justice40-tool/blob/main/data/data-pipeline/data_pipeline/etl/score/constants.py#L123

**Comment by switzersc-usds** [comment]
6 more thresholds, so 10 visible ones

**Comment by switzersc-usds** [comment]
Change that line 123 to 10

**Comment by emma-nechamkin** [comment]
- sustainable housing: housing cost burden
- clean energy: both
- legacy pollution: all

**Comment by vim-usds** [comment]
Thank you @emma-nechamkin 

ideally categories should only show these indicators, if they do show up in the categories qualify them as 
- "NOT AVAILABLE IN Puerto Rico"
