### ISSUE TITLE
Update the public engagement calendar to more readily support previous events

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1623]
**Is your feature request related to a problem? Please describe.**
We have passed the "line of discovery" WRT the public engagement calendar meaning that we have two many old / past events before the new ones. We need to update the design to have more of a recency bias.

**Describe the solution you'd like**
Kameron to propose.

**Describe alternatives you've considered**
The current way is no longer working.

**Additional context**
CEQ requested that the previous events be available in some way.

**Comment by BethMattern** [comment]
We decided we would change the sort order for now and look at implementing a more robust design in the future.
