### ISSUE TITLE
Understand changes in new EJScreen data before implementing

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1635]
We have questions for Tai

**Comment by BethMattern** [comment]
@lucasmbrown-usds make sure you know @emma-nechamkin's questions.

**Comment by lucasmbrown-usds** [comment]
Details are left at #1262

**Comment by BethMattern** [comment]
Sent email to Tai at EPA so he can route the questions to the appropriate people. In the meantime we will move forward with updating the EJScreen data in the CEJST for 1.0
