### ISSUE TITLE
Update survey link and WH.gov link on Spanish version of site to point to Spanish version

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#1637]
When someone is viewing the Spanish version of CEJST:

 - [ ] The footer link to whitehouse.gov should actually go to https://www.whitehouse.gov/es/

 - [ ] Survey link should point to https://www.surveymonkey.com/r/cejst-survey-es

**Comment by TomNUSDS** [comment]
Vim: I think the survey link part was done by me already somewhere else? 
Search code for `cejst-survey-es` before adding another url.

**Comment by esfoobar-usds** [comment]
I'm pretty sure I saw the Spanish link to the survey and Q/A'd it and it worked. But it does seem to be not working again. Maybe it was overwritten in the last `es.json` from State?

**Comment by katherinedm-usds** [comment]
good call out @esfoobar-usds yes I also remember this use to point to the Spanish version as intended
