### ISSUE TITLE
Add functionality to sign up to be added to CEQ mailing list to CEJST

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1640]

**Comment by katherinedm-usds** [comment]
The method that Holly Wilson the CEQ senior advisor for community engagement uses to haave people opt in is https://www.surveymonkey.com/r/whceqej, she includes this sign up link in her email signatures, etc.

**Comment by BethMattern** [comment]
Assigning this to you @KameronKerger so you can incorporate into designs.

**Comment by KameronKerger** [comment]
<img width="235" alt="Screen Shot 2022-09-15 at 2 23 36 PM" src="https://user-images.githubusercontent.com/77702996/190511289-fe09a53d-66e3-451f-b621-52fa602b5348.png">
done.

**Comment by KameronKerger** [comment]
also add to About page and PEC see screenshots. About change added to content 1.0 doc.
<img width="633" alt="sign-up-PEC" src="https://user-images.githubusercontent.com/77702996/191076454-a0dff32c-2185-4031-b56c-741a6d416589.png">
<img width="341" alt="Screen Shot 2022-09-19 at 10 19 47 AM" src="https://user-images.githubusercontent.com/77702996/191076460-61eae5ca-4bab-4952-bb08-fe69e40caf9e.png">

**Comment by vim-usds** [comment]
> also add to About page and PEC see screenshots. About change added to content 1.0 doc. <img alt="sign-up-PEC" width="633" src="https://user-images.githubusercontent.com/77702996/191076454-a0dff32c-2185-4031-b56c-741a6d416589.png"> <img alt="Screen Shot 2022-09-19 at 10 19 47 AM" width="341" src="https://user-images.githubusercontent.com/77702996/191076460-61eae5ca-4bab-4952-bb08-fe69e40caf9e.png">

@KameronKerger - Hi , is this captured in the Content 1.0 doc? If so, I'll close this, TY

**Comment by KameronKerger** [comment]
sorry @vim-usds but they've changed the link - please use
https://lp.constantcontactpages.com/su/Vm8pCFj/spring

in all three places - footer, about page, public engagement calendar page
