### ISSUE TITLE
Remove all the updated / new tags or indications on the download box on the methodology & data page

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1643]
**Describe the bug**
Since we are past the "window of newness", remove the coloring and tagging to indicate that things are new or have been updated on the methodology & data page. 

**To Reproduce**
1. Go to 'methodology & data'
2. See error

**Expected behavior**
Revert to normal state

**Screenshots**
<img width="609" alt="tags" src="https://user-images.githubusercontent.com/77702996/168181699-e971c70f-b657-4e9e-8079-0fbbe5e10dbe.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger - I believe we can close this right as the UI is no longer applicable?

**Comment by KameronKerger** [comment]
yes that tracks @vim-usds
