### ISSUE TITLE
From survey feedback -   "criteria" should be "criterion" in the following sentence: The tool ranks each census tract using percentiles...

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1647]
**Describe the bug**
Change criteria to criterion in the side panel unselected explanation of percentiles.

**To Reproduce**
1. Go to 'Explore the map'

**Expected behavior**
See above.

**Screenshots**
<img width="1245" alt="Screen Shot 2022-05-16 at 9 57 58 AM" src="https://user-images.githubusercontent.com/77702996/168644839-ae1967d9-76cb-4c57-83a2-a5583ab32a89.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger - is this simply the typo change? If so, I'll get it out this sprint

**Comment by KameronKerger** [comment]
yes @vim-usds I believe it is a singular / plural kinda thing.
