### ISSUE TITLE
Non prioritized communities are incorrectly reporting their burden because it is combined not each threshold

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1660]
**Describe the bug**
It looks like all non-DACS are showing 0 thresholds exceeded. (apparently this is by design, sigh). 

**To Reproduce**
1. Go to 'Explore the tool'
2. Click on 'a non-DAC'
3. Scroll down to 'side panel'

**Expected behavior**
The interface should specify that it is "combined" thresholds. so the string should read
At or above 0 combined thresholds

see updated screenshot below

**Screenshots**
<img width="243" alt="Screen Shot 2022-06-01 at 10 59 21 AM" src="https://user-images.githubusercontent.com/77702996/171476760-949110a1-a45e-4fb4-9e95-5f0d2c4d3c2d.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by esfoobar-usds** [comment]
@KameronKerger Can you give an example of a non-DAC that should show more than 0 categories?

**Comment by BethMattern** [comment]
@vim-usds the decision is to remove the "at or above X thresholds" from the UI

**Comment by KameronKerger** [comment]
closing and opening a new issue based on discussion during sprint planning
