### ISSUE TITLE
Implement approved changes to higher ed / income for 1.0

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1661]
Backend work for the score is complete - it also includes the enhancement to impute income where that data is missing.

**Comment by switzersc-usds** [comment]
@emma-nechamkin to confirm, this is done, but the score code is using the wrong variable names?

**Comment by emma-nechamkin** [comment]
thank you for tagging me! I believe so, see here: https://github.com/usds/justice40-tool/pull/1559/files

the score code pipes to score m rather than score narwhal

**Comment by switzersc-usds** [comment]
I'm not seeing anything in score narhwal that's getting assigned to score M field names. there's a log message that's incorrect but I change that in one of the open PRs.

**Comment by emma-nechamkin** [comment]
https://github.com/usds/justice40-tool/blob/emma-nechamkin/release/score-narwhal/data/data-pipeline/data_pipeline/etl/score/constants.py#L207 <-- i am thinking about these and their like. ideally we would be able to maintain score M with the OLD income calculation; i don't think that happens

**Comment by emma-nechamkin** [comment]
@vim-usds I believe that the new income variable ("adjusted and imputed") already goes to the front end correctly as income. Other than that, we should REMOVE the higher ed variable from the front end for narwhal. I suspect that's the only change here -- happy to pair / debug if you'd like?

**Comment by emma-nechamkin** [comment]
note: we will have to make new front end variables overall -- like all of the `SM_C`, `M_EBSI` etc variables will need "N" names. Here's the list of those columns. This is not strictly speaking about this ticket.

 ```
    field_names.M_WATER: "M_WTR",
    field_names.M_WORKFORCE: "M_WKFC",
    field_names.M_CLIMATE: "M_CLT",
    field_names.M_ENERGY: "M_ENY",
    field_names.M_TRANSPORTATION: "M_TRN",
    field_names.M_HOUSING: "M_HSG",
    field_names.M_POLLUTION: "M_PLN",
    field_names.M_HEALTH: "M_HLTH",
    field_names.SCORE_N_COMMUNITIES: "SM_C",
    field_names.SCORE_N_COMMUNITIES
    + field_names.PERCENTILE_FIELD_SUFFIX: "SM_PFS",
    field_names.CLIMATE_THRESHOLD_EXCEEDED: "M_CLT_EOMI",
    field_names.ENERGY_THRESHOLD_EXCEEDED: "M_ENY_EOMI",
    field_names.TRAFFIC_THRESHOLD_EXCEEDED: "M_TRN_EOMI",
    field_names.HOUSING_THREHSOLD_EXCEEDED: "M_HSG_EOMI",
    field_names.POLLUTION_THRESHOLD_EXCEEDED: "M_PLN_EOMI",
    field_names.WATER_THRESHOLD_EXCEEDED: "M_WTR_EOMI",
    field_names.HEALTH_THRESHOLD_EXCEEDED: "M_HLTH_EOMI",
    field_names.WORKFORCE_THRESHOLD_EXCEEDED: "M_WKFC_EOMI",
    field_names.WORKFORCE_SOCIO_INDICATORS_EXCEEDED: "M_WKFC_EBSI",
    field_names.FPL_200_SERIES: "M_EBSI",
}
```

**Comment by vim-usds** [comment]
Thanks @emma-nechamkin!

I'm assuming this list is exhaustive for Score N? 

Is there a backend ticket(s) associated with these changes? If I have the staging link then i can test these changes on the Frontend.

**Comment by emma-nechamkin** [comment]
no specific changes -- right now all the variables port to the M variables because I don't think the variables come up in the map UNLESS they are M variables?

**Comment by vim-usds** [comment]
Remove Higher Ed from all SocioEco indicators for 1.0 staging release branch

**Comment by vim-usds** [comment]
@Emma and @KameronKerger 

In 1.0, if we are removing higher Ed from the frontend, it seems that this would/could have a few effects in the frontend, namely; 

side panel:
![Screen Shot 2022-07-27 at 4 50 19 PM](https://user-images.githubusercontent.com/86254807/181391625-729a3580-7ad7-45ef-bd5d-369563024890.png)

methodology page:
![Screen Shot 2022-07-27 at 4 52 58 PM](https://user-images.githubusercontent.com/86254807/181391833-e740ba61-c2f2-4e6b-84f8-b8e21d852874.png)

![Screen Shot 2022-07-27 at 4 57 51 PM](https://user-images.githubusercontent.com/86254807/181392339-fe2b2e27-6e45-41ff-b0fc-dca064dfe4e0.png)

Does this capture all of it? 🤷‍♂️ 

I get the feeling that I might be jumping the gun on this task. 🤠 Do I have that right? If so, I can totally wait if it means we'll have a better handle on what needs to change. It would be awesome to meet up and discuss how we think the new design will look like before getting into implementation.

Thanks!

**Comment by KameronKerger** [comment]
I'll work on the updated panel comp today... but nothing has been approved so ::shrug emoji::

**Comment by vim-usds** [comment]
@KameronKerger - BTW, no rush at all, if things are still pending. I'm totally not the right person to decide at which point is the ambiguity low enough to start designs?!??
