### ISSUE TITLE
Rezip in the .csv and .xls files and include the codebook with each

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1679]
**Describe the bug**
Trying to solve a problem I created, can we include the codebook with the .csv and .xls files and have them as zip files? this solves two problems - one, it let's people get access to the codebook which they may need to understand the column names and two, it solves for the .csv on safari which just opens in another tab making it less useful for analysis purposes. Unfortunately I think this is both a front and back-end update.

**To Reproduce**
1. Go to 'Methodology & data'
2. Click on 'Downloads.'
3. Scroll down to 'the two file downloads.'

**Expected behavior**
See above. Will need to update to say it is a .zip containing a .xls (or .csv) and a codebook and the unzipped file size.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@esfoobar-usds - can we talk about this today by chance?

**Comment by vim-usds** [comment]
@esfoobar-usds so it sounds like we need 2 new zip files:
1. CSV + codebook
2. XLS + codebook

Also if we can name these zips like: `this-example-filename-name.zip` in kebab case

**Comment by vim-usds** [comment]
Not exactly sure.. this is what currently available in the downloads folder:

![Screen Shot 2022-07-18 at 12 41 00 PM](https://user-images.githubusercontent.com/86254807/179604015-88ac80ae-7cfd-49b0-b99b-621d3fed0d17.png)

I'm assuming the ones we want aren't here?

**Comment by BethMattern** [comment]
@vim-usds and @KameronKerger it's still in the sprint backlog column so I think it's just a matter of no one getting to it yet. We can pop it to the top of the list if this needs to get done soon.

**Comment by KameronKerger** [comment]
no pressure, just sometime on / before 1.0
