### ISSUE TITLE
Change data source for tribal boundaries to the BIA_AIAN_LAR_National dataset

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1684]
We need to use this data set to visualize tribal boundaries on the CEJST: https://biamaps.doi.gov/bogs/datadownload.html

- [x] Vim to provide some transparency on what is in this data set ( columns )

**Comment by vim-usds** [comment]
@BethMattern, @KameronKerger @katherinedm-usds 

## Downloaded data from above link
The link mentioned in this ticket's description allows us to download a shapefile, eg, BIA_National_LAR. This shapefile has 3 shapefiles embedded in them, namely:

1. BIA_National_LAR
2. BIA_AIAN_Supplemental
3. BIA_TSA

The following text file explains these datasets in more detail (download to view)
[Read Me AIAN LAR Vr9.txt](https://github.com/usds/justice40-tool/files/9012609/Read.Me.AIAN.LAR.Vr9.txt)

## What data fields exist in each data set?
 
### BIA_National_LAR:
![Screen Shot 2022-06-29 at 10 06 18 AM](https://user-images.githubusercontent.com/86254807/176494929-cb08b42a-c1f7-4584-a8a2-d19dbcafcda3.png)

### BIA_AIAN_Supplemental
seems like none

### BIA_TSA
![Screen Shot 2022-06-29 at 10 17 55 AM](https://user-images.githubusercontent.com/86254807/176497341-337c4fec-620f-4d97-adce-1255240565d9.png)

## How to view this on the map?

### Comparing this tribal land data with the previous tribal lands data

New tribal layers (this ticket):
1. BIA_National_LAR (red fill)
2. BIA_AIAN_Supplemental (yellow fill)
3. BIA_TSA (green fill)

Existing tribal layers:
4. AIANNH (green border - original data)
5. Alaska Native (dark blue border - original data)

These 3 sets have been added to a map here for comparison
![Screen Shot 2022-06-29 at 10 29 17 AM](https://user-images.githubusercontent.com/86254807/176501716-0a2f9ee4-449f-49f3-92a1-9cdba00aa4e4.png)

### Viewing all 5 layers with census tracts
https://screeningtool.geoplatform.gov/en/?flags=tl#5.03/34.13/-103.35

Open to discuss at anytime!

**Comment by BethMattern** [comment]
OK @vim-usds and @esfoobar-usds - LAR_Name it is. this will be the data we should see in the side panel and download file for now. We can continue to look for ways to supplement this in the future.

**Comment by BethMattern** [comment]
@vim-usds here's the alaska native villages fil
[AlaskaNativeVillages.gdb.zip](https://github.com/usds/justice40-tool/files/9021915/AlaskaNativeVillages.gdb.zip)
e

**Comment by vim-usds** [comment]
@katherinedm-usds and @BethMattern 

here is the map with the AlaskaNativeVillages added:
https://screeningtool.geoplatform.gov/en/?flags=tl#3/33.47/-97.5
They are the pink dots in Alaska

**Comment by vim-usds** [comment]
@katherinedm-usds and @BethMattern 

here is the map with the AlaskaNativeVillages added:
https://screeningtool.geoplatform.gov/en/?flags=tl#3/33.47/-97.5
They are the pink dots in Alaska

**Comment by lucasmbrown-usds** [comment]
@BethMattern @vim-usds -- can you confirm that the BIA_TSA (green in the mockup) area is also supposed to be on the map?

**Comment by lucasmbrown-usds** [comment]
@BethMattern confirms that they should all three be combined into one single layer and all displayed on the map.

**Comment by esfoobar-usds** [comment]
Thanks for the clarification @lucasmbrown-usds and @BethMattern!

**Comment by vim-usds** [comment]
Adding datafile here:
[BIA_National_LAR.zip](https://github.com/usds/justice40-tool/files/9628122/BIA_National_LAR.zip)
