### ISSUE TITLE
Implement the toggle to change from selecting census tracts to selecting tribal areas

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1692]
# Purpose

Since tribal areas will now be visible on the map, people would expect to interact with them to get information about the areas as they do the census tracts. Having a toggle to control what they want to select seems to be a reasonable solution.

## Desktop design

Map Header showing how search should be shortened to allow for `Select` and `Layer` (future)

<img width="600" alt="Screen Shot 2022-06-23 at 7 42 30 AM" src="https://user-images.githubusercontent.com/77702996/184241479-48b4938c-ca64-4a51-99e7-6ab3bbfef6b0.png">

Map Header showing `Select` along with Search Geolocate messages:

![Search+Geo+Tribal Mocks](https://user-images.githubusercontent.com/86254807/188731543-d72bc357-e9f9-4478-a5df-262699ba1fb7.png)

Just the `Select` component expanded:

<img width="341" alt="Screen Shot 2022-06-23 at 7 42 30 AM" src="https://user-images.githubusercontent.com/77702996/175326763-26ec6f0a-7ef2-4397-8757-5611339c8abe.png">

`Select` component in Map Header with all possible messaging:
![Screen Shot 2022-09-06 at 1 33 26 PM](https://user-images.githubusercontent.com/86254807/188732844-2233e060-50fe-4655-953a-d410f156b600.png)

## Mobile design

<img width="341" alt="Screen Shot 2022-06-23 at 7 42 30 AM" src="https://user-images.githubusercontent.com/77702996/184241465-b37f46c7-b676-48a2-b9c3-76d90d7bd290.png">

## Engineering
- [ ] implement desktop`Select` component. This would be a custom component. We can totally make this happen however it will take longer than an existing component. Can we use [a Select UI](https://trussworks.github.io/react-uswds/?path=/story/components-combo-box--custom-input-change-handler) instead?
- [ ] I'm assuming that this `Select` component will have 4 states only, `open`, `closed`, `tracts selected` or `tribal selected`. When the map is first loaded, it will show it being `closed` with `tracts selected`?
- [ ] implement mobile `Select` component. The bottom panel is also a custom component. We can totally make this happen however it will take longer than an existing component. Can we use a [modal](https://trussworks.github.io/react-uswds/?path=/story/components-modal--default-modal) instead?
- [ ] i18n
- [ ] mobile design / testing 
- [ ] add layer state to URL so that if someone shares the link with a tribal layer selected, the map should render the same layer selected (enhancement)
- [ ] Figure out some way to show smaller areas at low zoom ( e.g. CO, enhancement)

**Comment by vim-usds** [comment]
think about selecting each indicator for future use case

**Comment by vim-usds** [comment]
@KameronKerger - super quick implementation. How does this seem so far?

https://user-images.githubusercontent.com/86254807/178091575-4b064911-b107-4d4c-b067-bdc9b9706429.mov



On mobile, real estate is super scarce. Can we say tracts and tribal for the two buttons?

**Comment by vim-usds** [comment]
@KameronKerger 

## Layout ideas

### Desktop
Here's one layout for the tribal selection UI
![TribalSelectUI_DesktopV1](https://user-images.githubusercontent.com/86254807/184162339-49b1f04e-4704-4862-848e-3ed6c63184db.png)

The issue with this :

1. It's pretty crowded in the header
2. managing responsive on this will be more work

Here's the preferred layout
![TribalSelectUI_DesktopV2](https://user-images.githubusercontent.com/86254807/184163055-54d8971b-d0a0-4176-ac88-356051d08849.png)

### Mobile
The desktop v2 makes mobile easier:

![TribalSelectUI_MobileV1](https://user-images.githubusercontent.com/86254807/184161745-5c68cbb3-566a-448e-b15a-c1a60145a839.png)

What are your thoughts on these?

**Comment by KameronKerger** [comment]
on desktop can the search bar just be made shorter horizontally? ideally there should be enough room for select and eventually layers...
for mobile the proposal would be to place a second icon under the geolocation icon that opens the two options at the bottom of the screen. 
see screenshots for both
<img width="490" alt="Screen Shot 2022-08-11 at 1 55 27 PM" src="https://user-images.githubusercontent.com/77702996/184240786-2abc82b9-72f7-4bc9-b31a-88a711b3ddb2.png">
<img width="345" alt="Screen Shot 2022-08-11 at 1 55 07 PM" src="https://user-images.githubusercontent.com/77702996/184240789-32be6547-d5cc-4312-97d2-ef64029c5b21.png">

**Comment by vim-usds** [comment]
@KameronKerger - these designs are so wonderbar! Looking into seeing if we can make them happen.

Would it be possible to show the desktop view with the select and layers dropdown expanded, along with geolocation icon?

**Comment by BethMattern** [comment]
We are not going with this solution. Creating a new issue
