### ISSUE TITLE
Remove geolocation from behind the feature flag and update the behaviors if necessary

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1694]
**Is your feature request related to a problem? Please describe.**
Allow people to easily geolocate themselves on the map. Consider this as a default behavior for mobile.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger - a few questions around UI messaging :)

# State diagram of geolocation UI

Thanks for the meeting today. I wanted to capture the various states we discussed today. If my understanding is correct, we want three states for geolocation:

1. off
2. locating
3. locked with beacon on map

![Screen Shot 2022-07-15 at 6 14 53 PM](https://user-images.githubusercontent.com/86254807/179328754-afa21095-c0cc-431e-8395-d168796fb2f2.png)

## States

### Geolocation `off`
This is the state when the geolocation beacon is not displayed anywhere on the map. This is the initial state of the map. The map will also enter this state whenever the beacon is moved out of the view. 

Question: When the beacon is moved out of view should we inform the user that `Geolocation is now off` ❓ 

### Geolocation `locating`
This state is entered when the button is clicked from a geolocating `off` state. The UI will display "Geolocating..." ✅ 

### Geolocation `locked`
This state is entered when Geolocation is found and the beacon is in view. 

Question: When the beacon is view, should we inform the user that "Geolocation found!" ❓ 

![Screen Shot 2022-07-15 at 6 22 43 PM](https://user-images.githubusercontent.com/86254807/179329174-f3db0c3c-fdee-413c-9338-0f271c92b1a7.png)
