### ISSUE TITLE
Loading map does not show full set of zoomed-out DAC tracts

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#1702]
**Describe the bug**

**To Reproduce**
1. (On my personal device) go to https://screeningtool.geoplatform.gov which then redirects to https://screeningtool.geoplatform.gov/en/#3/33.47/-97.5

**Expected behavior**
Expect to see zoomed-out view of tracts that are DAC or not for all US

**Screenshots**
1st try, no DAC areas were shown
![image.png](https://images.zenhubusercontent.com/609ab603576fa56647137b9e/8df093de-698b-4b78-9cfe-dd997cb0b476)

2nd try, DAC areas were not shown for Washington, Montana, North Dakota, Minnesota, the states directly to the south of those states, plus Nebraska

![image.png](https://images.zenhubusercontent.com/609ab603576fa56647137b9e/68c0abbb-0edb-4d9f-9532-da15a8210d85)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
.

**Comment by vim-usds** [comment]
@katherinedm-usds - does the issue go away after [clearing your cache](https://support.springboardvr.com/hc/en-us/articles/360003694433-How-do-I-clear-my-Browser-Cache-)?

**Comment by BethMattern** [comment]
@katherinedm-usds is this still an issue?

**Comment by BethMattern** [comment]
@katherinedm-usds is this still an issue?

**Comment by katherinedm-usds** [comment]
I no longer see this issue, closing
