### ISSUE TITLE
Remove linguistic isolation from PR data 

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1704]
**Is your feature request related to a problem? Please describe.**
Currently we only removed the linguistic isolation data for Puerto Rico no the front end. It needs to also be removed from the data pipeline so it doesn't appear in the spreadsheets and cause confusion. Also consider recalculating the linguistic isolation percentiles. While PR is only a small number of tracts, the linguistic isolation numbers were in the 99th percentile for most of PR so it might bring some other tracts that are on the margins in for that threshold.

**Describe the solution you'd like**
Remove linguistic isolation from the PR data 
Update the percentile calculations for linguistic isolation for all tracts

**Describe alternatives you've considered**

**Additional context**

**Comment by KameronKerger** [comment]
@vim-usds it is related to this ticket https://github.com/usds/justice40-tool/issues/1625 and it is a 1.0 thing. I believe you have already done the front end ticket. this is a data fix only.

**Comment by vim-usds** [comment]
@esfoobar-usds - is this something @switzersc-usds worked on?

**Comment by esfoobar-usds** [comment]
I believe so!

**Comment by BethMattern** [comment]
I'm moving this to review/QA because I believe this is done.
