### ISSUE TITLE
Assess adding TRI data from RSEI model data

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1716]
Source - EPA
Add to: Legacy pollution

Pull in the air version of the data.

Here's one set of data https://gaftp.epa.gov/rsei/Census_XWalks

and here's another that includes MDB files https://www.epa.gov/sites/production/files/2015-07/rsei_2010_census_table_0.zip.

This is probably the best way to read in MDB on a mac: https://stackoverflow.com/a/42610107.

Data overview at https://www.epa.gov/rsei/ways-get-rsei-results#microdata.

**Comment by emma-nechamkin** [comment]
Sindhu has requested this data and we are awaiting it.

**Comment by emma-nechamkin** [comment]
Information from Mitch suggests this analysis is using "wrong" information. To redo, using files from Mitch et all

**Comment by emma-nechamkin** [comment]
suggest not to include.
