### ISSUE TITLE
Assess adding no kitchen or indoor plumbing data 

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1717]
Source: HUD CHAS - https://www.huduser.gov/portal/datasets/cp/CHAS/bg_chas.html - "2) housing unit lacks complete plumbing facilities"
Add to: Affordable housing

**Comment by BethMattern** [comment]
@emma-nechamkin check-in with @lucasmbrown-usds before starting this work because these data tables are a bit tricky.

**Comment by emma-nechamkin** [comment]
@lucasmbrown-usds can we do this async? I *think* we pull from T3. 

From CHAS table 3:
- `T3_est2` is subtotal: owner-occupied for all levels of income
- `T3_est3` is subtotal: owner-occupied lacking complete plumbing or kitchen facilities for all levels of income
- `T3_est45` is subtotal: renter-occupied for all levels of income
- `T3_est46` is subtotal: renter-occupied lacking complete plumbing or kitchen facilities for all levels of income

I have this as (renters without kitchen / bathroom + owners without kitchen / bathroom) / (all renters + all owners)

**Comment by lucasmbrown-usds** [comment]
That seems right to me! And much simpler than our other housing calculations. 

If you want, we can run it past Blair at HUD to check that we're calculating the data accurately. See you email for his info.
