### ISSUE TITLE
Large census tracts (like in Alaska) are behaving inconsistent w/ other parts of the US when you zoom out the tracts get deselected

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1722]
**Describe the bug**
Go to Alaska, zoom in and select a census tract (they are very large in Alaska). When you zoom out, the tract gets deselected. This is inconsistent with other parts of the US. I think this is because the boundaries are disappearing. You get a similar behavior in Montana (see screenshots) but the tract is not actually deselected, the boundaries just disappear.

**To Reproduce**
1. Go to 'Alaska'
2. Click on 'a census tract'
3. Zoom out

**Expected behavior**
The tract should not appear to deselect.

**Screenshots**
<img width="989" alt="Screen Shot 2022-07-07 at 8 34 03 AM" src="https://user-images.githubusercontent.com/77702996/177813599-0313ffe6-eca3-413c-83c7-aeb73092b9e4.png">
<img width="1007" alt="Screen Shot 2022-07-07 at 8 33 56 AM" src="https://user-images.githubusercontent.com/77702996/177813616-eecd3cc3-9c15-4cb9-b7ec-2a40afe6d5f4.png">
<img width="997" alt="Screen Shot 2022-07-07 at 8 32 41 AM" src="https://user-images.githubusercontent.com/77702996/177813628-9e5d02e5-295d-45e5-b3ec-1e5e75ed197a.png">
<img width="1014" alt="Screen Shot 2022-07-07 at 8 32 33 AM" src="https://user-images.githubusercontent.com/77702996/177813632-ab9e9d67-f8a5-4400-8789-5f7c819c59ea.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger, @esfoobar-usds

So for zoom levels between 3 -7 (low zoom) we aggregate various census tracks together, at this zoom level no tracts are selectable. This low zoom has a distinct URL. After zoom level 7 (high zoom), the aggregated census tracks are made distinct and each tract is clickable. This high zoom layer has its own URL.

In the case of Alaska, the tracts are so big that they are not viewable in their entirety when the zoom level is above 7. So we naturally zoom out (lowering zoom). To see the entire selected area, we eventually have to cross zoom level 7 and this aggregates census tracts and the selected tract no longer exists.

My naive way to fix this would be to
1. determine the census tract area for each census tract
2. determine the relationship between census area and the zoom level to fit entire tract “in-view”
3. Identify all tracts that require a zoom level < 7 to fit “in-vew”, let’s refer to these as “low-zoom-100%-in-view” tracts
4. Remove these "low-zoom-100%-in-view" tracts from existing layers and maybe place them on their own layer with their own selection logic?

@esfoobar-usds - let's chat about this next week

**Comment by vim-usds** [comment]
Corollary: So I can enable the low zoom layer to be interactive so if you click on an aggregated census tract, it becomes interact-able, however I believe in order for me to show the border around an aggregated tract I need a unique identifier for the aggregated tract

### high zoom feature properties
Notice how the how the high zoom layer has the unique GEOID property:

![HighZoomFeatureProps.png](https://images.zenhubusercontent.com/60d4d92c1bf5e498d6e808ba/522f6a23-1030-439a-adc5-ed41c5090c3a)

### low zoom feature properties
here the low zoom only has the M_SCORE as a property
![LowZoomFeatureProps.png](https://images.zenhubusercontent.com/60d4d92c1bf5e498d6e808ba/38af2457-7434-4bf6-9dd0-48355f98a14b)

**Comment by vim-usds** [comment]
After some analysis:

![Screen Shot 2022-07-11 at 4.54.03 PM.png](https://images.zenhubusercontent.com/60d4d92c1bf5e498d6e808ba/0fb435af-bf95-4946-9be5-79ce53e20d41)

**Comment by vim-usds** [comment]
Jupyter code in case anyone wants to try it:

```
import geopandas as gpd
import pathlib

lowJson = pathlib.Path() / 'usa-low.json'
assert lowJson.exists()
highJson = pathlib.Path() / 'usa-high.json'
assert highJson.exists()

gdf = gpd.read_file(highJson)
gdf['area'] = gdf.apply(lambda row : gpd.GeoSeries(row['geometry']).area, axis = 1)

gdf['zlfc'] = 0
gdf.at[9846, 'zlfc'] = 4.45
gdf.at[10212, 'zlfc'] = 7.08
gdf.at[9937, 'zlfc'] = 5.5
gdf.at[9857, 'zlfc'] = 5.5
gdf.at[9935, 'zlfc'] = 5.38
gdf.at[9936, 'zlfc'] = 5.77
gdf.at[9921, 'zlfc'] = 6.1
gdf.at[9847, 'zlfc'] = 5.33


gdf_short = gdf[["GEOID10", "SF", "CF", "area", "zlfc"]]
gdf_short_sorted = gdf_short.sort_values(by='area', ascending=False);
gdf_short_sorted.head(30)
```
