### ISSUE TITLE
(maybe goes away for 1.0) this tract in AS (see url in body) is identified as disadvantaged and under the current methodology it shouldn't be

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1730]
**Describe the bug**
[A clear and concise description of what the bug is.](https://screeningtool.geoplatform.gov/en/#9.43/-14.2111/-169.5465)
Because it is missing higher ed data it can't be above both thresholds and therefor shouldn't be "disadvantaged" - we haven't done any missing data imputations yet.

**To Reproduce**
1. Go to '[...](https://screeningtool.geoplatform.gov/en/#9.43/-14.2111/-169.5465)'
2. Click on 'tract that has the two islands in the left - 60020951800.'
3. Scroll down to 'higher ed non-attainment'

**Expected behavior**

**Screenshots**
<img width="860" alt="Screen Shot 2022-07-07 at 2 11 00 PM" src="https://user-images.githubusercontent.com/77702996/177872035-f4a66ee7-273d-4c5a-8f83-2d901bef4966.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BethMattern** [comment]
Fixed in 1.0
