### ISSUE TITLE
All links should be the same color and visited links should be consistent

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1775]
**Describe the bug**
I thought there was a bug for this already but I can not find it but the links on the CEJST are not the same color. They are different shades of blue. My preference is for the blue in the header "here's how you know" which is #005ea2. The other, less preferable blue is rgb(0, 0, 238). The visited links are also inconsistent. I think the opens new tabs ones don't change after visiting. See screenshots.

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="705" alt="Screen Shot 2022-07-28 at 12 10 49 PM" src="https://user-images.githubusercontent.com/77702996/181618752-8108d75b-4cec-4e48-8bc4-1a009ccb2c6d.png">
<img width="712" alt="Screen Shot 2022-07-28 at 12 07 43 PM" src="https://user-images.githubusercontent.com/77702996/181618760-751164bf-47df-41f4-9343-31ccca13d55f.png">
<img width="1164" alt="Screen Shot 2022-07-28 at 12 07 29 PM" src="https://user-images.githubusercontent.com/77702996/181618766-b07eb3df-2733-46ce-92d2-f98cdec8f954.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BethMattern** [comment]
@KameronKerger prefers the color in for the "Here's how you know" link

**Comment by vim-usds** [comment]
Reference material on this refactor:
https://ashleemboyer.com/blog/should-i-use-a-button-or-a-link
