### ISSUE TITLE
Create and assess indicator of natural space

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#1776]
**Description**
Create a new indicator for natural space (exact name TBD) that is calculated as: 

1 - (% impervious) - (% crop-land) 

to get the percent of each tract that is natural space. 

% imperviousness comes from NLCD, sourced intermediate from CDC. We've already loaded this data source into Python notebooks. 

% crop-land comes from USDA Cropland Data Layer (CDL). We have not loaded this data yet.

Assess top 10 percentile of tracts meeting socioeconomic criteria.

**Comment by lucasmbrown-usds** [comment]
Creating Impervious plus Cropland Attributes for Census Tracts

Crops
1.	Add an attribute called TractAcres (or similar) to the census tracts to hold a value representing acres covered by the census tract.
2.	Calculate the TractAcres field for each census tract by using the Calculate Geometry tool (set the Property to Area (geodesic), and the Units to Acres).
3.	From the Cropland Data Layer (CDL), extract only the pixels representing crops, using the Extract by Attributes tool in ArcGIS Spatial Analyst toolbox.
        a.	The attribute table tells you the names of each type of land cover.  Since the CDL also contains NLCD classes and empty classes, the actual crop classes must be extracted.
4.	From the crops-only raster extracted from the CDL, run the Reclassify tool to create a binary layer where all crops = 1, and everything else is Null.
5.	Run the Tabulate Area tool:
        a.	Zone data = census tracts
        b.	Input raster data = the binary crops layer
        c.	This will produce a table with the square meters of crops in each census tract contained in an attribute called VALUE_1
6.	Run the Join Field tool to join the table to the census tracts, with the VALUE_1 field as the Transfer Field, to transfer the VALUE_1 field (square meters of crops) to the census tracts.
7.	Add a field to the census tracts called AcresCrops (or similar) to hold the acreage of crops in each census tract.
8.	Calculate the AcresCrops field by multiplying the VALUE_1 field by 0.000247105 to produce acres of crops in each census tracts.
        a.	You can delete the VALUE_1 field.
9.	Add a field called PctCrops (or similar) to hold the percent of each census tract occupied by crops.  
10.	Calculate the PctCrops field by dividing the AcresCrops field by the TractAcres field, and multiply by 100 to get the percent.

Impervious
1.	Run the Zonal Statistics as Table tool:
        a.	Zone data = census tracts
        b.	Input raster data = impervious data raster layer
        c.	Statistics type = Mean
        d.	This will produce a table with the percent of each census tract occupied by impervious surfaces, contained in an attribute called MEAN
2.	Run the Join Field tool to join the table to the census tracts, with the MEAN field as the Transfer Field, to transfer the MEAN field (percent impervious) to the census tracts.
3.	Add a field called PctImperv (or similar) to hold the percent impervious value.
4.	Calculate the PctImperv field by setting it equal to the MEAN field.
        a.	You can delete the MEAN field.
Combine the Crops and Impervious Data

1.	Open the census tracts attribute table and add a field called PctNatural (or similar).  Calculate this field using this equation:  100 – PctCrops – PctImperv .  This produces a value that tells you the percent of each census tract covered in natural land cover.
2.	Define the census tracts that fall in the 90th percentile of non-natural land cover:
        a.	Add a field called PctNat90 (or similar)
        b.	Right-click on the PctNatural field, and click Sort Ascending (lowest PctNatural values on top)
        c.	Select the top 10 percent of rows after the sort
        d.	Click on Show Selected Records in the attribute table
        e.	Calculate the PctNat90 field for the selected records = 1
        f.	Clear the selection
        g.	The rows that now have a value of 1 for PctNat90 are the most lacking for natural land cover, and can be symbolized accordingly in a map

**Comment by emma-nechamkin** [comment]
Gotta do this by Thursday

**Comment by emma-nechamkin** [comment]
Email sent to team for raster data 8/10

**Comment by emma-nechamkin** [comment]
Data received. Preliminary information reported in drive.
