### ISSUE TITLE
Add FUDS data

### ISSUE THREAD

**Issue by emma-nechamkin** [usds/justice40-tool#1781]
Add fuds to legacy pollution, including streamlining the points -> tracts code

**Comment by mattbowen-usds** [comment]
So I don't forget, the various FUDS datasets are available for download here: https://geospatial-usace.opendata.arcgis.com/search?q=fuds

**Comment by emma-nechamkin** [comment]
When you add this data -- we are looking at whether or not there is an eligible property within a given census tract. The code Lucas has should do this filter. 

The output from this code should be a boolean -- contains or does not contain at least one FUDS

**Comment by emma-nechamkin** [comment]
[https://app.zenhub.com/files/358242767/2603a754-ab5f-4e9e-aff4-bdf67c3c7270/download](https://app.zenhub.com/files/358242767/2603a754-ab5f-4e9e-aff4-bdf67c3c7270/download)
