### ISSUE TITLE
Updates to map side panel to add new methodology indicators

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1782]
Add the following new data indicators to the map side panel:
kitchen/plumbing - housing
impervious surfaces - climate change
underground storage tanks - water
travel disadvantage - transportation
abandoned mine lands - legacy pollution
FUDS sites - legacy pollution
Historic underinvestment - housing

Adjacency index - this is an exception and doesn't go under any one category

**Comment by vim-usds** [comment]
Thanks @Beth - This seems like a milestone, if those are still working!

**Comment by vim-usds** [comment]
These have been added to the 1.0 staging link
