### ISSUE TITLE
Add adjacency index to methodology

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1783]
Donut hole work is now called 'adjacency index' and we will consider a tract a DAC if it is 100% surrounded by DACS

**Comment by emma-nechamkin** [comment]
For adjacency index: it's the share of all neighbors (contiguous) that are DACs. 

To do this, we need to spatially join the following: df_only_score_0, df_all 
and take the average of Definition N (communities). 

We should report this back, early! Then, in score_narwhal, we can define the threshold.

**Comment by BethMattern** [comment]
@emma-nechamkin is this a duplicate of #1507?
