### ISSUE TITLE
Set min and max values in the header so that the text doesn't unnecessarily wrap

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1784]
**Describe the bug**
Safari is adding line breaks to "explore the map" and "methodology & data". I can see that the USWDS lets you set mix / max values.
 $theme-header-max-width
Maximum width of the header.
 $theme-header-min-width
Can we use that so that the text doesn't wrap like it does on chrome? 
see screenshots

**To Reproduce**
1. Go to 'Safari' > screeningotool.geoplatform.gov

**Expected behavior**
Header text shouldn't wrap unless the window / screensize needs to.

**Screenshots**
<img width="1272" alt="Screen Shot 2022-08-01 at 10 31 27 AM" src="https://user-images.githubusercontent.com/77702996/182208528-dd835ac6-6aa6-49ff-ac0c-6162474b66d1.png">
<img width="1490" alt="Screen Shot 2022-08-01 at 10 31 09 AM" src="https://user-images.githubusercontent.com/77702996/182208532-cad4e295-10a9-4803-afc9-141ccabd5020.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger - I wish we were using the `theme` feature of USWDS. We are not. We're using the grid system which is based on flex-box.

### The wrapping that's occurring now:

https://user-images.githubusercontent.com/86254807/182531307-129ea104-5d91-4629-bc90-7f5444e89731.mov

### One fix:

https://user-images.githubusercontent.com/86254807/182531250-ef9d7518-e1a8-4562-9d00-4fe3a180ad97.mov

Another option could be to reduce the font size below a certain width like 400 px to avoid the 'e' getting cut off? 🤷 

Great catch!

**Comment by KameronKerger** [comment]
I agree with the solution to reduce the pt size to avoid loosing the e
the problem, which @katherinedm-usds caught not me, is that the text is always wrapping on safari, even when the window is desktop full screen - explore the map and methodology & data both take up two lines, even though there is plenty of horizontal space available...
