### ISSUE TITLE
Rewrite all downloadable csv and xlsx YAMLS to take only low income and not higher ed

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1785]
All of the downloadable file configs use the low income, low higher ed formulation of our variables. We need to change these all to match 1.0

**Comment by BethMattern** [comment]
@esfoobar-usds @emma-nechamkin who should this be assigned to?

**Comment by emma-nechamkin** [comment]
please not me 🙏

**Comment by esfoobar-usds** [comment]
I'll take it but I'll ask @emma-nechamkin which are the right ones?

**Comment by emma-nechamkin** [comment]
Well I think this is actually not going to be necessary with the refactor, thinking this through? Because we aren't going to use the configs anymore I thought?

**Comment by esfoobar-usds** [comment]
Right, but I don't know if we'll have that for 1.0

**Comment by emma-nechamkin** [comment]
Ahhh I see. I can take it then

**Comment by emma-nechamkin** [comment]
This is done.
