### ISSUE TITLE
Choose methodology for combining data from census tracts into census block groups

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#179]
We need a methodology for combining data from census tracts into census block groups so that we can use the DOE LEAD score and other future data sets that are at the tract level.

**Comment by lucasmbrown-usds** [comment]
Notes: 
* Recommended to not get into percentiles at the tract level, keep raw value from tract, assign that to every single CBG, then calculate percentiles at the CBG level. 

* Communication: on health data, need to be clear that this was originally at tract level, else people might be concerned about small samples revealing private information.
