### ISSUE TITLE
Ensure that all download files to include new data indicators

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1799]
Add the following new data indicators to the map side panel:
no kitchen/plumbing 
lack of green space
underground storage tanks
travel disadvantage
abandoned mine lands 
Formerly used defense sites
Historic underinvestment
Adjacency index

**Comment by esfoobar-usds** [comment]
Latest zip download packet: https://justice40-data.s3.amazonaws.com/data-pipeline-staging/1822/6e9c44ea7266b055f0dac0e797449d1efbc9f6b7/data/score/downloadable/Screening_Tool_Data.zip
