### ISSUE TITLE
Airports are still purple which is too close to the DACs color.

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1800]
**Describe the bug**
Airports are still purple which is too close of a color to the DACs. I believe it was supposed to be changed to none. See screenshots

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="742" alt="Screen Shot 2022-08-05 at 2 06 49 PM" src="https://user-images.githubusercontent.com/77702996/183183252-3bf1609b-3b19-422b-b726-4e488d3ba90f.png">
<img width="981" alt="Screen Shot 2022-08-05 at 2 05 14 PM" src="https://user-images.githubusercontent.com/77702996/183183401-5e925ca7-e201-4436-935c-2053613a6d89.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
Latest map shows good distinction and therefore closing this ticket

![Screen Shot 2022-09-06 at 4.44.12 PM.png](https://images.zenhubusercontent.com/60d4d92c1bf5e498d6e808ba/51fe2cf0-659e-41a3-989e-a64deb1f92bd
)
