### ISSUE TITLE
Run demographics reports on beta version of CEJST

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1808]
Data needed:

1. 	% of population in DACs vs, non-DACs by race/ethnicity (as reported in the census)
2. 	% of people of color and whites in DAC and non-DACs
3. 	% of majority white / majority non-white tracts for DACs and non-DACs
a. 	Run reports by each race/ethnicity
4. 	% of population that are low income (in the 65th percentile or above low income) by race/ethnicity
5. 	Of the tracts that are low income, majority tracts by race/ethnicity
6. 	Share of DACs / non-DACs in Census age ‘buckets’

**Comment by emma-nechamkin** [comment]
Draft report attached. [https://app.zenhub.com/files/358242767/fa40fa3f-987e-41f6-bf0f-08bf93ba9cae/download](https://app.zenhub.com/files/358242767/fa40fa3f-987e-41f6-bf0f-08bf93ba9cae/download)

**Comment by emma-nechamkin** [comment]
[beta_demo_report.pdf](https://github.com/usds/justice40-tool/files/9293965/beta_demo_report.pdf)
