### ISSUE TITLE
Rename the download folder and files

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1811]
**Describe the bug**
Usa and "communities + date" is not a descriptive enough name for the download folder and files. Can we update them to be more descriptive and more closely tied to the CEJST? Open to suggestions but something like:
CEJST_downloads
CEJST_communities
CEJST_list

and then the file names follow the chosen format.

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="768" alt="Screen Shot 2022-08-09 at 10 51 35 AM" src="https://user-images.githubusercontent.com/77702996/183724737-e9dc09ee-9786-44cc-83b7-7bb41c4d3ace.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
I recommend that download files that have a link on frontend like:

https://static-data-screeningtool.geoplatform.gov/data-pipeline/data/score/downloadable/communities-2022-05-31-1915GMT.xlsx

https://static-data-screeningtool.geoplatform.gov/data-pipeline/data/score/downloadable/communities-2022-05-31-1915GMT.csv

https://static-data-screeningtool.geoplatform.gov/data-pipeline/data/score/shapefile/usa.zip

I would recommend kebab case as I believe it's easier to read when being shared. The first two links have kebab case while usa doesn't really as it lacks description.

**Comment by BethMattern** [comment]
@esfoobar-usds i think this might be a duplicate now that you have worked out what needs to be done for the previous versions page vs. the downloads page for 1.0, right?

**Comment by esfoobar-usds** [comment]
Yes, this is being addressed in other tickets.
