### ISSUE TITLE
Add demographics to tiles so they can be displayed in the map side panel

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1827]
See https://github.com/usds/justice40-tool/issues/1516#issuecomment-1198733110.

**Comment by lucasmbrown-usds** [comment]
@BethMattern @KameronKerger @emma-nechamkin -- just realized the work for https://github.com/usds/justice40-tool/issues/1851 would be pretty extensive to pull this in from Decennial 2010 data, so moved to a separate ticket, probably for post-1.0?
