### ISSUE TITLE
Remove US Virgin Islands and Guam from the downloadable data files

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1830]
**Describe the bug**
Since the tool clearly states that there is no data available for the US Virgin Islands and Guam, they should not appear in the downloadable files as it creates confusion. 

Of note: apparently there is unemployment data for these territories

**To Reproduce**
1. Go to 'downloads'
2. Click on 'download files'
3. Scroll down to 'Guam / US Virgin Islands'

**Expected behavior**
US Virgin Islands and Guam should be removed from all the downloadable data files.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BethMattern** [comment]
we have added USVI and Guam to CEJST 1.0 so this can be closed.

**Comment by KameronKerger** [comment]
this is no longer applicable
