### ISSUE TITLE
Missing life expectancy data for WI and potentially another state

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1831]
**Describe the bug**
We are only ingesting 49 of 51 available states from https://www.cdc.gov/nchs/nvss/usaleep/usaleep.html

**Expected behavior**
We should be including all available states

NOTE: it appears Maine is also missing.

**Comment by emma-nechamkin** [comment]
I think we should actually generalize this! Once the earlier testing tickets are completed, we will have a list of all states / territories per dataset. Then, we can manually confirm that those are the correct states!

**Comment by lucasmbrown-usds** [comment]
Other state is probably Maine.
