### ISSUE TITLE
Correctness tests on each data source nulls and 0s

### ISSUE THREAD

**Issue by emma-nechamkin** [usds/justice40-tool#1835]
In my mind's eye, the first of each pair can be a series of unit tests, but the second must be manual because of the front end work. 
- [ ]  Confirm nulls are preserved throughout until the score is generated
- [ ] Confirm nulls are nulls on the map as well 
- [ ] Confirm 0s are preserved throughout until the score is generated
- [ ] Confirm 0s are 0s on the map as well

**Comment by vim-usds** [comment]
If there are certain tracts that we know should have nulls and/or 0s, then the FE could use this as a test to make sure it's working

**Comment by emma-nechamkin** [comment]
That's awesome! Can we check in early next week (maybe Monday?) to discuss how to have some tests that persist into the front end as well?

**Comment by emma-nechamkin** [comment]
@vim-usds we can convert this to a front-end QA ticket. 

I'm not sure how front end testing works, but maybe I can provide a list of tracts that are 0s / nulls for each column and we can verify? or do you think this isn't necessary?

**Comment by vim-usds** [comment]
Cool yes! @emma-nechamkin 

First off, I think having a test in place is the safest way to go. Let's call the "list of tracts that are 0s/nulls for each column" the `zero_null_tracts`. Just to be concrete, this will be a list of tracts and their column(s) that have 0 or null values. 

For a given tract from the `zero_null_tracts` list, It would be great to figure out which PBF file this tract is in. The folder location usually provides that for example `...5/6/11.pbf` would give me the info I need to 

1. download the PBF for a given tract under test
2. check if a certain indicator is either 0 or null
3. validate that the UI also shows 0 or null

What do you think?

**Comment by mattbowen-usds** [comment]
The tests for
[ ] Confirm nulls are nulls on the map as well
[ ]  Confirm 0s are 0s on the map as well

Ended up in #1848 with tests for tlies.csv
