### ISSUE TITLE
Back end "pipeline-y" tests

### ISSUE THREAD

**Issue by emma-nechamkin** [usds/justice40-tool#1848]
The following is a list of tests that we should add for the backend to ensure that we are passing the correct values forward into the front end. 

__Per data source:__ The goal here is tracts in should equal tracts out
- [x] All census tracts with a entry per numeric column (percentile, etc) should be represented in the `usa.csv` for that data source
- [x] All census tracts that do not have a entry per numeric column should NOT be included in the `usa.csv` for that source, column combination 

__Tiles and data pipeline:__ The goal here is to smoke test correctness
- [x] We should check for wrong variable ported over to the tiles by making sure the column name for each thing we want in `usa.csv` has the same value as the column name for the tiles csv. This is NOT the same as checking that the column has been renamed. Rather, this requires looking at the methodology of the tool, seeing what should be represented, and ensuring that variable is indeed represented. 
- [ ] Check for USVI and Guam in tiles
- [x] We should check that even census tracts that have NULLs for every indicator get included in the tiles and in the csv and are never dropped

__Tests we don't need right now__
- [ ] Threshold counts in island areas don’t match number of thresholds possible --> we've dropped this for now
- [ ] Codebook test (I think for now, this is fine -- will be no longer needed with refactor?)

**Comment by mattbowen-usds** [comment]
This isn't quite done yet, since I'm now working through each source

**Comment by mattbowen-usds** [comment]
Also, so I don't have to keep checking, this list of sources

- [ ] ejscreen
- [ ] census
- [ ] hud_housing
- [x] cdc_places
- [ ] census_acs_median_incomes
- [x] cdc_life_expectancy
- [x] doe_energy_burden
- [x] national_risk_index
- [ ] geocorr_urban_rural
- [ ] persistent_poverty
- [ ] census_decennial
- [ ] census_2010
- [ ] national_tract
- [ ] hrs
- [ ] dot_travel_disadvantage
- [ ] fsf_flood
- [ ] fsf_fire
- [ ] nature_deprived
- [x] eamlis
- [x] fuds

**Comment by mattbowen-usds** [comment]
We have done as much of this as we ever will.
