### ISSUE TITLE
Tract lists for ground-truthing

### ISSUE THREAD

**Issue by emma-nechamkin** [usds/justice40-tool#1850]
Getting a sense of whether we are getting "the right thing"
---
I've attached four spreadsheets, each of which have 25 randomly selected census tracts (as we uncover more bugs, I will blow this out and be a bit more targeted). This is for the first (of hopefully many!) rounds of QA that we do. 

Check that: 
- [ ] The values match up
- [ ] The colors are what you would expect given the numbers (e.g., the percentile for income is 66th so it's blue)
- [ ] If it's a donut hole at or above 50th percentile for low income, it is included
- [ ] If it should be a DAC, it is a DAC

**Comment by emma-nechamkin** [comment]
Here are some files to QA

[QA_column_details__0.xlsx](https://github.com/usds/justice40-tool/files/9419354/QA_column_details__0.xlsx)
[QA_column_details__1.xlsx](https://github.com/usds/justice40-tool/files/9419355/QA_column_details__1.xlsx)
[QA_column_details__2.xlsx](https://github.com/usds/justice40-tool/files/9419356/QA_column_details__2.xlsx)
[QA_column_details__3.xlsx](https://github.com/usds/justice40-tool/files/9419357/QA_column_details__3.xlsx)

**Comment by emma-nechamkin** [comment]
@vim-usds could you post a staging link when you have one? ❤️ 🥇

**Comment by emma-nechamkin** [comment]
[QA_column_details__0.xlsx](https://github.com/usds/justice40-tool/files/9462805/QA_column_details__0.xlsx)
[QA_column_details__1.xlsx](https://github.com/usds/justice40-tool/files/9462806/QA_column_details__1.xlsx)
[QA_column_details__2.xlsx](https://github.com/usds/justice40-tool/files/9462807/QA_column_details__2.xlsx)
[QA_column_details__3.xlsx](https://github.com/usds/justice40-tool/files/9462808/QA_column_details__3.xlsx)

**Comment by vim-usds** [comment]
1.0 staging link as of 8/31/22 3:30pm PT:

https://screeningtool-staging.geoplatform.gov/1829-3671e5/en/?flags=stage_hash=1822/5201f9e4578b09779b7d50f19a06cd005157dde4#3/33.47/-97.5

**Comment by vim-usds** [comment]
Each of the above xlsx files have been placed into shared doc called "Ground Truthing - 1.0 release"

**Comment by vim-usds** [comment]
@katherinedm-usds and/or @emma-nechamkin 

Are we still using the Ground Truthing document?
