### ISSUE TITLE
As a developer, I want my score python notebooks available as python files ready for some production ETL wizardry.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#186]
**Description**
Let's get those notebooks productionified! 

**Solution**
Convert the python notebooks we've been using for score drafting into python files that can be run in the docker containers.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**

**Comment by lucasmbrown-usds** [comment]
I'm assuming we'd want these to have appropriate testing of methods, too. And maybe a consistent base class for ETL to have a shared signature for all of our ETL scripts -- e.g., they have similar inputs and always produce output in the same format. But that's perhaps not necessary.

**Comment by switzersc-usds** [comment]
@esfoobar-usds What is the status here?

**Comment by esfoobar-usds** [comment]
This is accomplished with https://github.com/usds/justice40-tool/pull/260
