### ISSUE TITLE
Not all tribal boundaries are appearing in the map

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1873]
This [map](https://screeningtool.geoplatform.gov/en/?flags=tl#3/32.98/-95.84) shows all the tribal lands data.

In our current tribal tiles, we are only seeing tribal boundaries in [Oklahoma and Alaska](https://screeningtool-staging.geoplatform.gov/1861-4f2593/en/?flags=stage_hash=1822/1c4d3e4142d83bf86cec32b307c8d33b833549a3#7.48/35.537/-96.098). The theory is that one of the tribal dataset are missing. There are a total of 4 datasets that are being used to create the tribal lands map.

There are currently 3 datasets appearing on the tribal tiles:
- AlaskaNativeVillages
- BIA_TSA
- BIA_AIAN_Supplemental

The one that's missing from the tribal tiles is 
- BIA_National_LAR

See this for more information:
https://github.com/usds/justice40-tool/issues/1684

**Comment by esfoobar-usds** [comment]
PR #1874 fixed the issue: https://screeningtool-staging.geoplatform.gov/1829-3671e5/en/#3/33.47/-97.5

@BethMattern can you confirm?

**Comment by vim-usds** [comment]
@esfoobar-usds - LGTM! Nice fix!

This is what the map should look like with all tribal areas in:

![Screen Shot 2022-09-01 at 7 59 27 AM](https://user-images.githubusercontent.com/86254807/187946795-6a567923-db97-4800-a6c1-335f393e6d48.png)
