### ISSUE TITLE
As a developer, I want to add state, state abbrv, and county to my score CSV to help with data analysis and so that it can be accessible via the UI.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#188]
**Description**
In order to make the score CSV more useful during analysis and development, we want to add the state, state abbreviation, and county names. We know we also want this data in the CSV that we make available for download in the UI, which may pull from the score CSV S3 bucket directly or be generated from the geoJSON.

**Solution**
 Determine the state, state abbrv, and county from the census block group ID and add these three columns to the score CSV using pandas.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**
- [ ] The score CSV that lives (or will eventually live) on S3 has state, state abbreviation, and county name for every census block group row.

**Comment by esfoobar-usds** [comment]
Just to be super clear -- I would add 3 columns: state_name, state_abbrev and county_name to the score CSV

**Comment by switzersc-usds** [comment]
@esfoobar-usds sounds good. Card updated.

**Comment by switzersc-usds** [comment]
@esfoobar-usds is this data available in the Census TIGER files we're combing the CSV with for the geoJSON?

**Comment by esfoobar-usds** [comment]
Not sure, will start the research today.

**Comment by NatHillardUSDS** [comment]
As part of https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/132 , I found these:  https://www.census.gov/programs-surveys/geography/technical-documentation/records-layout/nlt-record-layouts.html  - these tables translate FIPS state/county codes to human-readable values. In particular this page from 2010 can help -- though its per-state: https://www.census.gov/geographies/reference-files/time-series/geo/name-lookup-tables.2010.html .

**Comment by esfoobar-usds** [comment]
I couldn't see one that maps to county name. I downloaded Alabama.

Here's the list of files:
Geographic Area	<entity>	Field Layout
Congressional districts	CD	STATEFP|DISTRICT|NAME|NAMELSAD
State legislative districts - upper	SLDU	STATEFP|DISTRICT|NAMENAMELSAD
State legislative districts - lower	SLDL	STATEFP|DISTRICT|NAME|NAMELSAD
Voting districts	VTD	STATEFP|COUNTYFP|DISTRICT|NAME|NAMELSAD
Elementary school districts	SDELM	STATEFP|DISTRICT|NAME|NAMELSAD
Secondary school districts	SDSEC	STATEFP|DISTRICT|NAME|NAMELSAD
Unified school districts	SDUNI	STATEFP|DISTRICT|NAME|NAMELSAD
Incorporated places	INCPLACE	STATEFP|PLACEFP|NAME|NAMELSAD
Census designated places	CDP	STATEFP|PLACEFP|NAME|NAMELSAD
American Indian / Alaska Native / Native Hawaiian areas	AIANNH	STATEFP|AIANNHCE|NAME|NAMELSAD
Minor Civil Divisions	MCD
STATEFP|COUNTYFP|COUSUBFP|NAME|NAMELSAD

Which one would be county?[https://app.zenhub.com/files/358242767/f91ae8c7-98b0-47b4-9921-40f7c6de8a0d/download](https://app.zenhub.com/files/358242767/f91ae8c7-98b0-47b4-9921-40f7c6de8a0d/download)

**Comment by NatHillardUSDS** [comment]
Ah sorry , you may have already found this, but it appears this particular link is typically used for a different purpose, namely getting text-based census place identifiers. 

In response to a similar question in the Census slack, they gave the "Census Gazetteer Files" as canonical, link [here](https://www.census.gov/geographies/reference-files/time-series/geo/gazetteer-files.2010.html). In particular the "Counties" file, linked [here](https://www2.census.gov/geo/docs/maps-data/data/gazetteer/Gaz_counties_national.zip) seems to be the one we need. 

There's also an API for querying these that I will likely use on the frontend, based on the same data:
```
https://api.census.gov/data/2010/acs/acs5?get=NAME&for=county:*
```

**Comment by esfoobar-usds** [comment]
The counties file looks like the winner! 🎉

**Comment by esfoobar-usds** [comment]
For referemce: the link is: https://www.census.gov/geographies/reference-files/time-series/geo/gazetteer-files.2010.html and look at the "Counties" section.

**Comment by esfoobar-usds** [comment]
Per @NatHillardUSDS[ I can use this endpoint](https://api.census.gov/data/2010/acs/acs5?get=NAME&for=county:*) to map the CBGs to counites.

**Comment by NatHillardUSDS** [comment]
Yep - chatted about this now as well but for future reference: data from that endpoint corresponds to the GEOID column of the gazeteer file - this is just STATE+COUNTY data from the endpoint

**Comment by switzersc-usds** [comment]
@esfoobar-usds What is the status here?

**Comment by esfoobar-usds** [comment]
This was left over and my next priority, after finishing https://github.com/usds/justice40-tool/pull/260
