### ISSUE TITLE
Use 2010 Decennial Census population data for island areas AS, MP, GU, and VI instead of showing as N/A in new "Tract Information" side panel

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#1882]
**Description**
In the new side panel as seen using the latest staging links, when navigating to any tract in island areas American Samoa, Northern Mariana Islands, Guam, or Virgin Islands, selecting the tract to see the side panel including the new "Tract Information" with Population, it's always N/A. Per @emma-nechamkin this is because we're getting population from ACS. We could pull population at least for the island areas from 2010 Decennial Census so that we can show something for population numbers here instead of N/A.

update - for these island areas we're already using the 2010 Decennial Census data, for instance for American Samoa we're already showing Low median income, Unemployment, Poverty, and High school degree non-attainment (screenshot below)

**Screenshots**
<img width="606" alt="image" src="https://user-images.githubusercontent.com/74208851/188759767-9a137661-95d3-4273-be54-68be5f17fa1d.png">

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/74208851/188783523-c7a8b577-58b3-4b0e-8d9f-0c6bf125439e.png">
 
<img width="691" alt="image" src="https://user-images.githubusercontent.com/74208851/188783565-c6d9eee5-9c89-456d-b078-9fbaba62c788.png">

**Comment by vim-usds** [comment]
@katherinedm-usds and/or @emma-nechamkin - is this already coming to the fronend?

if so, please list the signals where this can be found. If not, we'll prolly need a BE ticket and and FE ticket to rectify. TY for flagging this!

**Comment by katherinedm-usds** [comment]
@vim-usds thanks for that clarification - 2010 Decennial Census information is already being used for these island areas, and I added the info that at least I'm aware of to the original description for this ticket

**Comment by mattbowen-usds** [comment]
IN standup, we decided at this time, we'll do the racial demographic fields but not the age, given how ages are broken out
