### ISSUE TITLE
[SPIKE] As a screening tool user I want to see differences between my census block group's score and other scores/indices

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#190]
**Description**
Display existing data/indexes that have been used in the comparison tool in the census block group data panel on the map. Currently, this includes HUD R/ECAP and Cal EnviroScreen, and FEMA National Risk Index. 

New data sources will be added to the comparison tool - the CDC Social Vulnerability Index and Redlined communities - and these indicators should be able to be added to the UI when available.

Indicators to include:
Cal EnviroScreen - display the CalEnviroScreen Percentile
HUD R/ECAP - display whether or not a selected CBG is considered a R/ECAP currently and historically (recap 10, recap 00 and recap 90)
FEMA National Risk Index - display the FEMA NRI score for the county that the CBG is located in

**Tasks**

**Definition of "Done"**
- [ ] Users can see other indexes for the selected census block group in the UI in the CBG side panel
- [ ] Users can choose to visualize any of these indicators on the map / toggle between score and one of these indicators

**Comment by switzersc-usds** [comment]
Work in progress on this with open source partners, but we may want to scope more in for this in the upcoming sprint.

**Comment by BethMattern** [comment]
@katherinedm-usds I added some more context to the description. I think this feature should ultimately be available to any user of the CEJST, but if the team feels it should be behind a feature flag until it is fully implemented/vetted that is fine with me.

**Comment by switzersc-usds** [comment]
Closing this for now because we will make individual issues for each indicator/index/data point we want to show in the UI rather than having a big bucket issue.
