### ISSUE TITLE
Make sure Tribal overlap fields make it to downloads and tiles

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#1904]
#1900 created the fields and put the fields into `etl_score.py`, but didn't do the work to make sure they go into the Excel/CSV files and the tiles. To do so, we'll need confirmation from front-end and product teams what variables are needed and in what column order.

**Comment by vim-usds** [comment]
@mattbowen-usds and @lucasmbrown-usds extracting the FE requirements from this [thread](https://usds.slack.com/archives/C01LA9YLNE9/p1663278865776589):

> RE: side panel, so far I’m understanding that we’d like to communicate two new fields in the side panel:
> 1. The “count of number of Tribal areas” in the selected tract. This value will be number (integer) ranging from 0 to N. All tracts will have a this BE signal and it will always only be a number (integer). One name for this BE signal could be `TA_COUNT` for _tribal areas count_
> 2. The “percent of the tract that has tribal areas” in the selected tract. For tracts in CONUS this will be a number in the range of 0 to 1 , inclusive. For tracts in AK this will be  null . All tracts will have this BE signal and it will be either a number or a null value. One name for this BE signal could be `TA_PERC` for _tribal areas percent_. This number could/should (?) have 4 or 5 decimal places to allow for higher accuracy.
