### ISSUE TITLE
Investigate why BIA data has no Virginia Tribal Areas

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#1909]
**Description**
Perhaps these are just points in the dataset and are getting dropped from our ETL because they're just points? 

Their map lists Tribal areas: 

<img width="973" alt="Screen Shot 2022-09-20 at 11 43 35 AM" src="https://user-images.githubusercontent.com/25443529/191303654-6ce3b665-6f58-402a-b07e-6b6e5c78f87f.png">

**Comment by esfoobar-usds** [comment]
We don't drop anything on the ETL if they are points, FYI

**Comment by lucasmbrown-usds** [comment]
Confirmed with BIA that these are landless FRT.
