### ISSUE TITLE
As a stakeholder interested in the cumulative impact score, I want to see more states in the map, so that I can further analyze the score results.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#191]
**Description**
In order to get more feedback about the score formula, we need to add a few more states to the map:

A mix of:
- plains (rural) state - how about Montana
- southern state - how about Alabama
- NY
- NJ

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**
- [ ] USDS demo can show CEQ stakeholders these additional states on a map

**Comment by switzersc-usds** [comment]
Also Puerto Rico if possible.

**Comment by esfoobar-usds** [comment]
@NatHillardUSDS let me know if you need anything from me. Like I mentioned in a past meeting, you can restrict the states to generate locally using slicing in this [line](https://github.com/usds/justice40-tool/blob/main/score/scripts/generate_mbtiles.py#L37). Just pass the GEOID10 for the 4 states, i.e. `state_fips_codes = ['01', '05', '13', '14']` (note: not real codes)
