### ISSUE TITLE
As a repo contributor, I want to make sure my Python Notebooks are formatted using Black, so that we maintain a high standard of quality and consistency

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#192]
**Description**
We'd like to have autoformatting on our notebooks as well as the rest of our codebase.

**Solution**
Start using something like [jupyter-black](https://github.com/drillan/jupyter-black) or an alternative tool to use `black` for all of our Python notebooks. 

Edit: actually, `jupyter-black` looks like it needs to be run in the interface -- [`black-nbconvert`](https://pypi.org/project/black-nbconvert/) may be more appropriate for running as a pre-commit.

**Tasks**
* Implement an autoformatter for Jupyter notebooks
* Add the running of this autoformatter to existing pre-commit hooks

**Definition of "Done"**
* Jupyter notebooks are autoformatted to use black before being committed into the codebase

**Comment by switzersc-usds** [comment]
No longer relevant because we are moving away from Notebooks.
