### ISSUE TITLE
Update codebook to include new data indicators

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1927]
The codebook needs to be updated to include:

Projected flood risk
Projected wildfire risk 
Lack of plumbing
Lack of green space
Historic underinvestment 
Abandoned mine lands
Formerly used defense sites
Transportation barriers 
Leaking underground storage tanks 
Adjacency index
Number of Tribal areas within Census tract
Names of Tribal areas within Census tract
Percent of the Census tract that is within Tribal areas

**Comment by mattbowen-usds** [comment]
The codebook generates automatically from the configs that generate the various download files, so there's no work to do here.
