### ISSUE TITLE
There is no geojson with the Shapefiles download

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1931]
**Describe the bug**
Need to update the copy on the downloads page to not say that the Shapefiles download includes geojson files.

there’s no geojson in that download — it’s just a codebook and the shapefiles

**To Reproduce**
1. Go to 'downloads'
2. Scroll down to 'Shapefiles download'
3. See error

**Expected behavior**
Update the copy (see kameron if you have questions)

**Screenshots**
<img width="393" alt="Screen Shot 2022-09-27 at 1 04 44 PM" src="https://user-images.githubusercontent.com/77702996/192624654-1c6c73cf-efd1-4018-b003-8c00c91a2ee8.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger is this still an issue if you happen to know?

**Comment by KameronKerger** [comment]
yes, it still says there is a geojson included

**Comment by mattbowen-usds** [comment]
Vim merged this!
