### ISSUE TITLE
BUG - Adjacency index side panel state is wrong when income threshold isn't met

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1946]
https://screeningtool-staging.geoplatform.gov/1829-0d2477/en/?flags=stage_hash=1822/0f0d6db2d0bb90d67b7a04c53243094f3d8c8773#15.13/41.89043/-87.743106

census tract: 17031251700

This is NOT a DAC, but the side panel says Yes and has wording about the adjacency index being met. This one is not a DAC because the low-income percentile is not 50 or above.

**Comment by katherinedm-usds** [comment]
Here's an additional example census tract 5007021201, https://screeningtool-staging.geoplatform.gov/1829-0d2477/en/?flags=stage_hash=1822/0f0d6db2d0bb90d67b7a04c53243094f3d8c8773#12.25/36.17881/-94.55972, it's not a DAC but the panel says Yes
