### ISSUE TITLE
BUG: climate change category is blue but none of the thresholds are exceeded (except for low income)

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1953]
https://screeningtool-staging.geoplatform.gov/1829-0d2477/en/?flags=stage_hash=1822/0f0d6db2d0bb90d67b7a04c53243094f3d8c8773#11.72/34.5221/-101.7609

tract: 48437950300

Climate change is blue, but none of the burdens are exceeded. Is it possible it's blue because it does exceed the low income threshold?

This could also be an issue for categories with null values??

**Comment by emma-nechamkin** [comment]
i'm currently checking this out

**Comment by vim-usds** [comment]
@BethMattern - 
Confirmed that this was a FE Bug! great find Emma! This fix will go up in the next staging link
