### ISSUE TITLE
BUG: floating point issue with tribal % overlap

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1954]
https://screeningtool-staging.geoplatform.gov/1829-0d2477/en/?flags=stage_hash=1822/0f0d6db2d0bb90d67b7a04c53243094f3d8c8773#10.38/33.52/-116.0638

tract 06065045604

**Comment by emma-nechamkin** [comment]
(this should be solved with the new string from the ticket i just closed)
