### ISSUE TITLE
Bug - copy for imputed income hover needs a space between income and threshold

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1959]
![Screen Shot 2022-09-29 at 4.30.12 PM.png](https://images.zenhubusercontent.com/60b948a946294e688f91ba27/e921bb9c-527f-4ca1-9294-d4fd613ab100)

**Comment by KameronKerger** [comment]
this is also captured on another ticket but the second paragraph is wrong. they have an "adjusted low income threshold."
