### ISSUE TITLE
New Public Engagement page design

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1978]

**Comment by KameronKerger** [comment]
![Public_Calendar_v1 0_upcoming](https://user-images.githubusercontent.com/77702996/193912973-cc77a14d-2e81-4d7d-839c-a99e5e4fbbca.png)
![Public_Calendar_v1 0_upcoming_plus_post](https://user-images.githubusercontent.com/77702996/193912960-8d72ae7f-a457-4a9d-a5c2-0a31b47db093.png)

**Comment by vim-usds** [comment]
@KameronKerger - will need the SVGs (grayed out) for Oct 4th and 9th, please. TY

**Comment by vim-usds** [comment]
@KameronKerger - can we live with the gray buttons being yellow or blue. If you think it's nice to have, I can add the grey button versions.

Also I think we'll need 4 new links:
1. Youtube for beta and narwal
2. slides for beta and narwal

Do we need to create any BE tickets for this?

**Comment by KameronKerger** [comment]
![oct_9_off](https://user-images.githubusercontent.com/77702996/198364085-a74abab5-693e-4074-837d-362507827f0b.svg)
![oct_4_off_1](https://user-images.githubusercontent.com/77702996/198364102-517b2e91-af1f-404c-a21c-4fd7c744f8c4.svg)

**Comment by KameronKerger** [comment]
we should just remove the narwhal link and slides for now @vim-usds
