### ISSUE TITLE
Updates to the downloads page

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#1987]
**Describe the bug**
Downloads page needs an update for 1.0.

**To Reproduce**
1. Go to 'downloads page'
2. See error

**Expected behavior**
See screenshot

**Screenshots**
<img width="509" alt="Screen Shot 2022-10-05 at 2 29 36 PM" src="https://user-images.githubusercontent.com/77702996/194167731-210b5e88-2b00-428a-8d28-45158a912746.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
Download zip files need to have release notes added to the zip files and @KameronKerger  is working on getting these to @esfoobar-usds - #2007
