### ISSUE TITLE
Visual fixes needed

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#199]
List of visual fixes as discussed in a previous dev+design sync. See sheet for more details, but I've captured the short summaries as a checklist here:

- [ ] ~Remove layer toggle~
- [x] Update content in warning
- [x] Update Title
- [x] Add back warning icon in Alert
- [x] "Clickhere."
- [ ] ~Language Toggle~
- [x] Switch to light mode

**Comment by NatHillardUSDS** [comment]
In the dev-design sync earlier, we also discussed:
- About page updates
  - Grid updated on About page
  - What happens when you go full width? For now, let it be vis-a-vis column width, it's a beta, though it's a bit funky -- readdress closer to ship 
  - Remove language selector for now
