### ISSUE TITLE
Update score to account for 100% tribal overlap tracts (aka the great October 7th compromise of 2022)

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#1998]
1. New field called "Identified as disadvantaged due to tribal overlap" needs to be added. It will be True if the census tract overlaps with tribal boundaries by 99.5% or higher. This does not apply to the Alaska Native Villages.

2. If the "Identified as disadvantaged due to tribal overlap" field is True, then the "Definition N community, including adjacency index tracts" boolean field should be True.

3. There will be a new field called "Percentage of tract that is disadvantaged" and this will be 100% if "Definition N community, including adjacency index tracts" = True, will be 100% if the tract is 99.5% or higher inside tribal areas, and will be the partial % overlap number if the tract is partially inside tribal areas, and will be 0% of the tract is neither a DAC nor inside any tribal areas.

**Comment by BethMattern** [comment]
@mattbowen-usds I think "Identified as disadvantaged due to tribal overlap" should be the true/false field and "Percentage of tract that is disadvantaged" should be the new % field. Put the "identified as disadvantaged due to tribal overlap" after "Identified as disadvantaged based on neighbors and relaxed low income threshold only" and put the new % disadvantaged field after "Identified as disadvantaged"

**Comment by mattbowen-usds** [comment]
@vim-usds I came up with some names for us --- I can change them, but I figured something is better than nothing:

```
+    field_names.IS_TRIBAL_DAC: "SN_T",
+    field_names.PERCENT_OF_TRACT_IS_DAC: "SN_PERC",
```

**Comment by mattbowen-usds** [comment]
@BethMattern @emma-nechamkin asked that we make it clear "Percentage of tract that is disadvantaged" clear that it's area-based; could we make it like " Percentage of tract that is disadvantaged by area"?

**Comment by BethMattern** [comment]
@mattbowen-usds that sounds fine!
