### ISSUE TITLE
"Explore the Tool" page non-map modifications

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#200]
As discussed with dev+design:

- [x] Slim Alert about public beta and limited data resources
- [ ] ~Download Packet Card (non-functional just yet)~ Add when we implement the feature
- [x] Switch to light-mode
- [ ] ~Updated "Just Progress Communities" header and paragraph~ removing because of in progress name conversation

**Comment by NatHillardUSDS** [comment]
Notes from dev-design sync earlier:
* Look into subheader under "Just Progress" - "A climate and economic justice screening tool". if not possible, fall back to image. We need this text to be present, though Nat had doubts whether we could directly support a subheader at this location
