### ISSUE TITLE
Update the custom colors base map with the tribal data layers and fix the styling / zoom levels of the tribal names

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#2005]
**Is your feature request related to a problem? Please describe.**
Right now the tribal data is on the tribal basemap. For launch, we need to move it to the custom_colors base map and then make sure it is styled appropriately. We also need to update the visibility zoom level for the tribal data so that it behaves more consistently with the city names and other map labels. 

**Describe the solution you'd like**
Vim to port the data. Kameron to work on styling / zoom levels.

**Describe alternatives you've considered**
We started down this path on the tribal basemap but stopped when we realized it would most likely be work that needs to be repeated on the other basemap that we plan to use for 1.0.

**Additional context**
You can see the issue with the tribal names being shown at high zoom in this screenshot - 
<img width="880" alt="Screen Shot 2022-10-12 at 8 42 28 AM" src="https://user-images.githubusercontent.com/77702996/195388164-28f70109-90eb-4ed2-9bd3-a7f7963191b9.png">

**Comment by vim-usds** [comment]
Here are the styles on the combined Style (custom-colors + updated-tribal-names)

## Tribal areas styles
This includes the following data sources:
- BIA_TSA
- BIA_National_LAR
- BIA_Supplemental

### Area styles
Color: 
 - value: #758FB3
 - opacity: 100%

Pattern: 
- value: none

1px stroke:
- value: #1A447F
- opacity: 50%

## Tribal dots (AK)
This includes Alaska_Native_Villages

### Dot styles
Radius:
-  value: 5px

Color:
- value: #1A447F
- opacity: 100%

Blur:
- value: 0

Opacity:
- value: 0.3

Stroke Color:
- value: #1A447F
- opacity: 100%

Stroke Width:
- value: 1px

Stroke Opacity:
- value: 1
