### ISSUE TITLE
As an EVCM, I want the map to make sense at varying zoom levels so that I'm not confused.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#201]
**Description**
This card is about implementing different zoom-level based modifications to improve the UX of the map. It is dependent on the zoom spike. 

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**

**Comment by NatHillardUSDS** [comment]
Spike is now completed, but to implement these changes The Right Way we will need the data-side ticket, #209 . Setting as blocked on that now
