### ISSUE TITLE
Update EJScreen data and update all download files

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#2010]
The following  data will need to be refreshed using the new EJScreen data (still waiting on file)

Data refreshed from EJScreen (50 states and PR):

- Lead paint - 2016-2020
- Proximity to NPL (Superfund) sites - 2022
- Proximity to RMP facilities - 2022
- Proximity to hazardous waste facilities - 2022
- Leaking underground storage tanks - 2022

NEW data from EJScreen:
USVI
- Lead paint
- Proximity to NPL (Superfund) sites
- Proximity to RMP facilities
- Proximity to hazardous waste facilities
- Leaking underground storage tanks

Guam
- Lead paint
- Proximity to NPL (Superfund) sites
- Proximity to RMP facilities
- Proximity to hazardous waste facilities
- Leaking underground storage tanks

Samoa
- Lead paint
- Proximity to RMP facilities
- Leaking underground storage tanks

Marianna Islands
- Lead paint
- Leaking underground storage tanks

**Ensure that all new data fields are included in the download files**

**Comment by lucasmbrown-usds** [comment]
For the record, here are the fields that are in the 2021 file or the 2022 file, but not both: 

| 2021         	| Oct-22          	|
|--------------	|-----------------	|
| B_DISPSVI6   	|                 	|
| B_UNEMP      	|                 	|
| B_VULSVI6    	|                 	|
| B_VULSVI6PCT 	|                 	|
|              	| CNTY_NAME       	|
| DISPEO       	|                 	|
| DISPSVI6     	|                 	|
|              	| EXCEED_COUNT_80 	|
| P_DISPSVI6   	|                 	|
| P_UNEMP      	|                 	|
| P_VULSVI6    	|                 	|
| P_VULSVI6PCT 	|                 	|
| UNEMP        	| UNEMPLOYED      	|
| VULEO        	| VULEOPCT        	|
| VULEOPCT     	|                 	|
| VULSVI6      	|                 	|
| VULSVI6PCT   	|                 	|

**Comment by KameronKerger** [comment]
not doing EJScreen data refresh at this time
