### ISSUE TITLE
Update site copy to reflect new EJScreen data update

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#2012]
Explore the tool page:
American Samoa, Guam, the Northern Mariana Islands, and the U.S. Virgin Islands: For these U.S. territories, the tool uses the following data:
Workforce development: unemployment, poverty, low median income, and high school education
Legacy pollution: proximity to NPL (Superfund) sites (USVI and Guam), proximity to hazardous waste facilities (USVI and Guam), proximity to RMP facilities(USVI, Guam and Samoa), and leaking underground storage tanks (USVI, Guam, Samoa and Marianna Islands).
Sustainable housing: lead paint

Update the FAQ

Methodology & data page:
- Add territory names to appropriate data source cards
- Update source and date for lead paint - add “as compiled by EJScreen”
- Update dates:
Lead paint - 2016-2020
Proximity to NPL (Superfund) sites
Proximity to RMP facilities
Proximity to hazardous waste facilities 
Leaking underground storage tanks

**Comment by KameronKerger** [comment]
not moving forward with the updated EJScreen data at this time due to incompatibility at the census tract level
