### ISSUE TITLE
Remove LAR/TSA suffix/prefix from BIA shapefiles

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#2017]
## Purpose
Remove the unwanted suffix/prefix from the NAME field in the BIA data. 

This [ticket 1684](https://github.com/usds/justice40-tool/issues/1684) is being added for historical context. This ticket has both shapefiles in it's comment history:

1. [BIA LAR data](https://github.com/usds/justice40-tool/issues/1684#issuecomment-1255335934)
2. [Alaska Native Villages](https://github.com/usds/justice40-tool/issues/1684#issuecomment-1171470036)

The BIA data is made up of 3 sets of shapefiles as described by ticket 1684.

Once the NAME fields are cleansed, we can create a FE branch to test the new shapefiles. This means creating a new map style in MapBox, importing the various cleansed shapefiles and also created label layers for each shapefile. 

## Definition of done
Once the new map style shows tribal lands appropriately, we can consider this done.

**Comment by mattbowen-usds** [comment]
Updated files attached @vim-usds  --- lemme know if they actually work!
[BIA_National_LAR.zip](https://github.com/usds/justice40-tool/files/9786879/BIA_National_LAR.zip)
[AlaskaNativeVillages.gdb.zip](https://github.com/usds/justice40-tool/files/9786880/AlaskaNativeVillages.gdb.zip)

**Comment by mattbowen-usds** [comment]
@vim-usds updated filed for all layers attached :smile: 
[BIA_TSA.zip](https://github.com/usds/justice40-tool/files/9789029/BIA_TSA.zip)
[BIA_AIAN_Supplemental.zip](https://github.com/usds/justice40-tool/files/9789030/BIA_AIAN_Supplemental.zip)
[BIA_National_LAR.zip](https://github.com/usds/justice40-tool/files/9789031/BIA_National_LAR.zip)
[AlaskaNativeVillages.gdb.zip](https://github.com/usds/justice40-tool/files/9789032/AlaskaNativeVillages.gdb.zip)

**Comment by vim-usds** [comment]
@mattbowen-usds - would be open to seeing if you can import these zip files and get them going on MapBox? Totally OK if it's not your cup of tea.

In case you are, the steps are:
1. Get MapBox creds. Under the user icon, click on Studio. You will list a list of _Map Styles_.
3. Create a new Map Style that duplicates the `streets-with-tribal` Map Style (we did this together and it's called `streets-with-tribal-copy`). This allows to do anything we want without effecting any of the maps in our existing environments.
4. Open the newly created Map Style. 
5. Add a new layer (plus Icon). Import _one_ of your newly created shapefiles. Feel free to rename these to be more meaningful. Also the Map Style URL is cryptic and it would be awesome to have these be less cryptic (there may not be a way around this and this is not super important).
6. Copy the styles of this layer from the original `streets-with-tribal`. Right now we are manually doing this, however it would be awesome to see if there was some way to export all the styles and then import them into another style. Maybe some kinda of JSON export/import feature? Also you can use the existing layers to see how the new layers should be configured.
7. Add a new layer, this time for the labels. 
8. Repeat steps 4 - 6 for each new shapefile

**Comment by mattbowen-usds** [comment]
@vim-usds I gave it a go on the streets-with-tribal-copy we made together --- give it a look!

**Comment by vim-usds** [comment]
@mattbowen-usds - awesome work. I appreciate you!
