### ISSUE TITLE
Need to add a banner for when version 1.0 is released

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#2019]
**Is your feature request related to a problem? Please describe.**
Need to add a banner under the top header to draw people's attention to the fact that the site is out of beta and is now version 1.0

**Describe the solution you'd like**
I'll do a design

**Describe alternatives you've considered**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger - thanks!

**Comment by vim-usds** [comment]
Waiting for Sharmila on this

**Comment by KameronKerger** [comment]
will need to have two strings:
one for quiet launch and one for launch launch
quiet launch = something like "CEQ's press release coming soon"

**Comment by KameronKerger** [comment]
screenshot of final version copy
![Screen Shot 2022-11-10 at 8.04.23 AM.png](https://images.zenhubusercontent.com/60a81149dee122a5d67208e5/f9685810-68a8-4ea7-8fe0-2d72aed7f787)

final copy:
Version 1.0 of the tool is now available
The Council on Environmental Quality (CEQ) made the version 1.0 of the tool available on xx/xx/xx. For more information about the improvements to the tool, read CEQ’s [press release]([press release once available]).

temp copy:
Version 1.0 of the tool is now available
The Council on Environmental Quality (CEQ) made the version 1.0 of the tool available on xx/xx/xx. For more information about the improvements to the tool, CEQ’s press release will be coming soon.
