### ISSUE TITLE
As an EVCM, I want to see information about a given census block group so that I can understand the data about this area.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#202]
**Description**
We should show per-block group statistics in the tool. UX things to consider:
- Hover Behavior
- Click Behavior
- Indicator callout
- Expandable list

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**
- [ ] Show the test score and indicator values for any census block group on hover or click (UX determined by design)

**Comment by NatHillardUSDS** [comment]
From Dev-design sync earlier:
* Hover Behavior
    * none at this time
* Click Behavior
    * Ideally: create a side bar from the right
    * If sidebar is not possible, better to have a popup than to have the entire map shrinking. Note though that the popup was initially deemed unacceptable as it blocks the surrounding context 

* Indicator callout
    * Indicators should be categorized into "environmental" and "socioconomic"
    * All current indicators should be included

* Expandable list
    * Need to discuss further the exact interaction behavior

Other:
  * Include X to dismiss, or allow user to click on other block groups

**Comment by NatHillardUSDS** [comment]
![Screen Shot 2021-06-22 at 5 24 48 PM](https://user-images.githubusercontent.com/72811320/123001542-d783a100-d37e-11eb-82f3-ab8ce578bec9.png)
