### ISSUE TITLE
fill-color interpolation not working for mapbox style

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#205]
**Describe the bug**
We are attempting at the moment to use the Open-Layers-Mapbox-Style [extension](https://github.com/openlayers/ol-mapbox-style) to Open Layers which would allow for easier tile styling.

As part of this effort, we created the attached style json, which critically contains the following portion:
```javascript
      'paint': {
        'fill-color': [
          'interpolate',
          [
            'linear',
          ],
          [
            'get',
            'lowincpct',
          ],
          0,
          'white',
           1,
           'rgb(0,94,162)'
        ],
        'fill-opacity': 0.5,
      },
```

This does not appear to produce the correct behavior, however, when run against a local mbtiles server - instead of coloring based on the selected value, all tiles render grey.  

Interestingly, this also seems to impact mapbox styles when used directly with vanilla mapbox, so this may be related to our tiles themselves? It impacts both the below mbtiles db as well as mvt flat-files as seen in our S3 at the url http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/nm/{z}/{x}/{y}.pbf.

**To Reproduce**
1. Run `docker run --rm -it -v ${PWD}/tiles:/data -p 8080:80 klokantech/tileserver-gl` against the attached mbtiles db
2. Run `npx live-server` against the attached html and js files
3. Observe that tiles are all grey, as opposed to colored correctly.

**Expected behavior**
Similar styling worked against a local pg_tileserv instance - (ref [here](https://github.com/usds/justice40-tool/blob/client_perf/client/mapbox.js#L14)) but this does not appear to work against this particular dataset. 

**Screenshots**
![Screen Shot 2021-06-22 at 10.16.54 AM.png](https://images.zenhubusercontent.com/6091a54c180d4758f3eedc40/314ef5b0-88fa-4567-b9c5-f66c7154e748)

**Comment by NatHillardUSDS** [comment]
Github threw an error when I attempted to upload these, here are alternative links which should work:
1. [mbtiles](https://usds-geoplatform-justice40-website.s3.amazonaws.com/example/block2010.mbtiles)
2. [index.html](https://usds-geoplatform-justice40-website.s3.amazonaws.com/example/index.html)
3. [main.js](https://usds-geoplatform-justice40-website.s3.amazonaws.com/example/main.js)

For reference here is the full js:
```js
mapboxgl.accessToken = '{YOUR TOKEN}';
var map = new mapboxgl.Map({
    center: [-86, 32],
    container: 'map',
    style: 'mapbox://styles/mapbox/light-v10',
    zoom: 11
});

var popup = new mapboxgl.Popup({
    closeButton: false,
    closeOnClick: false,
    maxWidth: 600
});

map.on('load', function() {

    var layers = [{
        "id": "blocks",
        "source": {
            "type": "vector",
            "tiles": [
                "http://localhost:8080/data/block2010/{z}/{x}/{y}.pbf"
            ],
        },
        "source-layer": "cbg2010",
        "minzoom": 8,
        "maxzoom": 18,
        "type": "fill",
        "layout": {"visibility": "visible"},
        paint: {
            "fill-color": [
                "interpolate",
                ["linear"],
                ["get", "score_a_percentile"],
                0,
                "white",
                1,
                "rgb(0,94,162)"
            ],
            "fill-opacity": 0.5
            }
    }];


    layers.forEach((layer) => {
        map.addLayer(layer);
    });

    map.addControl(new mapboxgl.NavigationControl());
    var inspect = new MapboxInspect({
      showInspectMap: true,
      showInspectButton: false
    });
    map.addControl(inspect);
});
```

**Comment by mikelmaron** [comment]
@NatHillardUSDS I think the issue is that the `score_a_percentile` property is a string, not a number.

Try this style and see if it helps. Eventually, would recommend building the GeoJSON so that numeric properties are typed appropriately.

<pre>
[
  "interpolate",
  ["linear"],
  ["to-number", [
    "get",
    "score_a_percentile"
  ]],
  0,
  "white",
  1,
  "rgb(0,94,162)"
]
</pre>

**Comment by NatHillardUSDS** [comment]
Aha! That was exactly it. Thank you @mikelmaron !

**Comment by NatHillardUSDS** [comment]
Though the above workaround works, the solution for this ended up being that we switched from running SQL directly on geoJSON, which as Mikel notes would require us to use explicit casting to set types (as outlined [here](https://gdal.org/user/ogr_sql_dialect.html#changing-the-type-of-the-fields)), to using `tile-join` instead, which seems to handle typing correctly. Closing as resolved with the `tile-join` method
