### ISSUE TITLE
Figure out what is happening with the counties for American Samoa

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#2050]
**Describe the bug**
America Samoa is missing the territory name in the beta spreadsheet (I think). can we make sure this doesn't happen for 1.0? beta was missing the population count but this appears to be fixed for 1.0. the other issue is that neither version has counties which apparently are available for the territory. 
https://en.wikipedia.org/wiki/Outline_of_American_Samoa

**To Reproduce**
1. Go to 'AS'
2. Click on 'a census tract'
3. Scroll down to 'county info'

**Expected behavior**
Populations and counties should appear for American Samoa, both on the front and back end. The territory name should also appear in the spreadsheet.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mattbowen-usds** [comment]
I looked quickly in our code, and we use the a census gazetteer file for our county names. It doesn't include AS, nor do any other obvious files in that gazetteer directory :/

This is our counties file: https://www2.census.gov/geo/docs/maps-data/data/gazetteer/Gaz_counties_national.zip

**Comment by KameronKerger** [comment]
closing, not currently supported.
