### ISSUE TITLE
Update tribal strings for the side panel

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#2054]
**Describe the bug**
Need to finalize with Sharmila today. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
Will be meeting with Kameron on this

**Comment by vim-usds** [comment]
Updated on copy summary sheet

**Comment by vim-usds** [comment]
Working on making test cases for each string use case. 

There are like 18 use cases. It
