### ISSUE TITLE
Is there anything wrong with HRS_ET?

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#2058]
**Describe the bug**
@KameronKerger has a hunch that maybe HRS_ET may be in error as there were some tracts in her neighborhood that were historically redlined however now they are not.

@KameronKerger to fill in more here.

**Comment by KameronKerger** [comment]
I've done some ground truthing and I am less concerned that something happened on the backend to the data. I do however still have concerns about when it is not a yes or no. I will try to bury them deep in my psyche.
