### ISSUE TITLE
There is one tribal LAR area in Alaska - it is currently reading as 1 point it has a land boundary so we need a percentage calculation

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#2060]
**Describe the bug**
#9.42/55.1438/-131.5693 in Alaska is a LAR. It should have a percentage calculation in addition to it's points count.

**To Reproduce**
1. Go to 'Explore the map hashtag9.42/55.1438/-131.5693'
2. Click on 'the census tract on Annette Island'
3. See error

**Expected behavior**
There should be a LAR percentage calculation.

**Screenshots**
<img width="1149" alt="Screen Shot 2022-11-04 at 10 28 35 AM" src="https://user-images.githubusercontent.com/77702996/200038751-86b88bc1-3bf2-4953-ab8f-da117ac8c88b.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mattbowen-usds** [comment]
There's some logic I think that decides this --- I'll look at it tomorrow to see how complex it will be to solve.

**Comment by mattbowen-usds** [comment]
I looked at this, and on the backend for this tract, TA_PERC is 0.94 and TA_COUNT_AK is 1.0, so the backend is sending the correct signals. Vim and I are talking about the correct solution

**Comment by vim-usds** [comment]
This is the only tract in AK that has both a TA_COUNT_AK and TA_PERC. The assumption is that TA_PERC should take precedence. Is that correct @KameronKerger ?

**Comment by KameronKerger** [comment]
It is visually a PERC on the map so it should be a PERC.

From: Vim ***@***.***>
Reply-To: usds/justice40-tool ***@***.***>
Date: Tuesday, November 8, 2022 at 11:42 AM
To: usds/justice40-tool ***@***.***>
Cc: "Kerger, Kameron N. EOP/OMB" ***@***.***>, Mention ***@***.***>
Subject: Re: [usds/justice40-tool] There is one tribal LAR area in Alaska - it is currently reading as 1 point it has a land boundary so we need a percentage calculation (Issue #2060)


This is the only tract in AK that has both a TA_COUNT_AK and TA_PERC. The assumption is that TA_PERC should take precedence. Is that correct @KameronKerger<https://github.com/KameronKerger> ?

**Comment by vim-usds** [comment]
@KameronKerger thank you!

**Comment by vim-usds** [comment]
@KameronKerger - let's talk about this this afternoon

**Comment by vim-usds** [comment]
See highlighted fields in spreadsheet:

![Screen Shot 2022-11-08 at 2 28 47 PM](https://user-images.githubusercontent.com/86254807/200689797-49360e2b-e68e-44b8-a5c3-24e0fb0332ac.png)

**Comment by vim-usds** [comment]
And this one:

![Screen Shot 2022-11-08 at 2 35 52 PM](https://user-images.githubusercontent.com/86254807/200690912-13bc2869-5b12-4ec7-90c7-9a6095432635.png)
