### ISSUE TITLE
The pdf download is broken

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#2064]
**Describe the bug**
(https://static-data-screeningtool.geoplatform.gov/data-pipeline/data/score/downloadable/draft-communities-list.pdf)
gets an access denied error

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>KN29B5DTW8J6XGJF</RequestId>
<HostId>
As5AkYnRCcBT4ny/YiWNN1xSE0SzIBYyWxVIsXeHJ6OWdMgkK1FUC1sQ60U1RYzS+zqPjGHQqak=
</HostId>
</Error>

**To Reproduce**
1. Go to 'Downloads'
2. Click on 'how to use the communities list.pdf.'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[KM add] Just wanted to note that this occurs on personal or OMB device, and that it's only this short PDF that has the issue, other files download fine.

**Comment by vim-usds** [comment]
What link are they using when they get this error?

**Comment by katherinedm-usds** [comment]
@vim-usds https://static-data-screeningtool.geoplatform.gov/data-pipeline/data/score/downloadable/draft-communities-list.pdf
<img width="336" alt="image" src="https://user-images.githubusercontent.com/74208851/200389652-2fd9896b-08f9-4364-86d3-06df9b05845b.png">

**Comment by mattbowen-usds** [comment]
@vim-usds I think the link is https://static-data-screeningtool.geoplatform.gov/data-pipeline/data/score/downloadable/Draft_Communities_List.pdf for v1

**Comment by mattbowen-usds** [comment]
@vim-usds other version of this URL https://static-data-screeningtool.geoplatform.gov/data-versions/beta/data/score/downloadable/draft-communities-list.pdf

**Comment by vim-usds** [comment]
@mattbowen-usds - thanks for helping me talk this through!

**Comment by vim-usds** [comment]
@katherinedm-usds and @KameronKerger - should be fixed!

**Comment by KameronKerger** [comment]
Can confirm, is fixed.

From: Vim ***@***.***>
Reply-To: usds/justice40-tool ***@***.***>
Date: Monday, November 7, 2022 at 2:22 PM
To: usds/justice40-tool ***@***.***>
Cc: "Kerger, Kameron N. EOP/OMB" ***@***.***>, Mention ***@***.***>
Subject: Re: [usds/justice40-tool] The pdf download is broken (Issue #2064)


@katherinedm-usds<https://github.com/katherinedm-usds> and @KameronKerger<https://github.com/KameronKerger> - should be fixed!
