### ISSUE TITLE
Downloadable links for 4 PDF files 

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#2076]
## Description
Add the following files to downloadable:

@KameronKerger :

###  tool comparison chart
- link on S3 ✅ 
- link in FAQ ❓  
### interim guidance 
- https://www.whitehouse.gov/wp-content/uploads/2021/07/M-21-28.pdf ✅ 
- link in FAQ ❓ 
- remove this
### addendum guidance 
- external link - after launch 
- where in FAQs should this go? ❓
### Instructions 
- link is on S3 ✅ 
- where in FAQs should this go? ❓
### blog post PR - whitehouse.gov blog post (link to banner and FAQs) 
- no link ❓
- where in banner should this go? ❓
- where in FAQs should this go? ❓

**Comment by vim-usds** [comment]
@mattbowen-usds - [no urgent] is my understanding correct that files need to be placed into the the `files` directory and then a certain GHA will place it in the `downloads` folder for public (and website) consumption?

**Comment by mattbowen-usds** [comment]
@vim-usds yup, accurate!

**Comment by vim-usds** [comment]
comparison chart in FAQs
addendum and instructions in FAQs

**Comment by KameronKerger** [comment]
here is the current link to the interim guidance
https://www.whitehouse.gov/wp-content/uploads/2021/07/M-21-28.pdf

**Comment by katherinedm-usds** [comment]
[tool_comparison_chart.pdf](https://github.com/usds/justice40-tool/files/10006410/tool_comparison_chart.pdf)
here's an empty PDF if it helps @vim-usds

**Comment by vim-usds** [comment]
@mattbowen-usds - I'm working on getting my access back to AWS.

I'm assuming they should be placed in the `files` directory and then we should re-run the `previous version GHA` to get them to show up in the downloads folder right?

**Comment by vim-usds** [comment]
@KameronKerger - should we keep the file name as `M-28-28.pdf`

**Comment by vim-usds** [comment]
> @mattbowen-usds - [no urgent] is my understanding correct that files need to be placed into the the `files` directory and then a certain GHA will place it in the `downloads` folder for public (and website) consumption?

Thanks @mattbowen-usds 

Realizing I asked the same question twice, here's the updated question:

Can you point me to BE code of how the files get from the files directory to the downloadable directory and if it's a GHA, which one that is? Thx!

**Comment by mattbowen-usds** [comment]
@vim-usds this is the magic line for production: https://github.com/usds/justice40-tool/blob/main/.github/workflows/create-score-version.yml#L73

**Comment by KameronKerger** [comment]
1. tool comparison chart (blank file for now link to PDF in FAQ) ✅
2. interim guidance (link) - use existing link https://www.whitehouse.gov/wp-content/uploads/2021/07/M-21-28.pdf
3. addendum guidance (link) - will need to wait for OMB
4. instructions (blank file for now link to PDF in FAQ)
5. update blog post PR - whitehouse.gov blog post (link to banner and FAQs) - will need to wait for CEQ

**Comment by vim-usds** [comment]
> @vim-usds this is the magic line for production: https://github.com/usds/justice40-tool/blob/main/.github/workflows/create-score-version.yml#L73

Thanks @mattbowen-usds - would you agree that placing the files in the `files` directory and the downloadable directory _manually_ allows us to avoid having to run the GHA? Or do you feel it's better to re-run the GHA? 

The only advantage I'm seeing with the above _manual_ approach is that we don't have to wait for the GHA to run to get the files into the downloadable directory. Are you seeing other tradeoffs?

it give that we have new files to add?

**Comment by vim-usds** [comment]
@KameronKerger - which FAQ do the instructions go with?

**Comment by KameronKerger** [comment]
Q1

**Comment by KameronKerger** [comment]
it and the addendum are currently struck text where they would eventually go. honestly, I don't think they are going to have these ready in time so maybe focus on something else.

**Comment by KameronKerger** [comment]
the instructions and memo (link) are now ready to be added to the site copy - About page and FAQs.
https://static-data-screeningtool.geoplatform.gov/data-versions/1.0/data/score/downloadable/CEQ-CEJST-Instructions.pdf
https://www.whitehouse.gov/wp-content/uploads/2023/01/M-23-09_Signed_CEQ_CPO.pdf

**Comment by KameronKerger** [comment]
About page (note: just the placement of the links - the content in the surrounding paragraphs may have changed)
In January of 2020, President Biden issued Executive Order 14008. The order directed the Council on Environmental Quality (CEQ) to develop a new tool. This tool is called the Climate and Economic Justice Screening Tool. The tool has an interactive map and uses datasets that are indicators of burdens. The tool uses the datasets to identify which communities are experiencing a large share of these burdens. These are the communities that are disadvantaged because they are overburdened and underserved.
Federal agencies will use the tool’s identification of disadvantaged communities so that they can benefit from covered programs included in the Justice40 Initiative. The Justice40 Initiative seeks to deliver 40% of the overall benefits of investments in climate, clean energy, and related areas to disadvantaged communities.

Federal agencies should also use the following:
●       Memorandum on Using the CEJST for the Justice40 Initiative
●       Instructions to Federal Agencies on Using the CEJST

CEQ will update the tool each year based on public feedback, research, and the availability of new data. The current version of the tool is version 1.0.

**Comment by KameronKerger** [comment]
FAQs page (note: just the placement of the links - the content in the surrounding paragraphs may have changed)
NEW  Q: What is the Climate and Economic Justice Screening Tool (CEJST)?
The CEJST is a critical component of the Biden-Harris Administration’s historic commitment to addressing environmental justice. In Executive Order 14008 on Tackling the Climate Crisis at Home and Abroad, President Biden directed the White House Council on Environmental Quality (CEQ) to develop a geospatial mapping tool to identify disadvantaged communities that face burdens. The tool has an interactive map and uses datasets that are indicators of burdens.
Federal agencies will use the tool for the Justice40 Initiative. It will help them identify disadvantaged communities that should receive 40% of the overall benefits of programs included in the Justice40 Initiative. The Justice40 Initiative seeks to deliver 40% of the overall benefits of investments in climate, clean energy, and other related areas to disadvantaged communities.

Other useful links for Federal agencies:
● Memorandum on Using the CEJST for the Justice40 Initiative
● Instructions to Federal Agencies on Using the CEJST

The public can find communities of interest and provide feedback. This feedback will be used to improve the tool.
