### ISSUE TITLE
PR (Puerto Rico) is not behaving as expected

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#2083]
**Describe the bug**
FE
There are extra and missing burdens for PR.
Need to add the climate change category and the projected flood risk  burden
Need to add the transportation category and both related burdens diesel, traffic, and transportation burdens
Need to add wastewater category and both leaking underground storage tanks and wastewater discharge
Housing is missing lack of indoor plumbing
Need to remove abandoned mine lands and FUDS

BE
Need to remove the linguistic isolation percent column fields

**To Reproduce**
1. Go to 'PR'
2. Click on 'a census tract'
3. Open side panel 'x'
4. See errors

**Expected behavior**

**Screenshots**
<img width="247" alt="Screen Shot 2022-11-15 at 2 52 56 PM" src="https://user-images.githubusercontent.com/77702996/202041740-30d3e82f-2d37-44e9-aed8-09e8f8c78e37.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@mattbowen-usds - are you able to join the stand up tomorrow at 10:30 PST? I have some questions on this and AWS stuff too

**Comment by vim-usds** [comment]
@KameronKerger - we can work on this one together, should take about 10 mins to get the correct categories and burdens in

**Comment by vim-usds** [comment]
Seems like the BE signal that is used for highlighting of the housing category (blue) doesn't always show up as true even tho the burdens are met (unemploy and poverty):

http://localhost:8000/en/#11.31/18.2503/-66.5833

**Comment by mattbowen-usds** [comment]
@KameronKerger re "Need to remove the linguistic isolation percent column fields" --- like do we need to remove that field in general everywhere? Or just null it for PR tracts?

**Comment by KameronKerger** [comment]
Just for PR please @Matt ***@***.***>. Emma already removed the percentiles and having the percentages there is confusing?
note: this is not the most important thing.

From: Matt Bowen ***@***.***>
Reply-To: usds/justice40-tool ***@***.***>
Date: Wednesday, November 16, 2022 at 6:29 AM
To: usds/justice40-tool ***@***.***>
Cc: "Kerger, Kameron N. EOP/OMB" ***@***.***>, Mention ***@***.***>
Subject: Re: [usds/justice40-tool] PR (Puerto Rico) is not behaving as expected (Issue #2083)


@KameronKerger<https://github.com/KameronKerger> re "Need to remove the linguistic isolation percent column fields" --- like do we need to remove that field in general everywhere? Or just null it for PR tracts?

**Comment by mattbowen-usds** [comment]
For any dev's future reference, the previous removal for PR is in https://github.com/usds/justice40-tool/pull/1750
