### ISSUE TITLE
Something odd is happening with the spacing on the Tribal Nations note

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#2084]
**Describe the bug**
The spacing is off on the note on Tribal Nations (see screenshots / below the map) - browsers are safari and chrome

**To Reproduce**
1. Go to 'Explore the map'
2. Scroll down to 'a note on Tribal Nations'

**Expected behavior**
The spacing should be fixed.

**Screenshots**
<img width="621" alt="Screen Shot 2022-11-15 at 3 00 48 PM" src="https://user-images.githubusercontent.com/77702996/202043043-01a191d7-d5c4-4335-a98e-680718696f12.png">
<img width="585" alt="Screen Shot 2022-11-15 at 3 00 39 PM" src="https://user-images.githubusercontent.com/77702996/202043045-03b09d9b-c3fb-4cbb-887c-2a567f8f6984.png">

**Desktop (please complete the following information):**
 - **Browser [e.g. chrome, safari]**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger - this is a known bug, when the linked text becomes too long, it doesn't wrap anymore.  One solution is to reduce how much of the text is linked.
