### ISSUE TITLE
The AVN points side panel needs updating when donut = would have been yes but... and when donut = yes and income is above

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#2085]
**Describe the bug**
There should be two paragraphs in the side panel when donut = yes. It should be a but when adjusted income is not met (in one case it is not known) and when donut = yes and adj income is above. The paragraph about the AVNs should move the second slot.
#5.54/62.423/-163.239
#7.38/64.67/-165.524

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="238" alt="Screen Shot 2022-11-15 at 3 03 47 PM" src="https://user-images.githubusercontent.com/77702996/202043521-02754035-7109-4f35-9387-8514f44b50da.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
first para and sec para is highlighted in sheet

**Comment by vim-usds** [comment]
Should be in the latest staging link
