### ISSUE TITLE
downloads page needs some updates

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#2087]
**Describe the bug**
I'm going to be a pain and ask that the top part be moved under the Version 1.0 heading. purposefully retaining some older copy here. 

The xls and the csv links should be zip files. see https://github.com/usds/justice40-tool/issues/1679. need to update the file the parentheticals to say:

(.xlsx with codebook ##.#MB unzipped)
(.csv with codebook ##.#MB unzipped)

Have an email out to Sharm to ask what to do about the tsd link.

the list of communities is now 704KB - I haven't put the links in but I will update the ticket after if the size changes.

**To Reproduce**
1. Go to 'Downloads'
3. See error

**Expected behavior**

**Screenshots**

<img width="483" alt="Screen Shot 2022-11-16 at 3 14 37 PM" src="https://user-images.githubusercontent.com/77702996/202315023-ff67ec46-4eea-4458-864e-221b63c72827.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
On the previous versions page, both links have a zip file that contains an README.beta.md file that we no longer need?

**Comment by vim-usds** [comment]
![Screen Shot 2022-11-17 at 11 32 05 AM](https://user-images.githubusercontent.com/86254807/202541897-d13ae23a-dfd9-4e68-8063-bedbb462d123.png)
