### ISSUE TITLE
Upgrade packages on narwhal

### ISSUE THREAD

**Issue by mattbowen-usds** [usds/justice40-tool#2113]
Safety is failing, so we can't merge narwhal. Fix it.

**Comment by travis-newby** [comment]
Is this still a thing? @mattbowen-usds @vim-usds

**Comment by mattbowen-usds** [comment]
Narwhal is now main, so as long as main is up to date, you’re good.

From: Travis Newby ***@***.***>
Reply-To: usds/justice40-tool ***@***.***>
Date: Wednesday, March 8, 2023 at 8:56 AM
To: usds/justice40-tool ***@***.***>
Cc: "Bowen, Matthew R. EOP/OMB" ***@***.***>, Mention ***@***.***>
Subject: Re: [usds/justice40-tool] Upgrade packages on narwhal (Issue #2113)


Is this still a thing? @mattbowen-usds<https://github.com/mattbowen-usds> @vim-usds<https://github.com/vim-usds>

**Comment by travis-newby** [comment]
Closing this as fixed.
