### ISSUE TITLE
There are a few tracts / places where the values over the 90th percentile are not showing as blue

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#2119]
**Describe the bug**
I was doing some ground truthing on the lack of green space so I happened upon these tracts where values over the 90th percentile are not appearing as blue.

#15.04/34.02823/-118.31329 not showing blue at 91st percentile
 - tract # 06037222001

#12.44/34.12115/-118.11633 not showing blue at 94th percentile
- tract # 06037464100

#14.28/34.09612/-118.13079 not blue at 94th

**To Reproduce**
1. Go to 'explore the map'
2. Click on 'census tract'
3. Scroll down to 'values over the 90th percentile'

**Expected behavior**
All values over the 90th percentile should appear blue.

**Screenshots**
<img width="224" alt="Screen Shot 2022-12-06 at 2 30 25 PM" src="https://user-images.githubusercontent.com/77702996/206245492-518712dd-8372-4ccf-8673-570453b2fbfa.png">
<img width="229" alt="Screen Shot 2022-12-06 at 2 50 03 PM" src="https://user-images.githubusercontent.com/77702996/206245494-87f9675c-62b0-4d82-8665-a6cde3a9f85f.png">
<img width="199" alt="Screen Shot 2022-12-06 at 2 57 11 PM" src="https://user-images.githubusercontent.com/77702996/206245496-34b88afe-b148-4e87-a303-5b23365c7d50.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KameronKerger** [comment]
did some more digging into this

on lack of green space, I believe the front end is showing the wrong signal. it is using "is above + low income" when it should just be "is above" 
<img width="88" alt="Screen Shot 2022-12-23 at 9 31 02 AM" src="https://user-images.githubusercontent.com/77702996/209378092-45402778-e776-4df3-a865-bc08ea7b50d9.png">
<img width="948" alt="Screen Shot 2022-12-23 at 9 20 35 AM" src="https://user-images.githubusercontent.com/77702996/209378431-394ae163-0cd9-4e5f-9f8a-1371c7136cc7.png">
<img width="950" alt="Screen Shot 2022-12-23 at 9 17 49 AM" src="https://user-images.githubusercontent.com/77702996/209378437-e17b20dd-8acd-4bb6-9152-2d24f1e21066.png">

on lead paint, I think the signal is correct but is it not working correctly. this column is also missing from the spreadsheet.
<img width="88" alt="Screen Shot 2022-12-23 at 9 31 02 AM" src="https://user-images.githubusercontent.com/77702996/209379047-f445b634-8fa0-44c1-affc-c8a8ed0d7ebf.png">

**Comment by KameronKerger** [comment]
<img width="1456" alt="Screen Shot 2023-01-05 at 11 44 50 AM" src="https://user-images.githubusercontent.com/77702996/210866817-19bcc67e-a692-48a7-9f46-7e4d2038a45b.png">

**Comment by lucasmbrown-usds** [comment]
Ok, looking at @KameronKerger 's very helpful analysis, 

1. It appears the front-end needs to be updated to change the field that is used to determine whether the "Lack of green space" in the sidebar is highlighted blue. It appears that it might be using the field: 

> "Greater than or equal to the {PERCENTILE}th percentile for share of the tract's land area that is covered "
    "by impervious surface or cropland as a percent and is low income?"

when it should just be using the field: 

> "Greater than or equal to the {PERCENTILE}th percentile for share of the tract's land area that is covered "
    "by impervious surface or cropland as a percent?"

I fixed this in line data/data-pipeline/data_pipeline/etl/score/constants.py:356. 

2. This appears to be some wonkiness due to the lead paint indicator. The lead paint indicator is actually two things: 

A. The percentile of houses built pre-1960s, and 
B. If the tract has median home values <90th percentile. 

I've created a new indicator that shows the percentile of houses built pre-1960s if and only if the tract has median home values <90th percentile. 

It's called `LEAD_PAINT_HOUSE_VALUE_FIELD_PCTILE` aka `LPHV_PFS`. 

I think I've updated the front-end to work successfully here: client/src/components/AreaDetail/AreaDetail.tsx:446.

**Comment by vim-usds** [comment]
@lucasmbrown-usds

Can you point me to where this:

> 
> "Greater than or equal to the {PERCENTILE}th percentile for share of the tract's land area that is covered "
> "by impervious surface or cropland as a percent?"

would be in `constants.py`? I'm trying to find the abbreviated signal name for it. Thanks!

@KameronKerger 

Here is the staging link for each of the tracts mentioned in first comment of this ticket. I might need to meet with you all to figure out how to test these. Thanks!

https://screeningtool-staging.geoplatform.gov/2133-51ea29/en/?flags-stage_hash=2133/474caf32830ee9b8d08a0861480553482a3376c#15.06/34.02823/-118.31329


https://screeningtool-staging.geoplatform.gov/2133-51ea29/en/?flags-stage_hash=2133/474caf32830ee9b8d08a0861480553482a3376c#12.44/34.12115/-118.11633

https://screeningtool-staging.geoplatform.gov/2133-51ea29/en/?flags-stage_hash=2133/474caf32830ee9b8d08a0861480553482a3376c#14.28/34.09612/-118.13079

**Comment by vim-usds** [comment]
@lucasmbrown-usds, the lead paint indicator is missing on the staging links above. I plan to pull this branch and troubleshoot why that is. Thanks!
