### ISSUE TITLE
Subsequent runs of geo-score are slower than the first

### ISSUE THREAD

**Issue by travis-newby** [usds/justice40-tool#2143]
**Describe the bug**
When running geo-score, subsequent runs – after the first – are slower, until eventually they do not complete.

**To Reproduce**
1. Run `poetry run python3 data_pipeline/application.py geo-score`
2. Run it again... (repeat a few times)
3. Observe the slowness, and that, eventually, the run will not complete

**Expected behavior**
All runs should complete within a relatively consistent time

**Desktop:**
 - Mac Studio (M1 Max)
 - MacOS Ventura (13.0.1)

**Additional context**
I believe this is a bug caused by not cleaning the score/shapefile directory between runs. The file `usa.zip` grows with each subsequent run, until it can no longer be written to by the system.

**Comment by vim-usds** [comment]
Appreciate the write up and the ticket!

Any risks with deleting the `usa.zip` file prior to running `geo-score`?

**Comment by travis-newby** [comment]
That seems like the right thing to do there.
