### ISSUE TITLE
Copy changes after Spanish translation

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#2154]
After providing the en.json to the translation team, we've made some copy changes (there may be others) that may not be captured in the original es.json.

- #2076
- ✅  #2141
- #2134
- ✅  #2118
- ✅  #2135
- ✅  #2110
- ✅  #2170  

These may be a part of a second batch to the translation team or maybe we can translate it ourselves.

**Comment by travis-newby** [comment]
Can we lump the changes to the readme and installation files into this?

**Comment by vim-usds** [comment]
- FAQ number 5
- beta version download button
-
