### ISSUE TITLE
Push "Lack of green space" fix to prod

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#2164]
@sampowers-usds @travis-newby @KameronKerger 

In order for this to be pushed to production, we'll have to run the [create-score-version.yml](https://github.com/usds/justice40-tool/blob/main/.github/workflows/create-score-version.yml) Github action. In this action, I believe the [S3 downloadable folder is written to from the local downloadable folder](https://github.com/usds/justice40-tool/blob/160cac1002e20c3a1c78c0b86f3c94d44b1749a5/.github/workflows/create-score-version.yml#L86). I believe the "local downloadable" and the "S3 downloadable" folders are out-of-sync. 

We may want to ensure they are _synced_ prior to running this Github action as it's possible that some links may break (although there is caching with some TTL).

The path for the S3 downloadable folder for 1.0 (what is currently in production) is:
![Screen Shot 2023-02-09 at 3.52.43 PM.png](https://images.zenhubusercontent.com/60d4d92c1bf5e498d6e808ba/8fad12b9-5e93-4452-8c57-ecf6322a5150)

This S3 folder's content are on slack

**Comment by travis-newby** [comment]
This one is done as of yesterday, March 2! 🚀 We do have some followups which we've captured in #2181.

For future us, the process we (ok, mostly @vim-usds) followed was,

1. Back up the 1.0 folders on S3 and have those ready to hot-swap in jic something went wrong
2. Run the create-score-version Github Action, and monitor its progress
3. Manually invalidate all cached data (/*) in the AWS CDN
4. Check out the map and make sure it's generally working, then check that the fixes are in place
