### ISSUE TITLE
As a developer, I want to enhance the cumulative index score to include new indicators, so that I can continue to improve the score.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#217]
**Description**
Unemployment, LEAD score, housing costs and transportation costs need to be incorporated into the score formula.

Exact methodology TBD

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**
- [ ]  Score formula uses unemployment, LEAD score, housing costs, and transportation costs

**Comment by switzersc-usds** [comment]
@lucasmbrown-usds can you please update this?

**Comment by lucasmbrown-usds** [comment]
Out of date ticket.
