### ISSUE TITLE
Percentiles that end with 3s should be 3rd not 3th

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#2187]
**Describe the bug**
Reported to CEJST email address, percentiles that end in 3 should be 3**rd** not 3**th**.

**To Reproduce**
1. Go to 'Explore the map'
2. Click on 'a census tract with a percentile that ends in 3'
3. See error

**Expected behavior**
as above

**Screenshots**
If applicabl
![33rd](https://user-images.githubusercontent.com/77702996/223245676-7ba43f98-5b27-4049-8b81-b6270112d08a.png)
e, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger - nice find.. looking into this now
