### ISSUE TITLE
EJScreen Link Broken in CEJST

### ISSUE THREAD

**Issue by travis-newby** [usds/justice40-tool#2189]
**Describe the bug**
The EPA site https://www.epa.gov/ejscreen/technical-documentation-ejscreen is referenced multiple times on the CEJST Methodology and Data page. Following that link results in a 404 (page does not exist).

**To Reproduce**
1. Open the CEJST
2. Navigate to the Methodology and Data page.
3. Select `Fusion of model and monitor data`, `RMP database`, `National Air Toxics Assessment`, `Traffic Data`, or `Risk-Screening Environmental Indicators (RSEI) model`.
4. Notice the 404.

**Expected behavior**
All links on that page should point to an active website. I suggest we link to something less likely to go away, such as https://www.epa.gov/ejscreen or https://www.epa.gov/ejscreen/technical-information-about-ejscreen.

**Comment by travis-newby** [comment]
@KameronKerger curious where you think we should link.

**Comment by KameronKerger** [comment]
they must have moved it. what do you think about linking here - https://www.epa.gov/ejscreen/download-ejscreen-data

**Comment by travis-newby** [comment]
I think that's fine.
