### ISSUE TITLE
As a user, I'd like to have a single codebook, so that I don't get confused about where to look for the names of things.

### ISSUE THREAD

**Issue by travis-newby** [usds/justice40-tool#2196]
**Description**
Right now, we have two codebooks: the one generated in the downloadable directory (`xxx-codebook.csv`), and the one that is generated with the shapefile (`columns.csv`). This confuses users – and rightly so – since some data is in one but not the other.

**Solution**
We should have a single codebook representing all data.

**CoS**
- [x] Consolidate data from `columns.csv` into the main codebook (`xxx-codebook.csv`)
- [x] Remove `columns.csv` from the shapefile directory
- [x] Replace `columns.csv` with `xxx-codebook.csv` in `usa.zip`

**Comment by KameronKerger** [comment]
@travis-newby tres magnifique!

**Comment by travis-newby** [comment]
This issue addresses parts of related tickets...

* #2088 
* #1834
