### ISSUE TITLE
Small typos on FAQ

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#2209]
**Describe the bug**
See screenshot

**To Reproduce**

**Expected behavior**
The colon after Federal Register should be a period. Remove the bullet point and no indent and is there anyway to get the period to move up or is that a weird line break because of the link issue?

**Screenshots**
![image001 (3)](https://user-images.githubusercontent.com/77702996/230649139-2ac43d88-a2f8-4d85-9808-f8e42b7b4efb.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger - Gotcha. The links are weird that way and tend to wrap thing around. Is there a way we can decrease the amount of text that is linked? I believe if the linked text wasn't so long, it would fix these weird wrapping issues.

If we did that, it would look like this:

![Screen Shot 2023-04-20 at 7 30 44 AM](https://user-images.githubusercontent.com/86254807/233398318-fa8ef9a0-1ab9-4fc9-8bc7-ef837846793a.png)
