### ISSUE TITLE
methodology page - high school education indicator

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#2210]
**Describe the bug**
The language on the high school education indicator on the methodology page is incorrect / misleading.

**To Reproduce**
1. Go to 'Methodology & data'
2. Scroll down to 'Workforce development'
3. See error

**Expected behavior**
Update the text to say:
AND more than 10% of people ages 25 years or older whose high school education is less than a high school diploma.
Link on high school education

**Screenshots**
<img width="522" alt="Screen Shot 2023-04-07 at 10 21 06 AM" src="https://user-images.githubusercontent.com/77702996/230650762-2c11759c-5161-4de0-a45e-3048ee302674.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger - done
