### ISSUE TITLE
typo, missing period on the About page

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#2211]
**Describe the bug**
After the sign up sentence, there is a missing period. see screenshot

**To Reproduce**
1. Go to 'About'
2. Scroll down to 'sign-up sentence'

**Expected behavior**
Add a period at the end of the sentence.

**Screenshots**
<img width="249" alt="Screen Shot 2023-04-07 at 2 15 51 PM" src="https://user-images.githubusercontent.com/77702996/230680077-f6a3f1a3-4030-42b5-a5db-0ceb162f6bc4.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger - done
