### ISSUE TITLE
Add a new FAQ

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#2215]
**Describe the bug**
CEQ is asking that an FAQ be added to the FAQ page. See screenshot for where it should go. text below.

**Why was the CEJST initially released in a beta version?** 
CEQ launched a beta – or draft – version of the CEJST on February 18, 2022 with support from the U.S. Digital Service (USDS), and in collaboration with other Federal agencies and departments. The CEJST was released in a beta version in order to seek [feedback](https://www.federalregister.gov/documents/2022/02/23/2022-03920/climate-and-economic-justice-screening-tool-beta-version) from Federal agencies, Tribal Nations, State and local governments, Members of Congress, environmental justice stakeholders, and the public. The 90 day public comment period [closed](https://www.whitehouse.gov/ceq/news-updates/2022/04/21/ceq-extends-public-comment-period-on-beta-version-of-the-climate-and-economic-justice-screening-tool/) on May 25, 2022. CEQ and the USDS hosted several [public training](https://www.youtube.com/watch?v=QwHWcXbhw28) sessions on the beta version of the CEJST. All of this feedback on the beta version of the CEJST helped to inform the release of version 1.0 of the CEJST.

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="702" alt="Screen Shot 2023-04-17 at 11 12 25 AM" src="https://user-images.githubusercontent.com/77702996/232574452-7f06329c-dd58-41f4-9fd3-040f13131d11.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger - thanks for choosing the exact spot where a previous question was and it was just commented out! You make life easy Kameron! ❤️
