### ISSUE TITLE
[SPIKE] Research our current data set to identify areas with incomplete data / potential misrepresentations 

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#227]
We need to analyze our data set to identify possible areas/CBG that could have incomplete or missing data that could lead to misrepresentation of the score and/or inclusion in the list of prioritized communities. If there are areas of concern we need to take that to CEQ to develop a strategy to address.

As part of this, look into any possible gaps around tribal communities.

**Comment by switzersc-usds** [comment]
This has implications for how we might bucket data into different zoom levels, eg if we're bucketing at tract level for higher zoom levels.
