### ISSUE TITLE
As a score developer, I want to understand why Rio Arriba county, NM, scores low in the current version of the score, so that I can understand if the score is working appropriately.

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#228]
**Description**
[More details TBA.]

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**

**Comment by switzersc-usds** [comment]
@lucasmbrown-usds status here?
