### ISSUE TITLE
What percent of our census block groups are not in a census tract of the comparison indicator?

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#245]
**Problem statement / question**
The comparison tool already answers the question, what % of census tracts from the comparison indicator (e.g., CalEnviroScreen) include one or more census block groups from the current version of the CEJST score. 

This asks an inverse question: what percent of CBGs from the current version of the CEJST score exist outside the areas prioritized by a comparison indicator? For instance, we might find that 10% of CBGs from the CEJST score are in census tracts that CalEnviroScreen does not consider disadvantaged communities.

**Comment by lucasmbrown-usds** [comment]
In review in https://github.com/usds/justice40-tool/pull/266
