### ISSUE TITLE
As a developer, I want to read playbooks on how to respond during an incident and understand the software development life cycle.

### ISSUE THREAD

**Issue by ginabeena** [usds/justice40-tool#252]
We need playbook plays for:

- [x] restarting services
- [x] deploying services 
- [ ] ~what to do if tests fail~ N/A right now
- [x] what to do in the event of an email alert
- [ ] create a paper based rotation schedule (for now, until we have PD or other service)
- [ ] ~what to do in the event of a Denial of Service Attack (Dos, DDoS)~ Covered in incident response plan
- [ ] how to provision and rotate secrets
- [x] how to escalate to GeoPlatform team (and when to do so- noting that their availability prohibits weekends)
- [ ] clear pipeline from Google Group to Github template to notification, and having a statement that this is something we care about
- [x] documentation/process for escalating from a support email to incident response

**Comment by sverchdotgov** [comment]
(just popping in, @switzersc-usds sent me this asking if I had comments).

I don't think it makes sense for me to really run this, but I can work with whoever does it and give advice/support. It should be someone who really knows the systems and who everyone trusts. I can find the writeup we did for vaccines.gov and share it here as a starting point.
