### ISSUE TITLE
As a developer, I want to be able to see logging locally when I run the Python application using Docker  for monitoring purposes

### ISSUE THREAD

**Issue by esfoobar-usds** [usds/justice40-tool#256]
**Description**
At the moment Python logging is semi-working using a convoluted workflow (see [here](https://github.com/usds/justice40-tool/blob/845fdba2359f43a4c8a3a65c5eccae4f9fd69851/score/README.md#log-visualization)). We want to be able to see logs when the application is run via `docker run`.

**Solution**
Set up the Dockerfile or docker-compose.yml to output python logging to stdout.

**Describe alternatives you've considered**
- Tried setting up `PYTHONBUFFERED` on Docker compose without success.

**Links to user research or other resources**
- [A good resource on Docker logging](https://docs.docker.com/config/containers/logging/configure/)

**Tasks**
- [ ] Configure Docker containers to output logs to stdout for local development

**Definition of "Done"**
- [ ] Devs running the application locally can see logs on their terminals

**Comment by switzersc-usds** [comment]
Already working!
