### ISSUE TITLE
As a developer, I want to run vulnerability code scans as part of my CI/CD pipeline, so that I know my code is secure.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#261]
**Description**

From Geoplatform:

Here are some suggested tools to use. As long as the tool can detect vulnerabilities, flaws and improper configurations, it’s really up to you if you would rather use something else.

Web Application Scans:
OWASP ZAP (>https://www.zaproxy.org/<)
Pentest-Tools Website vulnerability Scanner (>https://pentest-tools.com/website-vulnerability-scanning/website-scanner<)
Snyk (>https://snyk.io/website-scanner/<)

Source Code Analysis Tools:
CodeQL (https://github.com/github/codeql)Steps to configure scans - https://docs.github.com/en/code-security/secure-coding/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository
SonarQube (>https://www.sonarqube.org/<)
Fluid Attack’s Scanner (>https://docs.fluidattacks.com/machine/scanner/plans/foss<)

**Solution**
Identify and implement a code scanner for CI/CD. 

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**
- [ ] Pick scanner
- [ ] Implement in CI/CD
- [ ] Send results to Geoplatform

**Definition of "Done"**

**Comment by switzersc-usds** [comment]
Ask Geoplatform if there is anything baked in.

**Comment by switzersc-usds** [comment]
Testing out CodeQL set up because of out of the box open source repo support on Github with Github Actions. Performing an OWASP ZAP test as well.

**Comment by switzersc-usds** [comment]
I wasn't able to finish confirming that the setup is correct for this before heading out. The checks appear to be passing, but I don't know that they should. For example, running `npm audit` on the `client` directory reveals a number of issues, none of which seem to be caught by CodeQL. I'd expect CodeQL to raise some of these same issues of not all.

@NatHillardUSDS @esfoobar-usds @ginabeena would any of y'all be able to take a look at this before we close the sprint?

**Comment by switzersc-usds** [comment]
We want to do these security checks as part of the build and deploy workflow. Looks like the runtime is pretty small. Added benefit of failing in one place.

**Comment by sverchdotgov** [comment]
(just popping in, @switzerc-usds sent me this asking if I had comments).

I think to say anything useful I'd need a bit of background information. Do you have an architecture diagram of the site and a description of what it does?

Can people write data to the site? Do people have user accounts? Are there read only datasets? These would change what's worth scanning, and for what.

**Comment by switzersc-usds** [comment]
@sverchdotgov We do have an architecture diagram! We have a bunch of info in the `docs` directory of the repo, although admittedly I think the architecture diagram itself there is out of date. I will update it tomorrow. In the meantime, here is a summary:

The front end is a static site generated by Gatsby JS. It lives on an S3 bucket with a Cloudfront CDN. There is no auth or database. The map on our site is created with the MapLibre open source library, which is an open source fork of MapBox. The map uses data that our backend publishes at static files (tiles) on S3 and with a Cloudfront CDN.

Our backend is serverless. It consists of a few python functions that get run as Github Actions. These functions ETL raw data from specified open data locations, then use that data to calculate a score (or currently, multiple scores), and then publish that data as geojson at two zoom levels and then publish that as uncompressed tiles. All files generates in this backend process live on S3.

**Comment by switzersc-usds** [comment]
Status update: We have dependabot and codeql set up and running, and we are actively addressing any identified issues as they are identified by dependabot and by codeql during CI/CD on pull requests. We should be good to go: since our infrastructure is entirely static assets on S3 with a CDN, we don't need application scanning and doing things like pen-tests or DDOS tests would essentially just be testing AWS, not us, and therefore be redundant.
