### ISSUE TITLE
Legend has reversed coloration

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#282]
**Describe the bug**
Our current legend has reversed colors. Whoops!

**To Reproduce**
1. Go to https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/9f04f5/en/cejst/?flags=mb
2. Look at legend

**Expected behavior**
"Prioritized" is white, but it should be non-prioritized

**Screenshots**
![Screen Shot 2021-07-01 at 12.44.17 PM.png](https://images.zenhubusercontent.com/6091a54c180d4758f3eedc40/dd1c97a7-a9d5-4931-854f-c71454830e16)

**Comment by TomNUSDS** [comment]
opps

**Comment by switzersc-usds** [comment]
@NatHillardUSDS which sprint does this belong to?
