### ISSUE TITLE
As a mobile user, I want the menu nav to disappear after I click an item

### ISSUE THREAD

**Issue by TomNUSDS** [usds/justice40-tool#285]
**Describe the bug**
Nav menu on mobile requires clicking the close button when navigating between pages.

**To Reproduce**
1. Be on mobile
2. Click 'menu'
3. Click on any item to switch pages
Result: page is changed but the nav menu isn't closed. Since it covers most of the page, it's hard to tell if the nav even worked

**Expected behavior**
Menu should auto-close when any nav item is clicked.

**Comment by BethMattern** [comment]
This appears to be fixed. @TomNUSDS ?
