### ISSUE TITLE
As an ECVM, I want to be able to see zoom+lat/lng in the url, so I can share and bookmark links to specific locations

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#286]
**Description**
We should add zoom/lat/lng to the URL to make it easier for people to show specific locations on the map

**Solution**
Mapbox has a built-in solution for this which is super simple! (see [here](https://stackoverflow.com/questions/64838507/is-it-possible-to-display-mapbox-coordinates-inside-a-dynamic-url))

**Describe alternatives you've considered**
- Without a hash you don't know your current zoom level, and can't share links

**Tasks**
- [ ] Enable the `hash` feature in mapbox

**Definition of "Done"**
- [ ] The URL displays zoom/lat/lng coordinates going forward

**Comment by NatHillardUSDS** [comment]
Change is available over here:
https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/27d947/en/cejst/?flags=mb

**Comment by janelien** [comment]
Looks good!
