### ISSUE TITLE
As a user, I want the CBG packet to include information about how to use that list, dataset sources, and scoring methodology (PDF)

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#292]
Add PDF to the ZIP on S3.

**Comment by katherinedm-usds** [comment]
Kameron worked off of Beth's shared "Scoring Methodology..." doc in Adobe Illustrator for this .PDF in packet and will attach exported PDF to this ticket

**Comment by KameronKerger** [comment]
[Prioritized_Communities_List.pdf](https://github.com/usds/justice40-tool/files/6804003/Prioritized_Communities_List.pdf)

**Comment by KameronKerger** [comment]
updated colors on the shapes thing... better reflects sun, water, land.
[Prioritized_Communities_List.pdf](https://github.com/usds/justice40-tool/files/6804156/Prioritized_Communities_List.pdf)

**Comment by esfoobar-usds** [comment]
Certainly @katherinedm-usds

**Comment by switzersc-usds** [comment]
We need to discuss this as a team to flesh out what we're looking for here. We should consider what kind of versioning we need for the data at all stages in the pipeline, not just the final download packet in the UI.
