### ISSUE TITLE
As an EVCM previewing the tool, I want to see if the indicators I care most about are reflected in the initial draft score so that I can feel confident that factors that impact my community most will make my community a prioritized for benefits

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#31]
Description:
This user story is about providing community members transparency into the cumulative score calculation (algorithm)

**Comment by NatHillardUSDS** [comment]
We talked a bit about this in grooming just now, and decided: 
* For the initial non-UI tool (associated with the "Initial Dataset and score" Epic), the audience is technical contributors, not yet wider community members (who will be the target for the "EVCM User Research Tool" to preview this visually
* Regarding the scoring methodology, we can use this issue to track: https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/55

Closing this issue for now with those caveats
