### ISSUE TITLE
Map performance could be better?! 

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#312]
**Is your feature request related to a problem? Please describe.**
This is more of an open question / spike ticket that may yield more tickets, but we're noticing a few areas where map performance could be improved, for example at zoom level 7 in the South. We could use some help identifying concrete improvements we can make to the map to help with performance in different specific regions as well as overall. 

Notably, some of the improvements may be back end rather than front end. We're looking for ideas that we could implement at any layer of the stack. 

**Describe the solution you'd like**
Buttery smooth and fast zoom and map performance everywhere!

**Comment by mikelmaron** [comment]
@switzersc-usds is there a demo instance up somewhere so that performance issues can be easily assessed?

**Comment by vim-usds** [comment]
@KameronKerger, @BethMattern - is this still an issue?
