### ISSUE TITLE
Zoom button styling does not match spec

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#320]
**Describe the bug**
Our zoom buttons do not currently match spec

**To Reproduce**
1. Go to the latest link: https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/d0c281/en/cejst/?flags=mb 
2. See the below:
![Screen Shot 2021-07-09 at 1.07.33 PM.png](https://images.zenhubusercontent.com/6091a54c180d4758f3eedc40/25a5d362-f745-4be0-925c-e24fbcb56d8f)
3. This does not match spec, which calls for larger zoom in / out buttons

**Expected behavior**
Should match the following:
![Screen Shot 2021-07-09 at 1.09.23 PM.png](https://images.zenhubusercontent.com/6091a54c180d4758f3eedc40/4713f63b-a69e-4965-963d-20088641e5ae)

**Screenshots**
See above

**Comment by katherinedm-usds** [comment]
Jane changed the spec to remove black formatting of button, no longer any concept of selected state

**Comment by NatHillardUSDS** [comment]
To be clear on the purpose of this ticket, this is about the zoom buttons, the +/-, which are too small / don’t match the other buttons. 

A note on terminology: internally, the “48, AK, HI, PR” buttons are known as “Territory Focus Buttons”, and the +/- are “zoom buttons". 

The black selection highlight was discussed offline and we determined to simply remove this, but that doesn't affect the "zoom button"s proper, which still do not match spec.

**Comment by NatHillardUSDS** [comment]
Available here for review:
https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/23c674/en/cejst/#3/32.47/-86.5

(side note, as a bonus, you can add ?=flags=gl,fs to get geolocation and fullscreen support, as in https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/23c674/en/cejst/?flags=gl,fs )

**Comment by janelien** [comment]
The plus / minus icons and line weight look different from spec

**Comment by NatHillardUSDS** [comment]
Moving back to in progress given issues discussed just now in dev-design review:
* faint grey background with faintly rounded corners
* Different icons (should use USWDS svgs)

**Comment by NatHillardUSDS** [comment]
Can confirm re-fix here: https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/ab72dc/en/cejst/#3/32.47/-86.5

**Comment by janelien** [comment]
Looks so good!!!
