### ISSUE TITLE
CBG boundaries and prioritization not shown for Washington DC and Puerto Rico

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#321]
**Describe the bug**
Census block group prioritization is not shown for Washington DC or Puerto Rico

**To Reproduce**
1. Go to latest link https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/cb025d/en/cejst
2. Zoom to [Washington DC ](https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/cb025d/en/cejst/#9/38.7039/-76.9093)or [Puerto Rico](https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/cb025d/en/cejst/#8.75/18.1998/-66.5831)
4. See census block group boundaries and prioritization color codes are not shown

**Expected behavior**
CBGs boundaries and correct visualization of prioritization for CBGs are shown for Washington DC and Pr

**Screenshots**
![image.png](https://images.zenhubusercontent.com/609ab603576fa56647137b9e/4b55b50a-8531-49b7-9ceb-647b6e1c8db9)If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Chrome 
 - Version: Version 91.0.4472.114 (Official Build) (x86_64)

**Additional context**
Nat mentioned in Slack that we have the boundary data from the census now if we run the score generation code again, but there may be more work to be done on the data processing side to add indicators

**Comment by switzersc-usds** [comment]
Update: Geoplatform has provided an updated file that includes this data. We just need to curl it and run our data pipeline; doing so will be a good test of our infrastructure.

**Comment by switzersc-usds** [comment]
We also need a geoJSON version.

**Comment by switzersc-usds** [comment]
We manually fixed this this week; will fix it long-term once we run through data-pipeline.
