### ISSUE TITLE
As a score developer, I want to split the ScoreETL class into having one ScoreETL subclass per score, so it's easier to read and update.

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#326]
**Description**
We'll have multiple versions of the score running at any given time, for historical purposes as well as experimentation.

Right now `ScoreETL` calculates 5 unique scores. We should have one of these score (sub)classes per unique score. This will make it easier to update. 

As part of this refactor, we can also move some of the data cleanup logic into the ETL scripts for the data, so that's not happening redundantly as part of the score. 

**Solution**
[TBA]

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**

**Comment by esfoobar-usds** [comment]
On my last conversation with @switzersc-usds, we want to not do Score generation as ETL and more like a class based modular approach.

**Comment by BethMattern** [comment]
There is more work to be done now that #618 is complete. New tasks should be added/estimated/priortized.

**Comment by switzersc-usds** [comment]
Moving this epic to the icebox. We're not sure whether more work here is valuable until we have an immediate need to for example show different scores on the map, host the score data in different locations, or do more complex score versioning / methodology experimentation.
