### ISSUE TITLE
Accessibility report fixes

### ISSUE THREAD

**Issue by TomNUSDS** [usds/justice40-tool#356]
# Errors section
- [ ] Link to github is incorrect `https://github.com/usds/justice40-tool/crisis-at-home-and-abroad/` should be `https://github.com/usds/justice40-tool/`
- [ ] report tool doesn't have the following words in it's dictionary and thinks they are typos: datasets dataset github. Probably should add to the tool?

- [ ] `/static/sourcesanspro-italic-webfont.woff2`
This is a USWDS referenced font that I don't think is used. It is referenced in the css. May indicate a build issue or may just be unused and tree shaken removed by build.
```css
@font-face {
  font-display: fallback;
  font-family: Source Sans Pro Web;
  font-style: italic;
  font-weight: 400;
```

# Accessibility Section

## Level A
- [ ] duplicate id `main-content` in same page
- [ ] duplicate title across multiple pages `Justice40` Each page should have a unique title
- [ ] `<main>` appears in the `layout.tsx` and some pages like cejst.txt and 404.tsx
- [ ] Missing `lang` attribute for English pages. Note: `Helmet` is setting but doing so in the J40Header. Maybe move this up to the `layout.tsx`?

## Level AA
- [ ] If you set any of the colors on the body or a elements you must set all of them. `background: rgb(239,246,251)` aka `#eff3fb` This is the background color of our `<aside>` Not sure th fix. Don't have background colors? There may be foreground elements that are white `rgb(255,255,255)` somewhere here?
<details><summary>See suggestion</summary>
<p>

> In HTML the color attributes are text, bgcolor, link, alink and vlink. In CSS the attributes are color and background-color. Some users have browser defaults set to white text on a black background, so setting one color without setting the others can result in black text on a black background. High contrast mode on Windows turns off background images so you must set a `background-color` in addition to a `background-image`.
</p>
</details>

- [ ] Add a sitemap (there's a gatsby plugin)

- [ ] The CSS outline or border style on this element makes it difficult or impossible to see the dotted link focus outline. Think this is just something in the USWDS css file and "how it's done"?
<details><summary>See suggestion</summary>
<p>

> Change the style to avoid obscuring the focus outline around focusable elements.
> Using a border or outline style that obscures the focus ring causes problems for keyboard-only users in:

> Chrome (obscures the focus indicator on links, buttons, dropdowns and range controls)
> Firefox (obscures the focus indicator on links)
> Internet Explorer (obscures the focus indicator on links, buttons and range controls)
> Internet Explorer does not support the `outline-offset:` property, so using this does not reliably avoid focus outline overlap.
</p>
</details>

## Level AA
 - [ ] Avoid specifying a new window as the target of a link with `target=_blank`.  This is done for links leading to external pages. We've considered having an interstitial page warning when leaving website. This should probably be a separate bug/checkin.
- [ ] Each section of content should begin with a heading element (h1, h2, h3), but this page has no headings. Probably should have only a single <h1> in header clean up h2, h3, etc. index page seems to be the issue.

# Compatibility
Most items in this section are for IE. Some are for mobile browsers. Suspect the complaints like `display: flex`, `filter:`, `mask:` not supported by mobile browsers or IE either have reasonable fallbacks or can't be fixed.

# SEO
Priority 1 and 2 items are mentioned above.
- [ ] Missing meta tags: Description, Keywords

# Standards
## Priority 1
- [ ] A document must not include more than one meta element with a charset attribute
- [ ] An img element with `alt=''` can only have `role=presentation` or `role=none`
- [ ] Element div not allowed as child element in this context
- [ ] Invalid value for CSS property `appearance: menulist`
- [ ] Invalid CSS `url()`
<details><summary>See Suggestions</summary>
<p>

> background-image: data:image/svg+xml; content: data:image/svg+xml; background-image: data:image/svg+xml; background-image: data:image/svg+xml; background-image: data:image/svg+xml;
</p>
</details>

## Priority 2

- [ ] The banner role is unnecessary for element header
- [ ] The main role is unnecessary for element main
- [ ] Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections. (🤷 without useful line numbers)

# Usability
## Priority 1

- [ ] Have a link labeled 'Home' on every page on the site, except for the home page. Note: we can turn the logo into a linked home page.

## Priority 2
Most of these are (🤷 without useful line numbers) 
- [ ] Avoid underlined text - people will click on it and think it's a broken link. 
- [ ] Do not create or direct users into pages that have no navigational options. No links out of these pages found. 
- [ ] Omitting `img width` or `height` attributes makes the page layout jump about as images load
- [ ] Provide a search option on each page of content-rich web sites

## Priority 3

- [ ] Use at least a 12-point font on all web pages
<details><summary>See suggestion</summary>
<p>

```
<p style="font-size: 11pt;" >
<p style="font-size: 15px;" >
<p style="font-size: small;" >
<font size="2" >
<font size="-1" >
```
</p>
</details>

**Comment by mgifford** [comment]
Other examples of how to integrate with CI https://accessibility.civicactions.com/posts/how-we-scale-inclusive-website-content-with-automated-testing-and-open-source-tools
