### ISSUE TITLE
States are not centered in mobile 

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#364]
**Describe the bug**
On mobile, our territory focus controls are cutoff

**To Reproduce**
1. Open https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/23c674/en/cejst/?flags=gl,fs on mobile
2. See screenshot below - the "territory focus" control buttons are cutoff

**Expected behavior**
Buttons should be styled as appropriate on mobile devices 

**Screenshots**
![iPhone.jpeg](https://images.zenhubusercontent.com/6091a54c180d4758f3eedc40/dfb670fa-c7b5-4093-9e3e-ce936b87db90)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
Seen on iPhone XS and Android pixel

**Comment by vim-usds** [comment]
Related tickets:

https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/428
