### ISSUE TITLE
Each transpiled file includes its own copy of styles instead of a static reference

### ISSUE THREAD

**Issue by TomNUSDS** [usds/justice40-tool#366]
**Describe the bug**
There is something wrong with our build. CSS styles should be referenced in an external css file not embedded in each file. This is making the file very large.

**To Reproduce**
1. run `gatsby clean`
2. run `gatsby build`
3. optional run `prettier --write ./public/` to reformat "compressed" content.
4. Open any of the `index.html` files
Result: each file has **21k lines** of css in it.

**Expected behavior**
The css should be referenced via a external file.  eg. `<link type="text/css" rel="stylesheet" href="...">`

**Comment by TomNUSDS** [comment]
https://github.com/gatsbyjs/gatsby/issues/1526#issuecomment-433347822

**Comment by katherinedm-usds** [comment]
hi @TomNUSDS! I see this is in Design column. Not sure from this bug description and history if this specifically needs Design input right now, and if so what that input is?

**Comment by TomNUSDS** [comment]
This was purely an dev issue. It was just a big inefficient in generating the html/css.

**Comment by switzersc-usds** [comment]
Fixed!
