### ISSUE TITLE
As a contributor to the repo, I want to see a workflow diagram of the data-pipeline and score generation so that I understand how the pieces fit together.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#370]
**Description**
It would be helpful to have a workflow diagram showing how the data pipeline and score generation code works so that it's easier to understand and contribute to. 

**Solution**
Mermaid diagram to be added to `docs` and embedded in the score/data-pipeline README as an image.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**
- [ ] Mermaid diagram added to `docs` and embedded in the score/data-pipeline README as an image.

**Comment by vim-usds** [comment]
@esfoobar-usds - I believe we have this right?
