### ISSUE TITLE
As a developer, I want to compare the list of prioritized census block groups to the published list of Persistent Poverty Counties, so that I can see how our list matches up.

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#392]
**Description**
The US Department of the Treasury, as part of The Consolidated and Further Continuing Appropriations Act, published a list of Persistent Poverty Counties.  Persistent Poverty Counties are defined by Public Law 112-74 (enacted on December 23, 2011) as counties where 20% or more of their population lives in poverty as measured by the U.S. Census Bureau (1990 and 2000 decennial censuses, and 2006-2010 American Community Survey)

It will be helpful in evaluating our score to report on the number of counties on the Persistent Poverty Counties list that has one or more census block groups that are considered prioritized on our list.

**Links to user research or other resources**
https://www.mycdfi.cdfifund.gov/what_we_do/persistentpoverty.asp

**Tasks**
[ ] Load the list of counties from the Persistent Poverty Counties list into the comparison tool (file is attached to this ticket)
[ ] Load the list of prioritized census block groups generated by the CEJST score/process
[ ] Identify which counties from the Persistent Poverty Counties list have census block groups in the list of prioritized communities
[ ] Produce a report that summarizes how many PPCs contain prioritized census block groups

**Definition of "Done"**
[ ] Report is ready for review by internal stakeholders

**Comment by BethMattern** [comment]
[persistent-poverty-counties-(ppcs)-(2011-2015-acs-and-island-areas-decennial-census).xlsx](https://github.com/usds/justice40-tool/files/6851637/persistent-poverty-counties-.ppcs.-.2011-2015-acs-and-island-areas-decennial-census.xlsx)

**Comment by lucasmbrown-usds** [comment]
https://s4.ad.brown.edu/Projects/Diversity/Researcher/LTBDDload/Dfiles/codebooks.pdf - ppovXX is `% in poverty, total`
