### ISSUE TITLE
As a developer, I want to update the download button with new zip (much larger zip file)

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#393]
## What needs to happen?
- The URL located in downloadPacket.tsx (called cbgFileURL = census block group file url) needs to be updated.
- The URL should be updated to: ` https://justice40-data.s3.amazonaws.com/data-pipeline/data/score/csv/full/usa.csv`

## Issue:
- The new URL has a download file that is much bigger. It's causing the cypress test (`client/cypress/e2e/downloadPacket.spec.js`) to fail. 
- run `npx cypress open` to open the cypress UI and click on `downloadPacket.spec.js` to trigger the test in the cypress UI.

## Possible solutions:
1. Experiment with intercepting the response so that the full file is not downloaded in cypress.

## Related tasks:
1. Touch this when we're ready to move the download button to it's new location
2. Add styling around button using theming as described in this [thread](https://usds.slack.com/archives/C01LA9YLNE9/p1626810938205800)
### Resources:
https://docs.cypress.io/guides/guides/network-requests#Testing-Strategies
https://docs.cypress.io/api/commands/intercept#Syntax

### Additionally,
1. ~Should this ticket be blocked by the #308 (styling of columns)?~
2. Should we also wait until the other files (xlsx, and pdf) are placed into the zip file?

**Comment by esfoobar-usds** [comment]
@vim-usds this ticket shouldn't be blocked by #308 which is related to the internal classes and functions of the Python files.

This needs to be a step on the `score/etl_score_post.py` that generates this zipped file with the desired CSV proper columns. The related backend ticket is #303.

**Comment by vim-usds** [comment]
@esfoobar-usds, thanks,

I might have the ticket number wrong. I believe it was mentioned somewhere on slack that some styling is required for columns? I was wondering if that task could be a blocker?

**Comment by switzersc-usds** [comment]
No longer an issue
