### ISSUE TITLE
Test automation of prioritized scenarios (desktop only)

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#413]
## Description:
Kameron has described in the attached doc and reviewed in the July 20th "QA/test workflow review" meeting desktop and mobile scenarios for the following 18 workstreams.

As discussed with Nat after the July 20th meeting, seems to make more sense to open just one ticket initially because it could be that tests could go across multiple workstreams, and the dev team could follow up with splitting up this ticket into potentially ~3 tickets to evenly distribute the work.

Note that we may want create multiple issues for this one, but let's see what we can scope in for this sprint out of this list and then add new issues for what we can't get to.

### Workstreams
- [x] Site navigation (navigate "About", "Explore the tool", etc.)
- [x] Federal program officer key information and CTA (download communities list packet, etc.)
- [x] Community members key information and CTA 
- [x] Send feedback
- [x] Join the Open Source community
- [x] Link to White House website
- [x] Link to the Freedom of Information Act (FOIA) website
- [x] Link to the Privacy Policy
- [x] Link to find a contact at USA.gov
- [x] Contact CEQ (mobile requirements only - skipping)
- [x] Official government website link (from component library and test not needed - skipping)
- [x] Link to the January 27th Executive Order
- [x] Contact emails (regular cypress test already in place - skipping)
- [x] Data & methodology - download communities list packet (regular cypress test already in place - skipping)
- [x] Data & methodology - users learn more about sources of data
- [x] Explore the tool (zoom into map, select a census block group, etc.) (moving to another ticket)
- [x] Explore the tool - download the communities list packet (moving to another ticket)
- [x] Explore the tool - learn how to improve the tool (moving to another ticket)

**Comment by katherinedm-usds** [comment]
[https://app.zenhub.com/files/358242767/8b075ba6-4c83-40fb-bda7-200f17cd2571/download](https://app.zenhub.com/files/358242767/8b075ba6-4c83-40fb-bda7-200f17cd2571/download)

**Comment by switzersc-usds** [comment]
We will break this up into multiple tickets once we start diving into the tests to better understand the overlaps. We don't want massive PRs, so we should use a line limit for PRs as a guiding principle for splitting this up. 400 lines of green diff is the limit!
