### ISSUE TITLE
Compress CSV to Zip file for download packet

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#419]
**Description**
For the front end download packet feature, we need the CSV to live as a compressed ZIP on S3. We will then add the Excel file and PDF to the ZIP as separate issues.

**Tasks**
- [ ] Update file on S3 to ZIP
- [ ] Double check that the front end has the right URL for the ZIP

**Comment by esfoobar-usds** [comment]
Duplicate of #303
