### ISSUE TITLE
Turn Lighthouse on for all pages and fix failures.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#420]
Our current lighthouse test ([here](https://github.com/usds/justice40-tool/blob/main/client/cypress/e2e/accessibility.test.js)) , only runs against the main page. 

The `nathillardusds/failing_lighthouse` branch fixes tests to run instead on all pages. When you do this, you get the below output:
[acccessibility_failures.log](https://github.com/usds/justice40-tool/files/6887301/acccessibility_failures.log)

We should look through these and fix them

**Comment by switzersc-usds** [comment]
We turned it on for all pages and have lots of errors we need to fix!

**Comment by vim-usds** [comment]
All pages are failing the following:

1. document-title
2. html-has-lang
3. landmork-one-main
4. page-has-heading-one

Other than item 2, the pages do have all the others. Needs more investigating why it's failing

**Comment by vim-usds** [comment]
Seeing some light on this.

While the cypress.axe alerts on a11y issues are great for CI/CD, it doesn't show where the error is happening. 
The Axe chrome [plugin](https://www.deque.com/axe/) is showing promise. On localhost it seems to not only identify a11y issues, but also point out where it's occurring. One this is addressed via the plugin,  then one can check the cypress.axe tests to see if alerts are passing. More to come on this.

**Comment by vim-usds** [comment]
All automated a11y testing (aka cypress-axe) are now passing! 🥳 

For both mobile and desktop, all pages on the staging URL has an A11y lighthouse score of 100% ! 🥇 

About = 100% ✅
Explore = 100% ✅
Methodology = 100% ✅
Contact = 100% ✅

The automated a11y testing (via cypress-axe) is more stringent than Lighthouse (it seems). The only _visible_ change to the site that needs review was the addition of an `<h1>` tag to the About page:

- http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/c40867/en/

Looking forward to your review!
