### ISSUE TITLE
Download packet results in "This XML file does not appear to have any style information associated with it" error instead of download

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#434]
**Describe the bug**
Download packet link on [URL](https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/main/en/cejst#3/63.28/-162.39) shared by Nat July 28th shows error 

**To Reproduce**
1. Go to 'https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/main/en/cejst#3/63.28/-162.39'
2. Click on 'Download packet'
3. See error "This XML file does not appear to have any style information associated with it. The document tree is shown below."

**Expected behavior**
Packet .zip file is downloaded

**Screenshots**
![image.png](https://images.zenhubusercontent.com/609ab603576fa56647137b9e/2980449c-b4bc-4409-8ebd-6ac7cd013a5b)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Chrome
 - Version 92.0.4515.107 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**
Vim indicated this was a bug

**Comment by vim-usds** [comment]
The zip file's URL has been made public.

The download packet has been removed from the UI. It will be placed back into the UI on this ticket:

https://app.zenhub.com/workspaces/justice40-60993f6e05473d0010ec44e3/issues/usds/justice40-tool/351

**Comment by switzersc-usds** [comment]
This may be fixed with latest PR from @esfoobar-usds. To be tested.

**Comment by esfoobar-usds** [comment]
I just tested this and it's been fixed with my last PR
