### ISSUE TITLE
"Explore the tool" color key box shows ovals instead of circles, and flash of info pop up when loading

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#462]
**Describe the bug**
I took a look at the [link](https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/e108d5/en/cejst#4.87/50.24/-61.5) in closed ticket https://github.com/usds/justice40-tool/pull/454#issuecomment-892344545, overall page looks great but noticed a couple small quirks with the color key box. 

**To Reproduce**
1. Go to https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/e108d5/en/cejst#4.87/50.24/-61.5 with non-maximized Chrome browser window
2. Observe the color key box as the page loads - you'll see a flash of a text box with white font on a black background

**Expected behavior**
Don't flash the content of the info pop-ups when loading the page

**Screenshots**
https://user-images.githubusercontent.com/74208851/128269696-5ca3bade-3486-4d52-9f94-455d713bf244.mov

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser Chrome
 - Version 92.0.4515.107 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@katherinedm-usds ,

I believe the screen size width may not be one of the ones targeted in this ticket. I think the width should either be > 1024px or < 400px.

In regards to the flash of black sections, that's totally legit. Thanks!

**Comment by katherinedm-usds** [comment]
Cool @vim-usds thanks! I just updated the title of this ticket to remove mention of ovals and modified original comment to remove "3. Observe the color key circles look like ovals"

**Comment by vim-usds** [comment]
Thank you!
