### ISSUE TITLE
Side panel should not show circle for non-prioritized areas, should not need refresh on screen size change, and remove warnings in console

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#463]
**Describe the bug**
Click on non-prioritized areas, circle should not be there

Additional things to fix while this component is being touched:
- [ ] useWindowSize hook to render map on mobile (w/o refresh)
- [ ] fix commented out cypress tests
- [ ] not prioritized = no bubble
- [ ] fix areaDetail console warning (re-run tests/ snapshots) on unused indicator style

**Comment by switzersc-usds** [comment]
@vim-usds can you include a screenshot of the circle this is referring to? i don't see anything other than this, which doesn't seem like a bug: ![image.png](https://images.zenhubusercontent.com/60994445b305970bf293d619/7f4c5cfb-8fa5-419c-b13a-2711fc9ed027)
