### ISSUE TITLE
If the census download task is run more than once, us.csv doubles in size and all data is removed from dataframe

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#467]
**Describe the bug**
If you run the census ETL more than once, us.csv ends up with ~600K rows instead of ~300K. Later on, when we do a duplicate check in `etl_post`, all the data is removed

**To Reproduce**
1. Run `poetry run download_census`
2. Run it again, without running the clean task
3. Check output of `etl_score_post` - data has been removed entirely because of a duplicate removal step

**Expected behavior**
These tasks should be idempotent, able to be run multiple times without altering the results.

**Comment by esfoobar-usds** [comment]
This is no longer the case, since in [the latest merged PR](https://github.com/usds/justice40-tool/pull/465), `census-download` runs a folder cleanup first. It's okay to check for its existence within the function though, specially if it's called outside of `click`
