### ISSUE TITLE
Nightly tests failing as of 9 days ago 

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#471]
**Describe the bug**
See [here](https://github.com/usds/justice40-tool/actions/runs/1073597302) - our nightly tests are failing, in particular our map tests -- it seems to be related to the changing size of our map

**To Reproduce**
1. Go to https://github.com/usds/justice40-tool/actions/runs/1073597302 to see test logs from 9 days ago for the map tests
2. See below :
```

  1) Tests for the Explore the Map page
       Can focus on Lower 48 :
     AssertionError: Timed out retrying after 4000ms: expected 'http://localhost:8000/en/cejst#3.19/38.07/-95.87' to include '3.25/38.07/-95.87'
      at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/map.spec.js:119:18)

  2) Tests for the Explore the Map page
       Can focus on Hawaii :
     AssertionError: Timed out retrying after 4000ms: expected 'http://localhost:8000/en/cejst#5.35/20.574/-161.438' to include '5.89/20.574/-161.438'
      at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/map.spec.js:119:18)

  3) Tests for the Explore the Map page
       Can focus on Puerto Rico :
     AssertionError: Timed out retrying after 4000ms: expected 'http://localhost:8000/en/cejst#7.65/18.2/-66.583' to include '8.19/18.2/-66.583'
      at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/map.spec.js:119:18)
```
This appears to be related to our map changing size

**Expected behavior**
These tests should pass every night

**Possible Fix**
1. run `npm run cy:open`
2. This will trigger the cy window, click on the failing test
3. check the URL for z/x/y numbers, 
4. they should match the expected numbers in the test

**Comment by switzersc-usds** [comment]
We have the solution for this. We need to change expectation on the test.
