### ISSUE TITLE
Subsequent pushes to PR branch do not post new updates

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#472]
**Describe the bug**
As things are currently setup, subsequent push events to the same branch should trigger a new build and post a new hash. This is not currently happening

**To Reproduce**
1. Open a new PR
2. Bot posts PR links
3. Make some changes, push them to the branch
4. Bot does not post PR links!

**Expected behavior**
Every new push to the branch should result in:
*  the app being rebuilt 
* sources being posted to a new hashed-location 
* the PR bot updating the PR with the link to the hash

**Additional context**
We suspect this line might be the problem: https://github.com/usds/justice40-tool/blob/main/.github/workflows/build_deploy.yml#L102  , given order of operations. We should surround the first two args with parens

**Comment by esfoobar-usds** [comment]
@switzersc-usds I think we can close this one
