### ISSUE TITLE
Docker-compose file does not properly build / run commands

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#478]
**Describe the bug**
I see three issues - I think I personally caused at least 1.5 of these, but :
1.  Docs should be updated with new application.py path ( I broke this)
2. Seeing No matching distribution found for fiona==1.8.20 when installing the current requirements.txt - not sure how this got out of sync, I had recently run a poetry export which should have worked, not clear where fiona even came from - (a mystery to track down)
3. Directories are not persisted locally on Unix systems - need to specify shared volumes differently (may be as simple as adding volumes: section at the bottom?) (this seems to be a windows-unix mismatch that has been around since the first version of the compose file)

**To Reproduce**
1. Remove all existing docker images 
2. In the root dir, run `docker compose up --build`
3. Observe:
```log
#20 7.117     ERROR: Command errored out with exit status 1:
#20 7.117      command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mmndfmor/fiona_5f0f4fec7a1e4871933b7a98e35dca30/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mmndfmor/fiona_5f0f4fec7a1e4871933b7a98e35dca30/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-s_4ul1g2
#20 7.117          cwd: /tmp/pip-install-mmndfmor/fiona_5f0f4fec7a1e4871933b7a98e35dca30/
#20 7.117     Complete output (2 lines):
#20 7.117     Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'
#20 7.117     A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
#20 7.117     ----------------------------------------
#20 7.118 WARNING: Discarding https://files.pythonhosted.org/packages/ec/f7/093890341a7e8fbfcdfa04caf4dfb588ebab32c13ceaa6a3819da79ea106/Fiona-1.8.20.tar.gz#sha256=a70502d2857b82f749c09cb0dea3726787747933a2a1599b5ab787d74e3c143b (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#20 7.118 ERROR: Could not find a version that satisfies the requirement fiona==1.8.20 (from versions: 0.5, 0.6, 0.6.1, 0.6.2, 0.7, 0.8, 0.9, 0.9.1, 0.10, 0.12, 0.12.1, 0.13, 0.14, 0.15, 0.16, 0.16.1, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.1, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.3.post1, 1.6.4, 1.7b1, 1.7.0, 1.7.0.post2, 1.7.1, 1.7.1.post1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.9.post1, 1.7.10, 1.7.10.post1, 1.7.11, 1.7.11.post1, 1.7.11.post2, 1.7.12, 1.7.13, 1.8a1, 1.8a2, 1.8a3, 1.8b1, 1.8b2, 1.8rc1, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.9.post1, 1.8.9.post2, 1.8.10, 1.8.11, 1.8.12, 1.8.13, 1.8.13.post1, 1.8.14, 1.8.15, 1.8.16, 1.8.17, 1.8.18, 1.8.19, 1.8.20)
#20 7.118 ERROR: No matching distribution found for fiona==1.8.20
------
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c pip3 install -r requirements.txt]: exit code: 1
```
4. (with cached, working image), attempt to run `docker exec j40_data_pipeline_1 python3 application.py [command]`
5. Observe `python3L can't open fie 'application.py'`
6. (with cached, working image), attempt to run pipeline commands to download data
7. Observe that files are not downloaded to shared volume directory when run on macOS/ a unix machine

**Expected behavior**
We should be able to :
1. build the image
2. run the image using documented commands
3. persist files on local disk

**Comment by esfoobar-usds** [comment]
Note: to avoid having to delete any images, you can do `docker-compose build --no-cache`. This will ensure that a brand new image is built.

**Comment by sverchdotgov** [comment]
This issue is outdated and no longer relevant. I believe the issue described is fixed, but we do have another bug in the compose setup that we are tracking here: https://github.com/usds/justice40-tool/issues/1108

Also, we now have a [docker compose quickstart](https://github.com/usds/justice40-tool/blob/main/QUICKSTART.md) documenting this setup.
