### ISSUE TITLE
Task: Add download packet to Methodology page

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#480]
## Describe the task
Add download packet to Methodology page

Use Sprint 4 designs as a guide

Also
- refactor component for new layout structure
- address snapshot test undefined class

**Comment by katherinedm-usds** [comment]
Just checked on OMB computer, iPhone 12, and iPad 6th gen - rectangle, text, download functionality, transition of Draft communities list rectangle from to the right of the "The cumulative index score is a metric..." text to inline below that text happens as expected on computer browser when I change browser window width, and is inline below text as expected on iPhone 12, but just doesn't appear to show for me on iPad 6th gen @vim-usds

**Comment by vim-usds** [comment]
@katherinedm-usds , anyway to take a screen shot and post here? I don't have an iPad to replicate
