### ISSUE TITLE
Github actions should initiate lambda run instead of running entire data pipeline

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#485]
**Describe the bug**
After #469, we are running through the census data download, the full etl, and the score creation scripts on all changes to `data/data-pipeline`. 

The result is a run like [this one](https://github.com/usds/justice40-tool/runs/3267245733?check_suite_focus=true), which take ~50 minutes. 

This is not ideal for several reasons:
1. It occasionally times out (this run previously ran for 40 minutes before timing out and had to be manually re-run)
2. We will eventually move the files into AWS anyway and should ideally start and end there.
3. We will soon have relatively duplicative code pushed remotely by the Serverless app / lambdas
4. We could in theory use higher powered machines in the future via lambda settings

Instead, we should initiate a lambda run on AWS when our infrastructure has been set up. 

**To Reproduce**
1. Push a change to data/data-pipeline
2. Wait 50 minutes
3. Check out a run of the "Deploy Data" workflow [here](https://github.com/usds/justice40-tool/actions/workflows/deploy_data.yml)
4. Notice that you have just spent 50 minutes running something on github that should probably have been run on AWS. 

**Expected behavior**
Running these processes on AWS will remove duplication with our infra setup, ensure ability to parallelize and/or bulk up machine capacity, and use a more robust infrastructure for this long-running job. Additionally we can have finer grained control of when to run which portion of the pipeline.

**Comment by esfoobar-usds** [comment]
Yeah, `deploy-data.yml` has been replaced by the other GHA and should be removed.

**Comment by sverchdotgov** [comment]
Ok, I'm going to close this out then. Linked the note about performance of the deletion step in https://github.com/usds/justice40-tool/issues/488#issuecomment-1006828481, so it's at least documented in an open ticket somewhere.
