### ISSUE TITLE
Create a Github Action for data source ETL so that upstream data issues do not impact score and tile generation.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#488]
Updating this issue as a result of #946. We want to mitigate the effect of issues in upstream data sources on our data pipeline. 

Make a Github action that:

- Runs the etl for all the sources 
- Run score, score-post and score-geo

**Comment by sverchdotgov** [comment]
This issue might help with performance of the tilefy job, because `aws s3 rm --recursive` is not using batch operations and is known to be slow, but this might eliminate the need for that step. See https://github.com/usds/justice40-tool/issues/485#issuecomment-1006791510
