### ISSUE TITLE
As a score developer, I want to compare a census block group's income level to the area median income.

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#492]
**Description**
Determine whether the median income for a block group is: 
* For non-metropolitan CBGs, median family income does not exceed 80% of statewide median family income 
* For metropolitan CBGs, median family income does not exceed 80% of statewide median family income OR 80% of the metropolitan area’s median family income

**Tasks**
This could be broken down into multiple tickets. 

1. Load state and metropolitan area median family incomes (from HUD?) 
2. Load join table of CBGs to CBSAs
    * Can use geocorr (https://mcdc.missouri.edu/applications/geocorr2014.html), but this needs to be run 51 times, one for each state and territory. 
    * There are no uniform codes for identifying CBSAs. It looks like HUD's `cbsasub` field contains the typical `cbsa10` code inside of it. e.g., for St. Joseph, MO-KS Metropolitan Statistical Area, HUD calls this METRO41140M41140 and the cbsa10 from geocorr is 41140.
    * It might be possible to match on free text. E.g., HUD calls it `St. Joseph, MO-KS Metropolitan Statistical Area` and geocorr calls it `St. Joseph, MO-KS MSA`. Replace Metropolitan Statistical Area with MSA and those are the same.
3.  Identify whether CBG is in a metropolitan area (i.e., is first five characters of `cbsasub` field from geocorr == `METRO`) 
4. Make calculation comparing median income to AMI appropriately

**Definition of "Done"**

**Comment by BethMattern** [comment]
@lucasmbrown-usds wasn't this done as part of the last score you implemented, as part of this indicator: Median family income does not exceed 80% of statewide median family income AND less than high school education is greater than 20%
