### ISSUE TITLE
Deploy Data workflow should fire via manual trigger, not on every PR ; should also not be firing on non-data-pipeline changes

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#493]
**Describe the bug**
Currently our Deploy Data [workflow](https://github.com/usds/justice40-tool/blob/main/.github/workflows/deploy_data.yml) fires on all PRs. But - it takes an hour to run. We should move to use [workflow_dispatch](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) instead , and/or trigger via [schedule](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule). 

Also, as a bonus bug! It's firing on changes to directories that are not data-pipeline. This should not be the case. 

**To Reproduce**
1. Create a PR , and/or create a PR that includes changes not made to the data directory 
2. Notice the Deploy Data workflow is running, takes an hour, and prohibits merging for an hour

**Expected behavior**
We should move to a manual trigger so we don't have to wait

**Comment by esfoobar-usds** [comment]
The firing bug is addressed with #491
