### ISSUE TITLE
Don't use Nat's personal (Admin) role to upload files to S3

### ISSUE THREAD

**Issue by NatHillardUSDS** [usds/justice40-tool#494]
**Describe the bug**
Right now our [deploy data])(https://github.com/usds/justice40-tool/blob/main/.github/workflows/deploy_data.yml) workflow, which has the single responsibility of writing files to our S3 bucket under `data/data-pipeline` is set up to use `DATA_DEV_AWS_ACCESS_KEY_ID` and `DATA_DEV_AWS_SECRET_ACCESS_KEY` . Under the hood, in [settings->secrets](https://github.com/usds/justice40-tool/settings/secrets/actions) these are set to be my (Nat)'s personal admin role credentials. This is obviously bad - we should work with Zivaro to create a targeted and restricted IAM role and use that instead. 

**To Reproduce**
1. Go to https://github.com/usds/justice40-tool/settings/secrets/actions
2. Know that these represent admin credentials
3. These should not represent admin credentials

**Expected behavior**
We should work with Zivaro to create a targeted and restricted IAM role, which can *only* write to `data/data-pipeline`, and use that instead

**Tasks**
* Request a role with permissions only to write to `data/data-pipeline` -- we'll need two, one for our dev environment and one for prod
* Incorporate this role into our Serverless app setup
* Write out `DATA_DEV_AWS_ACCESS_KEY_ID` and `DATA_DEV_AWS_SECRET_ACCESS_KEY` vars to match the creds of these roles

**Comment by esfoobar-usds** [comment]
Got creds from Zivaro, implementing today

**Comment by esfoobar-usds** [comment]
Added to Github Actions
