### ISSUE TITLE
Resolve Linting Issues with Score F

### ISSUE THREAD

**Issue by esfoobar-usds** [usds/justice40-tool#529]
This bug relates to https://github.com/usds/justice40-tool/pull/510

Right now linting tests are not passing because of two issues:

1 There are too many statements on the transform function which reflects a need to refactor the `score/etl.py` file
1 Lucas re-added `matplotlib` which has a license dependency with `Pillow` which uses some licensed imaging libraries. I need to research how to clear this, which according to Nat, it's just a matter of adding a `LICENCE` file

**Comment by switzersc-usds** [comment]
Jorge is working on this and will timebox it. If we can't get past this today we will make an exception for this linting rule, and potentially revisit with the bigger refactor of the score work.
