### ISSUE TITLE
Create "COMBINE-TILEFY" Github Action

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#535]
**Description**
Create one github action that combines the score into differnt zoom levels, writes the geojson files to S3, and the creates/loads the tiles. 

**Definition of Done**
- [x] Refactor `application.py` & `generate.py` to be parameterized by a `--datasource` (local is default, but if you pass in `aws` then we look for those resources externally) flag and making an external S3 call where it is using our Score.csv & GeoJSON 
- [x] Github Action (clone and use the Score Action) definition yml and call SYNC after so that we write to S3
- [x] Switch to using python click CLI instead of Poetry commands
- [x] Remove poetry commands from pyproject.toml and from README
- [ ] Making sure that the github errors and logging happen
- [ ] Write test that produces failure when the file isn't in S3

**Comment by ginabeena** [comment]
Take a look at the Click library for passing optionals on the CLI
