### ISSUE TITLE
As a developer, I want the option to run the main python functions using files from S3, instead of local files.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#540]
**Description**
Refactor score, combine, and tile-fy related python functions to use S3 files. This is needed for the devops work to set up Github Actions for these.

**Solution**
A clear and concise description of the solution.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**

**Definition of "Done"**

**Comment by esfoobar-usds** [comment]
This will be completed as part of #535
