### ISSUE TITLE
Configure production CDN with main front-end deployment

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#542]
**Description**
When we merge front end code to main, it deploys to S3. We need to set up the production CDN for this S3.

**Comment by switzersc-usds** [comment]
@vim-usds @esfoobar-usds I feel like we've done this already - do either of y'all know the status for this?

**Comment by esfoobar-usds** [comment]
There is no production CDN, since there's no production environment. We can close this one and reopen when we do.
