### ISSUE TITLE
Remove/add columns from the prioritized communities download file

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#565]
The download .csv/.xls should contain the following columns (do NOT rename from existing CSV, these are just a bit off):

GEOID10
County name **(used to be in file, now gone from sample)**
State name **(used to be in file, now gone from sample)**
Score G (communities)
Median household income (% of AMI)
Median household income (% of state median household income) (percentile)
Area Median Income (State or metropolitan)
Area Median Income (State or metropolitan) (percentile)
Percent of individuals < 100% Federal Poverty Line
Percent of individuals < 100% Federal Poverty Line (percentile)
Percent individuals age 25 or over with less than high school degree
Percent individuals age 25 or over with less than high school degree (percentile)
Diagnosed diabetes among adults aged >=18 years
Diagnosed diabetes among adults aged >=18 years (percentile)
Current asthma among adults aged >=18 years
Current asthma among adults aged >=18 years (percentile)
Coronary heart disease among adults aged >=18 years
Coronary heart disease among adults aged >=18 years (percentile)
Life expectancy (years)
Life expectancy (years) (percentile)
Traffic proximity and volume
Traffic proximity and volume (percentile)
FEMA Risk Index Expected Annual Loss Score
FEMA Risk Index Expected Annual Loss Score (percentile)
Energy burden
Energy burden (percentile)
Housing burden (percent)
Housing burden (percent) (percentile)
Wastewater discharge
Wastewater discharge (percentile)
Percent pre-1960s housing (lead paint indicator)
Percent pre-1960s housing (lead paint indicator) (percentile)
Diesel particulate matter
Diesel particulate matter (percentile)
Particulate matter (PM2.5)
Particulate matter (PM2.5) (percentile)
Total population
Total population (percentile)

**Comment by switzersc-usds** [comment]
Discussed this in standup today: we will pause this while we learn more about what columns we want to include or cut from the download for this upcoming sprint.

**Comment by BethMattern** [comment]
Updated to reflect all of the approved indicators as of 9/15

**Comment by esfoobar-usds** [comment]
@BethMattern can you update this ticket when you have edited the names to match with the ones on the score csv excel? Thanks!

**Comment by esfoobar-usds** [comment]
@BethMattern just checking something:

These two columns don't follow the plain, percentile pattern:

- Median household income (% of AMI)
- Median household income (% of state median household income) (percentile)

Is this accurate? We don't want the following?
-  Median household income (% of AMI) (percentile)
- Median household income (% of state median household income)

**Comment by KameronKerger** [comment]
[Draft_Communities_List_V3.pdf](https://github.com/usds/justice40-tool/files/7180591/Draft_Communities_List_V3.pdf)

**Comment by BethMattern** [comment]
Thanks @esfoobar-usds - does this look more correct below? I've put this in the overall decription abov

Median household income (% of AMI)
Median household income (% of state median household income) (percentile)
Area Median Income (State or metropolitan)
Area Median Income (State or metropolitan) (percentile)

**Comment by esfoobar-usds** [comment]
@BethMattern can you check if the files look good?
https://drive.google.com/file/d/1jHbwhw8U1nKON958eWEZcB4h9wrHYMHy/view?usp=sharing

**Comment by BethMattern** [comment]
Looks good!!!

**Comment by BethMattern** [comment]
@esfoobar-usds one change actually - can Score G column header be changed to say "Community of focus"?

**Comment by esfoobar-usds** [comment]
Is that in both the CSV and Excel files?

**Comment by BethMattern** [comment]
yes please

**Comment by KameronKerger** [comment]
[Draft_Communities_List_V4.pdf](https://github.com/usds/justice40-tool/files/7181032/Draft_Communities_List_V4.pdf)

**Comment by KameronKerger** [comment]
[Draft_Communities_List_V5.pdf](https://github.com/usds/justice40-tool/files/7181123/Draft_Communities_List_V5.pdf)

**Comment by BethMattern** [comment]
Correction: update "Score G" column name to be "Community of focus (v0.1)"

**Comment by esfoobar-usds** [comment]
@KameronKerger @BethMattern FYI, we'll just call it "Draft_Communities_List.pdf" and commit to the repo, so versioning will be handled by Github

**Comment by esfoobar-usds** [comment]
@BethMattern @KameronKerger can you check the ZIP package?
https://drive.google.com/file/d/1CBzZ0kOe_kWDvpLzyFktH89Ym96bfiq-/view?usp=sharing
