### ISSUE TITLE
Implement consistent typography for all <h> tags on all pages

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#571]
See typography sheet in design tool. This ticket is just about updating heading tags to be consistent. Use USWDS tokens.

For implementing USWDS tokens for other tags, we will create new tickets to tackle thosse in groups based on priority and what Glennette finds in her audit.

**Comment by vim-usds** [comment]
refactored the global.scss file. A great deal of work. h1s now seem to functional from USWDS

**Comment by switzersc-usds** [comment]
Had to start a full refactor in able to tackle <h> tags, so now this includes all content tags. This will likely extend into the first part of next sprint.

**Comment by vim-usds** [comment]
Hi @katherinedm-usds and/or @janelien 

Here's the this issue's link!
https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/9ad363/en/

It would be awesome if QA can validate (excluding the methodology page as it seems some of it may be removed):
- [ ] Header / nav is within the main width of the page
- [ ] the headings identified in designs are consistent across site 
- [ ] the p tags identified in designs are consistent across site 
- [ ] the spacing between sections identified in designs are consistent across site 

What still needs to be done:
- [ ] consistency of color
- [ ] methodology page consistency

If the things that are left to be done is priority we can make a ticket for the remaining items. Thank you!

**Comment by janelien** [comment]
The spacing is so much better!
I think the font is still Source Sans Pro, whereas the spec is for Public Sans. I'm ok with that being a later change though.
