### ISSUE TITLE
Task: Add "Council on Environmental Quality" in footer below "Contact", above address

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#573]
## Describe the task
Now that the footer design is a little different to work more within USWDS constraints, "Council on Environmental Quality" no longer appears above the "730 Jackson Pl NW" line. Would be good to add a "Council on Environmental Quality" line of text above "730 Jackson Pl NW". Note, keep the logo and "Council on Environmental Quality" at the very bottom of the footer as is.

## Subtasks
 - [ ] @janelien confirm, update design, "With USWDS Tokens" section designs currently have "730 Jackson Pl NW" directly under "Contact"
 - [ ] Dev add "Council on Environmental Quality" text to footer below "Contact" and above address to footer

**Comment by vim-usds** [comment]
This is ready for QA:

https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/c48959/en/

**Comment by janelien** [comment]
Works for me!
