### ISSUE TITLE
decimal accuracy is all zero

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#577]
**Describe the bug**
- Why are all the indicators of the side panel all rounded to zero?
- remove the 'th' from percentile

**Comment by vim-usds** [comment]
@esfoobar-usds and @katherinedm-usds,

After decoding the PBF files it seems that the map tile data is showing indicator values with accuracy of two decimals places:

```json
  "type": "Feature",
  "properties": {
    "GEOID10": "132219601001",
    "State Name": "Georgia",
    "County Name": "Oglethorpe County",
    "Total population": 639,
    "Score E (percentile)": 0.58,  // here
    "Score E (top 25th percentile)": false, 
    "Poverty (Less than 200% of federal poverty line) (percentile)": 0.78, // here
    "Percent individuals age 25 or over with less than high school degree (percentile)": 0.71, // here
    "Linguistic isolation (percent) (percentile)": 0.26, // here
    "Unemployed civilians (percent) (percentile)": 0.6, // here
    "Housing burden (percent) (percentile)": 0.29 // here
  },
```

When converting these values to percentage (by multiplying by 100 and adding a % sign), these values will always result in a whole number with no decimal point accuracy.

We can either
1. update the pipeline to return tile map data with 3 decimal points of accuracy which when multiplied by 100 will show 1 decimal point of accuracy to reflect the designs... OR
2. change the designs to show percentage with 0 decimal values (whole number percentage) and keep the pipeline the same.. OR
3. Or maybe something else?

**Comment by esfoobar-usds** [comment]
@vim-usds can't we just cast it as a string on the frontend and display just the first decimal?

**Comment by vim-usds** [comment]
@jorge, I think so, part of this question is to help me understand what percentile value really mean.

This article seems to define it well (thx @katherinedm-usds)
> https://medium.com/statistical-guess/percentiles-98d37f327c4a

Some say percentiles are to be whole numbers and others say it could be decimal values. What are we deciding for J40?

Let's take an example, in the case of poverty = .78, what should we display? 

- just display the value exactly as is, display the poverty percentile as  `.78` (seems odd)
- drop the decimal and display poverty percentile as `78` (seems resonable, but might need a th)
- drop the decimal and suffix a _th_ and display poverty percentile as `78th` (seems reasonable)
- multiply by 10 and get one point of accuracy and display poverty percentile as `7.8` (seems odd)

**Comment by BethMattern** [comment]
@vim-usds @katherinedm-usds @lucasmbrown-usds on slack yesterday I said that the percentiles should be whole numbers but I changed my mind. I think we should "update the pipeline to return tile map data with 3 decimal points of accuracy which when multiplied by 100 will show 1 decimal point of accuracy" I don't think a whole number percentile is enough specificity.

**Comment by vim-usds** [comment]
Thx @BethMattern! 

Just to re-iterate, the recommendation is that the backend should increase the decimal accuracy to 3 decimal places. E.g. `poverty = .786`.  Then we'll display _78.6_ as the percentile value. How does that sound to you @esfoobar-usds ?

Lastly, @Beth or @katherinedm-usds: Should we add a suffix? E.g,  should it be displayed as _78.6<sup>th</sup>_ or just plain old _78_? The function to add the suffix (called [superscript ordinals](https://en.wikipedia.org/wiki/Ordinal_indicator)) is already done for english and internationalizing shouldn't be too bad (famous last words 😄 ) 

Thank you!

**Comment by BethMattern** [comment]
thanks @vim-usds! In the example above, we should display 78.6. I would love @janelien to chime in on whether or not we want to see "th" after all the values....

**Comment by BethMattern** [comment]
Final decision after discussion - we will display whole numbers (no decimals) with the appropriate suffix to represent percentiles.

**Comment by vim-usds** [comment]
Thanks @beth, @janelien @katherinedm-usds 

This ticket is available for QA review here:
https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/199d84/en/cejst/#11.35/37.1191/-84.4461

**Comment by janelien** [comment]
Looks good to me!

**Comment by glennettec** [comment]
Question: Are we using the term percentile and percentage interchangeably?

**Comment by katherinedm-usds** [comment]
@glennettec no not interchangeably, for instance if we're saying that a CBG is in the top 10th percentile of linguistic isolation and there are 300k CBGs, 90% or 290k CBGs that would have lower linguistic isolation vs. a CBG having a percent*age* level of linguistic isolation that is 90% of whatever might be the max value.
