### ISSUE TITLE
As a member of the public, I want to see J40's website live on the internet, so that I know it's real!

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#58]
**Description**
This one is all about hosting the website!

**Solution**
Deploy the website with continuous dellivery set up. This will likely be on geoplatform.gov's S3 bucket, pending #18.

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**
* Secure and set up domain (this may be a Github pages URL as an intermediary while we work on a .gov URL)
* Set up deployment and deploy

**Definition of "Done"**
* I can visit the given URL with an internet connection and see the website live!

**Comment by NatHillardUSDS** [comment]
Available for now via https://usds.github.io/justice40-tool/ , and manually uploaded for now via http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/en/ . Deployment was setup in  https://github.com/usds/justice40-tool/pull/73 .
