### ISSUE TITLE
As a developer, I want to invalidate the Cloudfront assets/content for both frontend and backend on every new deploy.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#591]
**Description**
Right now Cloudfront is not being invalidated and therefor we're using assets from previous deploys instead of the most recent. 

**Solution**
We want to do two things to mitigate this:
- set up cloudfront to invalidate every 24 hours
- modify the "deploy" github action to invalidate cloudfront on merge to main after the `Deploy to Geoplatform AWS` run step

**Describe alternatives you've considered**

**Links to user research or other resources**

**Tasks**
- [ ] configure cloudfront
- [ ] update github action

**Definition of "Done"**
We merge a PR to main and then see that change immediately reflected on the main URL.

**Comment by switzersc-usds** [comment]
Latest: We need to update our access permissions to be able to invalidate cache. In progress.

**Comment by esfoobar-usds** [comment]
Ticket created with Zivaro: https://gishelpdesk.zivaro.com/support/tickets/7243

**Comment by esfoobar-usds** [comment]
Waiting for [Zivaro ](https://gishelpdesk.zivaro.com/support/tickets/7243)to allow service accounts to invalidate.
