### ISSUE TITLE
Only run some actions when there are changes to certain directories

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#593]
We don't need to run all the actions for every commit or merge. Some things only need a backend or frontend related action.

**Comment by sverchdotgov** [comment]
This is an issue specifically for the markdown one: https://github.com/usds/justice40-tool/issues/1114

**Comment by sverchdotgov** [comment]
This isn't referencing a specific job, so I'm going to close it out.

We can always file a new ticket if there's a specific action that's running too often.
