### ISSUE TITLE
Add new prioritization scores

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#611]
Add a new score - Score G - to the system and be able to use this score in the comparison tool and display it in the UI.

The formula is very similar to a portion of the existing score F.

A census block group is considered prioritized if:
median family income does not exceed 80% of statewide median family income AND less than high school education is greater than 20%
OR
Poverty (people living at below 200% of the Federal Poverty Line) is greater than 40%
OR
Linguistic Isolation is greater than 10%
OR
Less than high school education is greater than 40%

Note that we will have to tweak the threshold percentages above in the goal of arriving at 25% of the total population being prioritized.

**Comment by switzersc-usds** [comment]
This is probably outdated; we will update this this week.
