### ISSUE TITLE
Task: Remove content from data and methodology page

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#630]
## Describe the task
The current content is not applicable and may confuse stakeholders that we're showing this to. Let's remove all content for now and just add the text "In progress" to this page. 

Note that because of version control we will be able to easily reinstate the style, content, etc of this page when we decide to bring it back. 

Note that we are leaving the page and its link in the nav bar because we want people to know we intend to put text here. 

## Acceptance Criteria

- [x] data and methodology page just says "In progress"

## Additional context

* Add any other context about the task here.
* Or here

**Comment by vim-usds** [comment]
great! This makes the heading work a little easier. 

@janelien - If possible - it would be awesome to have a quick mock up of what this might look like! Thx

**Comment by janelien** [comment]
Sure, I'm guessing this is just a header mockup?

**Comment by vim-usds** [comment]
My question is that there are 3 sections on the methodology page, should all three sections be removed (show below in magenta, blue and green) or maybe 2 out of 3 or something else? Thx!

![Screen Shot 2021-09-09 at 7.37.25 AM.png](https://images.zenhubusercontent.com/60d4d92c1bf5e498d6e808ba/ea052356-fb62-448f-a8f3-e8fa8f0144ba)

**Comment by switzersc-usds** [comment]
In the above picture, remove sections blue and green, and then change the paragraph text to the left in the magenta. @BethMattern will post what the new paragraph content should be for the magenta section.

**Comment by switzersc-usds** [comment]
Also, in the blue box, change this text to be:

The package includes the draft list of prioritized communities (.csv and .xlsx). This information should not be used to make program resource allocation decisions.

**Comment by BethMattern** [comment]
The paragraph on the left side of the magenta box should say "The methodology for determining disadvantaged communities for the purposes of Justice40 initiative is currently in progress."

**Comment by vim-usds** [comment]
@janelien 

This ticket is ready for QA:
https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/353c05/en/contact

**Comment by janelien** [comment]
Still needs removal of the text "and information about how to use the list (.pdf)" in the blue box

**Comment by vim-usds** [comment]
@janelien 

Updated here!
https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/28e994/en/methodology

**Comment by vim-usds** [comment]
@janelien 

Updated here!
https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/7dc639/en/methodology

**Comment by janelien** [comment]
Looks good to me!
