### ISSUE TITLE
Add non-score related indicators to CBG panel

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#636]
In addition to the indicators that are used in the prioritization score, users also need to see additional indicators that will help to further understand a census block group. We *do* want to show percentiles.

The additional indicators are:
- **Diabetes** - People aged 18 years or older who report having ever been told by a doctor, nurse, or other health professionals that they have diabetes other than diabetes during pregnancy.
- **Asthma** - Weighted number of people who answer “yes” both to both of the following questions: “Have you ever been told by a doctor, nurse, or other health professional that you have asthma?” and the question “Do you still have asthma?”
- **Heart disease** -  People aged 18 years or older who report ever having been told by a doctor, nurse, or other health professionals that they had angina or coronary heart disease.
- **Life expectancy** - Estimated years of life expectancy
- **Traffic proximity and volume** - The count of vehicles (AADT, avg. annual daily traffic) at major roads within 500 meters, divided by distance in meters (not km)
- **FEMA Risk Index** - Expected Annual Loss Score, which is the average economic loss in dollars resulting from natural hazards each year.
-  **DOE energy burden** - Average annual energy cost ($) divided by household income.
- **Housing cost burden** - Households that are low income and spend more than 30% of their income to housing costs
- **Wastewater Discharge** - Toxic Concentrations at stream segments within 500 meters, divided by distance in kilometers (km)	
- **Lead paint** - Percent of housing units built pre-1960, used as an indicator of potential lead paint exposure in homes
- ** Diesel particulate matter** - Diesel particulate matter level in air
- **PM2.5** - Fine inhalable particles, with diameters that are generally 2.5 micrometers and smaller

**Comment by switzersc-usds** [comment]
@BethMattern will add descriptions for these indicators. 

Design to make a new mockup to show how these should look in the sidebar.

**Comment by esfoobar-usds** [comment]
@lucasmbrown-usds @switzersc-usds can you check the list below to see if I have the indicators correct? These are what I found on the `score/full/usa.csv`:

| Indicator from list above| Indicator on score/full/usa.csv |
| --- | --- |
| Diabetes | Diagnosed diabetes among adults aged >=18 years |
| Asthma | Current asthma among adults aged >=18 years |
| Heart disease | Coronary heart disease among adults aged >=18 years |
| Life expectancy |
| Traffic proximity and volume |
| FEMA Risk Index |
| DOE energy burden |
| Housing cost burden |
| Wastewater Discharge | 
| Lead paint | 
| ** Diesel particulate matter** | 
| PM2.5 |

**Comment by switzersc-usds** [comment]
For life expectancy:: https://github.com/usds/justice40-tool/blob/main/data/data-pipeline/data_pipeline/etl/sources/cdc_life_expectancy/etl.py#18

DOE energy burden: https://github.com/usds/justice40-tool/blob/main/data/data-pipeline/data_pipeline/etl/sources/doe_energy_burden/etl.py#L23

**Comment by lucasmbrown-usds** [comment]
"Life expectancy (years)" 
"Energy burden"

**Comment by switzersc-usds** [comment]
"FEMA Risk Index Expected Annual Loss Score"

**Comment by vim-usds** [comment]
Updating the table above with info from @lucasmbrown-usds and @switzersc-usds:

Can we agree that the PBF tiles (geojson) will have their indicator values associated with keys that are named according to the 2nd column?

| Indicator from list above| Indicator on score/full/usa.csv |
| --- | --- |
| Diabetes | Diagnosed diabetes among adults aged >=18 years |
| Asthma | Current asthma among adults aged >=18 years |
| Heart disease | Coronary heart disease among adults aged >=18 years |
| Life expectancy | _Life expectancy (years)_ |
| Traffic proximity and volume | Traffic proximity and volume |
| FEMA Risk Index | _FEMA Risk Index Expected Annual Loss Score_ |
| DOE energy burden | _Energy burden_ |
| Housing cost burden | Housing burden (percent) |
| Wastewater Discharge | Wastewater discharge |
| Lead paint | Percent pre-1960s housing (lead paint indicator) |
| ** Diesel particulate matter** | Diesel particulate matter |
| PM2.5 | Particulate matter (PM2.5) |

**Comment by esfoobar-usds** [comment]
@vim-usds please hold, I'll update the list once the new score with FEMA index has been generated. To avoid confusion, please remove the table directly above. Thanks!

**Comment by lucasmbrown-usds** [comment]
| Indicator from list above| Indicator on score/full/usa.csv |
| --- | --- |
| Diabetes | Diagnosed diabetes among adults aged >=18 years (percentile) |
| Asthma | Current asthma among adults aged >=18 years (percentile) |
| Heart disease | Coronary heart disease among adults aged >=18 years (percentile) |
| Life expectancy | _Life expectancy (years)_ (percentile) |
| Traffic proximity and volume | Traffic proximity and volume (percentile) |
| FEMA Risk Index | _FEMA Risk Index Expected Annual Loss Score_ (percentile) |
| DOE energy burden | _Energy burden_ (percentile) |
| Housing cost burden | Housing burden (percent) (percentile) |
| Wastewater Discharge | Wastewater discharge (percentile) |
| Lead paint | Percent pre-1960s housing (lead paint indicator) (percentile) |
| ** Diesel particulate matter** | Diesel particulate matter (percentile) |
| PM2.5 | Particulate matter (PM2.5) (percentile) |

**Comment by esfoobar-usds** [comment]
Confirmed above list.
