### ISSUE TITLE
Change score related indicators in CBG panel

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#637]
Score G uses the following data indicators to determine if a census block group is prioritized. These data indicators should be displayed in the census block group side panel and it should be indicated that they are part of the prioritization formula.

**Area Median Income** 
The median income of the census block group calculated as a percent of the metropolitan area’s or state's median income.

**Poverty** 
The percent of households in a state with a household income below 200% of the federal poverty line. 

**Education, less than high school**
The percent of individuals who are 25 or older who have received a high school degree.

**Comment by esfoobar-usds** [comment]
@lucasmbrown-usds @switzersc-usds can you check the list below to see if I have the indicators correct? These are what I found on the score/full/usa.csv:

| Indicator from list above| Indicator on score/full/usa.csv|
| --- | --- |
| Area Median Income | Area Median Income (State or metropolitan) (min-max normalized) |
| Poverty | Percent of individuals < 100% Federal Poverty Line |
| Education, less than high school | Percent individuals age 25 or over with less than high school degree |

Please confirm these are the right ones?

**Comment by lucasmbrown-usds** [comment]
It's actually gonna be the following: 

| Indicator from list above| Indicator on score/full/usa.csv|
| --- | --- |
| Median household income as percent of Area Median Income | "Median household income (% of AMI)" |
| Poverty | "Percent of individuals < 200% Federal Poverty Line" |
| Education, less than high school | "Percent individuals age 25 or over with less than high school degree" |
