### ISSUE TITLE
Task: Ensure that download packet responds correctly on mobile

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#638]
Ensure that download packet responds correctly on mobile

**Comment by katherinedm-usds** [comment]
![IMG_6837.PNG](https://images.zenhubusercontent.com/609ab603576fa56647137b9e/92106367-26a0-4bf8-a390-ebe78e78a60b)
@vim-usds other than the amount of space the download file would take on my phone, I'd say the experience on iPhone is what I'd expect and pretty good
