### ISSUE TITLE
Remove concept of threshold communities

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#643]
The new score methodologies are threshold-based, so a census block group is either prioritized or not. Therefore, there should no longer be any mention of threshold communities. Current designs use the concept of a threshold so we should update the designs for the map and the color key to not have "threshold community". We may not need color key not but we'll still need explanation of what "prioritized" means for a CBG. TBD.

**Comment by vim-usds** [comment]
Designs have been provided by Jane

**Comment by vim-usds** [comment]
Frontend status update:
- [x] initial render of Accordion (truss)
- [x] can place two Accordions in side panel
- [x] can style background of Accordion content
- [x] replace layout of side panel with grid 
- [x] side panel snaps at 1024 (can easily change when it should snap)
- [x] can change header style of Accordion
- [x] can keep both Accordions open
- [x] Move prioritized info below CBG info
- [x] fix spacing in sidePanel
- [x] place holder data while backend provides data
- [x] intl static strings
- [x] standard style guide for all side panel typography (h's, p's, etc)
- [x] adds Tag / pill to logo

UI stuff that's left (would be great if QA added to this list! Thx)
- [ ] update legend
- [ ] mobile spacing in sidePanel needs tweeking
- [ ] fix pill / Tag on mobile

Tech debt stuff that's left (for now):
- [ ] componentize indicator card (tech debt)
- [ ] remove remaining threshold logic (tech debt see Todo)
- [ ] clean up styles (tech debt)
- [ ] move intl to another file (tech debt)


Can we get a QA on the panel?

- http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/7b8390/en/

_Any feedback on side panel?_

_How is the map's height?_

_How is the user experience with the dropdowns?_

**Comment by janelien** [comment]
Wow. I can't believe you got so much done in so little time @vim-usds!

It looks really good! The only things I noticed are:
- at around 400px the indicator name is no longer left aligned but I think you have that noted already
- with the additional indicators, the line between each indicator listed is missing, could be that we need to tweak the colors a bit so there's enough contrast

**Comment by glennettec** [comment]
@vim-usds Looks great thanks for the fast turnaround time. 
@janelien we have to address spacing for the indicators as we around "prioritized" to so that the non-indicators are completely hidden on first load.

**Comment by vim-usds** [comment]
Frontend status update:
- [x] reduce line height to 1.1 in indicator descriptions (p2 token to 2)
- [x] update legend 
- [x] add borders between additional indicators using (f3 /gray4)
- [x] update designs remove - Prioritized
- [x] main subtext on page changed
- [x] add back ordinal superscripting (easy with version control :)
- [x] clean up styles (tech debt)
- [x] mobile spacing in sidePanel needs tweeking

What's left:
- connect indicator keys to side panel (best to do this after tiles are baked)

QA requested here:
http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/25bf81/en/

**Comment by vim-usds** [comment]
frontend status update

- [x] connect indicators to backend data
- [x] render additional indicators to be open on load
- [x] update copy on About page
- [x] update copy on indicator descriptions (some tweaks might still be necessary
- [x] updated explore the tool page
- [x] updated methodology page

Shout out to Shelby for the frontend copy assist, that surely helped! 🎉 
Shout out to Jorge on getting tiles baked! 🎉 
Shout out to all that were up late! 🌙 

It would be great to have QA here:
http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/007e80/en/

For copy changes please see the "Living copy of J40" on our shared drive. There are some ideas on how to use this.
