### ISSUE TITLE
Get most up to date final-est PDF for package

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#678]

**Comment by katherinedm-usds** [comment]
Here's Kameron's note on the attached Draft_Communities_List_V7 she provided on Friday 9/17[https://app.zenhub.com/files/358242767/42e05319-d39b-45b5-9917-8d1f1df6998c/download](https://app.zenhub.com/files/358242767/42e05319-d39b-45b5-9917-8d1f1df6998c/download) @BethMattern could you please review?

> Multiple updates to the pdf content based on CEQ review, final approvals not yet. Attached are current files that reflect the latest sent to CEQ (and what I am hopeful is actually final) in doc, ai, and pdf format. If the OK is given then this is the pdf version to give to jorge.

**Comment by katherinedm-usds** [comment]
@esfoobar-usds though this won't be the final PDF, could you please add this version https://app.zenhub.com/files/358242767/42e05319-d39b-45b5-9917-8d1f1df6998c/download which Kameron provided Friday September 17th? 

(more comments came in over the weekend from CEQ legal but that may take a little while to update, and more comments/updates might come in. But would be good to just ensure something somewhat representative is there)

**Comment by KameronKerger** [comment]
@esfoobar-usds latest updates based on "final edits" from Sharmila and MLA...
[Draft_Communities_List_V8.pdf](https://github.com/usds/justice40-tool/files/7213109/Draft_Communities_List_V8.pdf)

**Comment by esfoobar-usds** [comment]
@KameronKerger @katherinedm-usds can you check if the live site's download packet looks good to you?

**Comment by KameronKerger** [comment]
I got the .csv and the .xls but no .pdf @esfoobar-usds

**Comment by esfoobar-usds** [comment]
That is strange. I got the 3 files (csv, excel and pdf) on my Windows machine. The automatic unzipping could be Safari, can you try another browser?

**Comment by esfoobar-usds** [comment]
Just tried on my OMB MacBook Pro and the same -- got the 3 files.

**Comment by KameronKerger** [comment]
safari no zip two files
chrome zip two file
<img width="776" alt="Screen Shot 2021-09-23 at 11 47 14 AM" src="https://user-images.githubusercontent.com/77702996/134566217-b69fe7e7-5546-45af-aa7f-94377f381e00.png">
<img width="567" alt="Screen Shot 2021-09-23 at 11 47 55 AM" src="https://user-images.githubusercontent.com/77702996/134566226-1a6b3fe9-a210-4fc5-ae7a-2e2248caac24.png">
s

**Comment by esfoobar-usds** [comment]
I think this is a caching issue, let me do a cloudfront invalidation

**Comment by esfoobar-usds** [comment]
@KameronKerger can you try again?

**Comment by KameronKerger** [comment]
looks good @esfoobar-usds - safari still unzipped it automatically but all three files are in there now.
