### ISSUE TITLE
Load census data for the 4 territories (e.g., the CSVs with income data)

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#723]
The data for the Island Areas is collected through the Decennial Census of Island Areas.  

Each individual territory has its own Summary File, but it's not SF1. 

There's the American Samoa Summary File, the Guam Summary File, the Commonwealth of the Northern Mariana Islands Summary File, and the US Virgin Islands Summary File:

* https://api.census.gov/data/2010/dec/as.html
* https://api.census.gov/data/2010/dec/gu.html
* https://api.census.gov/data/2010/dec/mp.html
* https://api.census.gov/data/2010/dec/vi.html

It looks like some of these have a separate Year of Entry File available. I did a quick check and it looks like the data is available down to the block level.

We would want to load income and high school graduation variables to start. 

This includes just adding these as data sources for the ETL and their associated tests, not adding to the score and file generation.

**Comment by switzersc-usds** [comment]
@lucasmbrown-usds @VincentLaUSDS @esfoobar-usds lt's touch base about this today or tomorrow on slack
