### ISSUE TITLE
Determine best approach for collecting responses to PRA approved customer satisfaction survey

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#725]

**Comment by BethMattern** [comment]
@KameronKerger is going to clarify/confirm that USDS can host the survey and collect the responses and exactly what "burden to EPA" means

Long term we are recommending that CEQ apply for their own generic PRA clearance - @KameronKerger and @lucasmbrown-usds are providing them with some guidance about the types of things we would want to colled & the justifications

**Comment by katherinedm-usds** [comment]
There's just one outstanding issue @KameronKerger will discuss with @vim-usds regarding whether the header could be put into the separate tab version of the survey, but we can track that separately
