### ISSUE TITLE
Add approved wording about US territories to UI

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#735]
Until we are able to incorporate the US territories (American Samoa, Guam, the Commonwealth of the Northern Mariana Islands, and the US Virgin Islands) we need to address the fact that they aren't included in the UI.

**Definition of Done**
- [ ] Determine where wording should appear in UI
- [ ]  Determine exact wording for each location
- [ ] Create tasks for dev team to implement

Approved wording:
A note on US territories 
The data sources powering the screening tool are often drawn from the Census’s American Community Survey, which collects data for all 50 states, the District of Columbia, and Puerto Rico. 

There is not currently data in the tool that maps the lived experiences of the approximately 375,000 residents of the remaining US territories: American Samoa, Guam, Northern Mariana Islands, and the Virgin Islands of the United States. 

However, the team is working diligently to provide an updated methodology that identifies communities of focus in these territories, as an update to the current beta methodology of communities of focus. The initial focus will be on using data collected from these four territories during the 2010 Census and relevant to income and education levels, similar to the formula used using ACS data.

**Comment by katherinedm-usds** [comment]
@KameronKerger presented 3 options, we can suggest both option 2 (below map) and 3  (data page, CEQ's preference). We ruled out additional option of note text going under "Did you know?" next to/under map.

**Comment by switzersc-usds** [comment]
Waiting to hear on preference for mocks; should know by tomorrow. Once we have mock option selected, we can move forward on dev.

**Comment by KameronKerger** [comment]
![Option1_below_map (1)](https://user-images.githubusercontent.com/77702996/136252597-948f25d9-d51c-4b77-8f63-f4eb6f68cbec.png)
![Option2_below_methodology (1)](https://user-images.githubusercontent.com/77702996/136252601-2ef731a2-6e2d-409f-8b21-7d1710aedde3.png)

**Comment by BethMattern** [comment]
@KameronKerger @katherinedm-usds if we are able to incorporate all territories using the older ACS data, this wording will change. We should hold on this until the territory work is done.

**Comment by switzersc-usds** [comment]
Closing this as it will be covered in the copy updated coming up.
