### ISSUE TITLE
Modify Banner to have English and Spanish links

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#747]
Tasks
- look into modify the Banner component
- understand how to switch
- integrate fully flushed out es.json
- is there such a thing as snapshot testing in Spanish?
- investigate ordinal value translation into Spanish
- mobile view has to move Eng and Spanish links to menu button

**Comment by katherinedm-usds** [comment]
Would it be possible for us to create an updated placeholder es.json with a complete set of fields (albeit without fully translated text, until we get translations from DoS?

**Comment by switzersc-usds** [comment]
epic is #184

**Comment by vim-usds** [comment]
Task update:

- [x] get language selection links to work
- [x] re-style header to match mock
- [ ] componentize gov header
- [ ] add world icon
- [ ] refactor styles to USWDS tokens
- [ ] test gov banner expand on desktop / mobile
- [ ] ensure language links display and work correctly on mobile
- [ ] align vertically to Site logo
- [ ] re-align beta banner to Site logo
- [ ] add unit tests
