### ISSUE TITLE
Update 404 page content

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#760]
## Describe the task
Design to confirm content and home link if applicable for 404 page, which currently https://screeningtool.geoplatform.gov/en/404/ says "Sorry 😔 we couldn’t find what you were looking for. Go home." with "Go home" linking to https://screeningtool.geoplatform.gov/en/. 

## Acceptance Criteria
- [ ] text and link if applicable for Dev to incorporate into 404 page

## Additional context

* Add any other context about the task here.
Example content Glennette had shared on [Slack](https://usds.slack.com/archives/C0222FBGQ65/p1632941177026400)

Airtable - https://airtable.com/a
> Sorry, the page you were looking for was not found.
> Return home or get some help.

Google - https://www.google.com/a
> 404. That’s an error.
> The requested URL /a was not found on this server. That’s all we know.

USWDS 404 template - https://designsystem.digital.gov/templates/404-page/

USWDS - https://designsystem.digital.gov/templates/404/
> 404 / Page not found
> You might want to double-check your link and try again, or return to the homepage.
> This is a default 404 page for Federalist, a hosting service for federal websites.

**Comment by vim-usds** [comment]
http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/974-22993b7/en/cejst/#3/32.47/-86.5
