### ISSUE TITLE
Typos on Explore the tool

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#768]
**Describe the bug**
Explore the tool has a couple very minor typos under "How you can help improve the tool" 

- the link "recieve an email from you" should be "receive an email from you"
- the link "Data and methodology" should be "Data & methodology"

**To Reproduce**
1. Go to https://d29zfl8cj7y1zf.cloudfront.net Explore the tool
2. See the text under "How you can help improve the tool"

**Expected behavior**
"recieve" should be spelled "receive", "Data and methodology" should be "Data & methodology" to be consistent with how this is written elsewhere on the site

**Screenshots**
![image (3).png](https://images.zenhubusercontent.com/609ab603576fa56647137b9e/95f80ef0-84d6-4301-89cd-bfe41f7b96f5)

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: any

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser: any
 - Version: any

**Additional context**

**Comment by vim-usds** [comment]
QA requested here, Thank you!

https://github.com/usds/justice40-tool/pull/803
