### ISSUE TITLE
Task: Design for where PRA compliant survey can be accessible on CEJST

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#771]
## Describe the task
@KameronKerger provide design mockup for where the PRA compliant survey to collect feedback can be accessed by visitors to the CJEST site

## Acceptance Criteria
- [ ] Design mockups provided to dev with placeholder survey questions

**Comment by KameronKerger** [comment]
the actual survey questions (which we have) will be hosted in USDS' survey tool provider @glennettec (surveymonkey). The task is to design where the survey is accessed / linked from which I have on my todo list.

**Comment by KameronKerger** [comment]
<img width="1003" alt="Screen Shot 2021-10-21 at 9 37 40 AM" src="https://user-images.githubusercontent.com/77702996/138320459-501a4d9d-7019-407a-97b8-433e1f04593b.png">

**Comment by katherinedm-usds** [comment]
We decided separate tab implementation is acceptable for launch
