### ISSUE TITLE
Task: ensure links on Spanish version of site link to the Spanish versions of internal/external links  

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#773]
## Describe the task
This is issue is to specify where possible or optimal links in the \es version of CEJST should link to specifically Spanish versions of internal or external links.

## Acceptance Criteria

Header
 - [x] Top nav menu items go to Spanish version of site
 - [x] U.S. government "Here’s how you know" (or rather, the equivalent in Spanish) drop down expands to Spanish version of explanatory text

From About
 - [ ] "Executive Order 14008 on Tackling the Climate Crisis at Home and Abroad." remains in English (to be confirmed, though DoS translation team confirmed EOs don't get translated)
 - [x] "Whitehouse.gov" links to whitehouse.gov/es
 - [x] "Política de Privacidad" (Privacy Policy" links to https://www.whitehouse.gov/es/privacidad/
 - [x] "Find a contact at USA.gov" (or rather, the equivalent in Spanish) links to https://www.usa.gov/espanol/
- [ ] ~"Take our survey" links to the \es version of the survey (design and implementation of survey still TBD)~ moved to survey ticket

Internal links on About:
 - [x] "Go to data & methodology" (or rather, the equivalent in Spanish) links to \es version of that page
 - [x] "Explore the tool" (or rather, the equivalent in Spanish) links to \es version of that page

Internal links on Explore the tool
 - [x] "Data & methodology" (or rather, the equivalent in Spanish) links to \es version of that page

Internal links from Data & methodologies
- [ ] ~"Take our survey" links to the \es version of the survey (design for survey still TBD)~ moved to survey ticket
- [ ] additional text (exact text TBD) explaining that data is not available in Spanish, i.e. "Los datos no están disponibles en español" added to data cards

## Additional context
* Note, none of the links in the main body of the Data & methodology page (when translated to Spanish) have a Spanish language equivalent to link to
* Currently, the body of the Contact page has no links to consider (only has the email address, and may switch to a correspondence management system form.

**Comment by katherinedm-usds** [comment]
@KameronKerger I was hoping to have your review on this just to make sure I didn't miss any internal or external Spanish version links that we should make sure the Spanish translated version of CEJST pages should link to.

**Comment by KameronKerger** [comment]
@katherinedm-usds also need 

(about page)
[ ] take our survey links to the \es version of the survey

(data and methodologies page)
[ ] take our survey links to the \es version of the survey

all pages
[ ] us government website dropdown is in Spanish
[ ] Menu and other nav labels are in Spanish

do we want to add a note to cover the data links not being available in Spanish? something like (not available in Spanish (but in Spanish)) maybe after "the variety of sources" in the main body text.

also is there anyway to tell the browser that the person is viewing \es (I think there is) so that messages that are shown, like on Safari for example, do request download permissions the text is in Spanish.

**Comment by switzersc-usds** [comment]
epic is #184

**Comment by vim-usds** [comment]
@katherinedm-usds and @KameronKerger 

to reduce scope on this ticket, I would like to suggest we move all survey related tasks into the survey ticket #813

**Comment by vim-usds** [comment]
@katherinedm-usds ,

Can you expand on this?

Internal links from Data & methodologies
- additional text (exact text TBD) explaining that data is not available in Spanish, i.e. "Los datos no están disponibles en español" added to data cards
