### ISSUE TITLE
Add version number to the download link label on the Explore the tool page

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#778]
Text should read:

Download the draft v.0.1 list of communities of focus and datasets used. Last updated: 10/01/21.

**Comment by BethMattern** [comment]
Version number should be here to be consistent with the wording on the download link on the data and methodology page.

The text should read: "Download the draft list of communities of focus and datasets used. v.0.1 last updated: 10/01/21.

**Comment by BethMattern** [comment]
Text should read:

Download the draft list of communities of focus and datasets used. Version 0.1 last updated 10/01/21.

**Comment by KameronKerger** [comment]
<img width="598" alt="Screen Shot 2021-10-06 at 10 11 55 AM" src="https://user-images.githubusercontent.com/77702996/136251553-bc259df0-ecc5-45e8-a4e0-8951ca7a9ed5.png">
