### ISSUE TITLE
Research design for change log

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#779]
Determine how we want to present the change log to users of the tool, as well was what information should be contained in the change log.

Eg https://wiki.ubuntu.com/Releases 

- Change log should be stored as markdown in code base, but can be rendered in another format in download package if we want
- We should frame content for both FPOs and community members
- We would want to have the Change log in Spanish as well, for download and on the webpage. Maybe this is one file or two separate files in the download. Need to talk through how to use this as markdown in our internationalization workflow for the front end.

**Comment by katherinedm-usds** [comment]
track in #780
