### ISSUE TITLE
Design for displaying change log on website

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#780]
Subtasks
- [ ] research best practices as described in now closed/combined https://github.com/usds/justice40-tool/issues/779 
- [ ] Design for website should pull directly from markdown change log (so content should be the same) but formatting/styling can be different
- [ ] Think holistically about displaying/communicating change and if we want multiple pages 
- [ ] How should the change log be included in the download packet?

**Comment by katherinedm-usds** [comment]
@KameronKerger (who is having computer issues atm) will add links to other sites we can reference for this design

**Comment by katherinedm-usds** [comment]
High priority for right after launch, should go into icebox

**Comment by KameronKerger** [comment]
kinda? yes, closing.
