### ISSUE TITLE
[SPIKE] Speed up cypress tests with parallelization

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#789]
PR #800 in place that starts this

- [ ] Look into ways to speed it up
- [ ] install cucumber autocomplete to VS code
- [ ] best practices around file naming
- [ ] add cross browser testing (and maybe mobile?)

Some of the things to think about here:

- Parallelization seems to reduce GHA action execution time by ~20%
- Cypress dashboard has been integrated and required for parallelization
- Currently we have 43 tests. This is just for Chrome. Adding firefox would double this to 86, adding a mobile test would multiply by 3 to 129. The cypress dashboard (Free tier) allows for 500 tests runs per month. If a single PR is opened and 5 commits are pushed to it, this will run 43 * 5 times which would use up 1/2 of the monthly quota. Need to investigate if there's a way to cache or not run tests that haven't changed or some smarter way to.
- Need to find the right balance of parallelized tests (limit of 500/mo) and local tests (unlimited)

**Comment by vim-usds** [comment]
Some motivation:

![Screen Shot 2021-10-08 at 12.25.00 PM.png](https://images.zenhubusercontent.com/60d4d92c1bf5e498d6e808ba/b560e81d-70e7-4b01-af5b-bf3f08a8698a)

**Comment by vim-usds** [comment]
Some of the things to think about here:

- Parallelization seems to reduce GHA action execution time by ~20%
- Cypress dashboard has been integrated and required for parallelization
- Currently we have 43 tests. This is just for Chrome. Adding firefox would double this to 86, adding a mobile test would multiply by 3 to 129. The cypress dashboard (Free tier) allows for 500 tests per month.
- Need to find the right balance of parallelized tests (limit of 500/mo) and local tests (unlimited)

Meeting with Cypress sales rep for options, however may just pause on parallel tests for now and build times may increase.

**Comment by switzersc-usds** [comment]
Closing this as the spike is finished. @vim-usds will write an ADR explaining the decision about parallization.
