### ISSUE TITLE
Show territories on the map

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#805]
These 4 territories are shown on the map and use a different set of data for the score:

- American Samoa Summary (AS)
- Guam (GU)
- Commonwealth of the Northern Mariana Islands (MP)
- US Virgin Islands (VI)

The territories may not have all of the data that is available for the 50 states, so some data in the tract details panel will be missing. How do we handle this?

Finally - all of the territories except Puerto Rico will be using ACS data from 2010, because that is the last time this data was made available. Does this need to be called in in the UI? If so where?

Re: display for these territories, right now we are showing these with the long list of shortcuts. We will eventually have new design for the list of shortcuts.

**Comment by switzersc-usds** [comment]
Recap of convo:
- we want to see what the data actually looks like after dev adds score calculation for territories (that is a new issue)
- we want content change as well as map UI changes (eg adding buttons to zoom to territories, or a new experience). there is a separate issue for content.
- beth is adding details to this issue about what we've discussed as stuff to consider (eg zoom buttons, what info we need to display)
- design does not have bandwidth this week to think about this

**Comment by BethMattern** [comment]
Updates to details complete

**Comment by glennettec** [comment]
mockups for displaying territories on the map + search bar

![Explore the tool_sidebar.png](https://images.zenhubusercontent.com/60e71e455052ef541fcc40c3/bf79bc98-8773-42df-bd91-6e55a2c3869a)

![Explore the tool_show indicators.png](https://images.zenhubusercontent.com/60e71e455052ef541fcc40c3/6530cdda-a5fd-4d2e-9ea7-982fa21f3414)

**Comment by katherinedm-usds** [comment]
this interim design should be ready for @vim-usds to implement

**Comment by katherinedm-usds** [comment]
@KameronKerger will sync up with @vim-usds on a potential design for territory shortcuts for mobile

**Comment by BethMattern** [comment]
@KameronKerger and @vim-usds - seems like this can be closed now that we've decided what to do with the territories?

**Comment by vim-usds** [comment]
agreed!
