### ISSUE TITLE
EJSCREEN areas of concern data pull request - data shouldn't be available publicly

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#823]
From Lucas:
There’s a lingering PR from vincent based on a file we can’t put out publicly, we need to decide what to do with it. if we merged that code anyone who doesn’t have the file would have the score process fail when they run it.

The best approach is probably to just add a bunch of “if / else” logic to check if the file exists and load it if it does, so we can merge the code. but we need to think about it a lil bit and make a decision

**Comment by switzersc-usds** [comment]
We can take a similar approach as the census tract data and use secrets for now.
