### ISSUE TITLE
Change data sources to use tract level data

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#836]
The following data sources do also provide data at the tract level, but we’ll need to update the logic of how we access and process that data to make the switch: 

- Census ACS. We access this with a library; we should find out if this library lets us get data at tract level; if not, it will be much more work.
- Census AMI 
- Census island territories 
- GeoCORR urban/rural
- County mapping to census block groups 

Note: Some of these are just used in the comparison tool, not the map.

**Comment by switzersc-usds** [comment]
Broke this up into multiple cards
