### ISSUE TITLE
Update side panel in map UI and export file to show indicators used in methodology

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#856]
**Big ole issue**
This represents all final changes to the side panel data AND the CSV in the export file. We are closing #857 and that work is represented here. This will all be done once we get the final go ahead from powers that be. The final word for what should be present is being tracked in Vim's spreadsheet called "Indicators on Side Panel" (which includes CSV data fields despite the name).

**Comment by vim-usds** [comment]
@BethMattern will these indicators fall into primary and additional ? If so, can it be specified which one is which? Thx

**Comment by BethMattern** [comment]
@vim - all of these indicators will be primary

**Comment by vim-usds** [comment]
@BethMattern Thx!

@esfoobar-usds, I don't see these in the map tiles yet. Is it true that these indicators have to baked in?

**Comment by esfoobar-usds** [comment]
Side panel changes are related to the frontend, so @vim-usds needs to kickstart a frontend change and deploy.

**Comment by vim-usds** [comment]
I think so, this is what I currently see in the decoded PBF (geo-json files):

```json
       "properties": {
            "GEOID10": "190150203002",
            "State Name": "Iowa",
            "County Name": "Boone County",
            "Total population": 2079,
            "Score D (percentile)": 0.33,
            "Score D (top 25th percentile)": false,
            "Score E (percentile)": 0.28,
            "Score E (top 25th percentile)": false,
            "Score G (communities)": false,
            "Score G": 0,
            "Definition L (communities)": false,
            "Definition L (percentile)": 0,
            "Poverty (Less than 200% of federal poverty line) (percentile)": 0.49,
            "Percent individuals age 25 or over with less than high school degree (percentile)": 0.09,
            "Linguistic isolation (percent) (percentile)": 0.61,
            "Unemployed civilians (percent) (percentile)": 0.18,
            "Housing burden (percent) (percentile)": 0.44,
            "Diagnosed diabetes among adults aged >=18 years (percentile)": 0.33,
            "Current asthma among adults aged >=18 years (percentile)": 0.23,
            "Coronary heart disease among adults aged >=18 years (percentile)": 0.54,
            "Life expectancy (years) (percentile)": 0.99,
            "Traffic proximity and volume (percentile)": 0.24,
            "FEMA Risk Index Expected Annual Loss Score (percentile)": 0.57,
            "Energy burden (percentile)": 0.46,
            "Wastewater discharge (percentile)": 0.78,
            "Percent pre-1960s housing (lead paint indicator) (percentile)": 0.52,
            "Diesel particulate matter (percentile)": 0.38,
            "Particulate matter (PM2.5) (percentile)": 0.29,
            "Median household income (% of AMI) (percentile)": 0.55,
            "Percent of individuals < 200% Federal Poverty Line (percentile)": 0.51
          },
```

This leads me to believe that the following may need to be added:
- Expected annual loss rate (percentile)
- Proximity to RMP sites (percentile)
- Proximity to NPL sites

**Comment by esfoobar-usds** [comment]
Ok, let me get on this. @BethMattern this is a bit unexpected work on the data pipeline side and we have no ticket to track this work, so I'll reference this ticket on my PR.

**Comment by esfoobar-usds** [comment]
@vim-usds opened a PR here: https://github.com/usds/justice40-tool/pull/866

**Comment by esfoobar-usds** [comment]
Ok, looks like this is failing at score post because those two indicators aren't being written to the score/full/usa.csv.

```
KeyError: "['Expected annual loss rate (percentile)', 'Proximity to RMP sites (percentile)'] not in index"
```

@lucasmbrown-usds do you have context on this?

**Comment by katherinedm-usds** [comment]
just confirming, not sure who would know @esfoobar-usds - in the Excel/CSV spreadsheet, instead of "GEOID10" the column name will be "Census Tract ID"?
