### ISSUE TITLE
Update methodology page (and translate)

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#861]
Update Data & methodology page to reflect Score L, content has been sent to Corey for review but no confirmed ETA for approval yet
- [x] Update for high level description under "Methodology"
- [x] Updates for download packet section
- [x] Updates for datasets (in addition to updated indicators, now there's no "Additional Indicators" section needed)
 - [x] Updates to Methodology, in particular to make it easier for people to conceptualize Score L
- [x] Update to download package copy re: version, size, etc
- [ ] Add translation

**Comment by BethMattern** [comment]
Copy is is "Draft Revised Methodology score L" document.

**Comment by switzersc-usds** [comment]
We now have mocks for this that we can use to begin coding. We expect any changes in the future to be textual, not layout.

**Comment by KameronKerger** [comment]
![Methodology_score_L_updated](https://user-images.githubusercontent.com/77702996/143961254-2f8ca43a-db2e-4ce8-82ff-3d97b6f8aae7.png)

**Comment by KameronKerger** [comment]
![Methodology_score_L_updated2](https://user-images.githubusercontent.com/77702996/144289858-bbb3412f-0912-4db6-a301-c0a583dd89a7.png)
