### ISSUE TITLE
Changes to excel export file based on user research sessions

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#865]
Changes in priority order:
1. Update all column names - names will be in the spreadsheet
2. Change precision of numbers:
- percentile columns will show whole numbers converted to percentile (example: 92)
- raw value numbers will be to 2 decimal places
3. Add Region, state/territory, county name
4. Sort - region starting with one, then state within the region (alphabetized), then county within state (alphabetized), then Yes/NO (yes first) then census tract ID numerically 
5. Reorder columns - order will be in spreadsheet
6. Additional tabs for methodology, data dictionary in .xlsx and flat files for .csv users
7. Include a total count of threshold yes's
8. Include yes/no for each threshold

**Comment by katherinedm-usds** [comment]
Was opened as a placeholder, will be @KameronKerger and @glennettec meeting more about this, @KameronKerger already started working on this and shared a draft version on Slack

**Comment by katherinedm-usds** [comment]
@KameronKerger shared in Slack an Excel spreadsheet she mocked up with changes that could help make it more usable https://usds.slack.com/archives/C01LA9YLNE9/p1637791570116800

**Comment by KameronKerger** [comment]
updated version based on recent changes to the methodology / desire to homage cumulative impact 

[communities-abrg.xlsx](https://github.com/usds/justice40-tool/files/7644104/communities-abrg.xlsx)
