### ISSUE TITLE
Scrolling side to side causes census block group boundaries to cycle on / off

### ISSUE THREAD

**Issue by KameronKerger** [usds/justice40-tool#889]
**Describe the bug**
When you scroll side to side the block group boundaries appear to disappear and then reload causing an unstable and rapid cycling visual appearance. 

**To Reproduce**
1. Go to 'explore the tool'
2. Click on 'map'
3. Zoom down to 'x zoom level'
4. Scroll side to side

**Expected behavior**
The census block group boundaries remain stable as you scroll.

**Screenshots**
Video screenshots or ask Kameron to play video

<img width="386" alt="Screen Shot 2021-11-12 at 1 51 04 PM" src="https://user-images.githubusercontent.com/77702996/141538886-6ea78d5d-451b-4397-b85d-55a01a788535.png">
<img width="391" alt="Screen Shot 2021-11-12 at 1 51 14 PM" src="https://user-images.githubusercontent.com/77702996/141538890-42aef4ee-5805-4143-b5d8-818b09044f93.png">
<img width="396" alt="Screen Shot 2021-11-12 at 1 51 23 PM" src="https://user-images.githubusercontent.com/77702996/141538892-b83dd954-517d-4e98-a1a8-661a262a7e76.png">
<img width="398" alt="Screen Shot 2021-11-12 at 1 51 32 PM" src="https://user-images.githubusercontent.com/77702996/141538898-38577342-8ff9-4c34-9a27-1a2ce38f9976.png">

**Desktop (please complete the following information):**

OMB Laptop

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vim-usds** [comment]
@KameronKerger - I'm unable to reproduce this. I think we can close?
