### ISSUE TITLE
Unexpected response when running command: poetry run python3 data_pipeline/application.py data-full-run

### ISSUE THREAD

**Issue by ahlusar1989** [usds/justice40-tool#893]
**Descrption**

Unexpected response for FIPS Code 66 (Guam) 

**To Reproduce**

1. Go to [Local Development Directions for Setup](https://github.com/usds/justice40-tool/blob/main/data/data-pipeline/README.md#local-development)
2. Execute all steps up to and including **Run both ETL and score generation processes**
3. Be patient and wait until.....
4. See error (attached)

ETL and score generation processes should complete successfully

**Screenshots**

<img width="1389" alt="Screen Shot 2021-11-14 at 7 49 18 AM" src="https://user-images.githubusercontent.com/7760225/141682044-45e36183-46d4-4199-8d90-4d6d9acfaafd.png">

**Desktop (please complete the following information):**
 - OS: MacOS, Big Sur 11.6
 - Python Version: 3.7.4
 - data-pipeline 0.1.0
 - Poetry version 1.1.11
 
**Additional context**
The same error  is thrown when the following is excuted:` poetry run python3 data_pipeline/application.py etl-run`

**Comment by switzersc-usds** [comment]
Thanks for reporting this bug! I believe this has been fixed by #885 which I merged this morning. We are seeing this now successfully run on Github Actions, and I've run it successfully locally. Please pull the latest `main` and try again, and let us know if you're still seeing issues!

**Comment by ahlusar1989** [comment]
@switzersc-usds It looks like the error checks and exception handling handled the case that was raised. I am closing this.
