### ISSUE TITLE
[SPIKE] Scope work to integrate Nominatim search for searching on the map

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#895]
# Summary
We would like to integrate BOTH a free/open source search component and a more robust search component into the CEJST map. We should scope the work to integrate Nominatim and another to be determined paid service. We would plan on making the paid search available on the CEJST public site.

Here is the research done to date on options:
https://github.com/usds/justice40-tool/issues/402

## Dev Tasks
What will trigger the app to switch from one solution to the other?

API
- [x] understand query params and options for sending data to Nominatum API
- [ ] understand various ways the return data can be sent
- [ ] data-fetch client investigation, `axios` vs `swr` vs `fetch` vs `react-query`

Search UI component
- [x] display the search field
- [x] truss has a search component with intl - limited options on what to display
- [x] can trigger action on search
- [ ] trigger Nominatum on search
- [ ] intl search button text (if that UI component is chosen)
- [ ] search should be disabled if service is down via `/status` endpoint
- [ ] place this behind a feature flag
- [ ] loading screen? nice to have
- [ ] typeahead? nice to have
- [ ] cache historical searches? nice to have

Map
- [x] pan map pan based on lat/long
- [ ] pans based on search

**Comment by vim-usds** [comment]
Tasks

API
- [ ] understand query params and options for sending data to Nominatum API
- [ ] understand various ways the return data can be sent

Search UI component
- [ ] display the search field
- [ ] typeahead? Make this optional
- [ ] truss has a search component with intl 

Map
- [ ] once payload is received how should the map pan to results?

**Comment by BethMattern** [comment]
I also like the small variant option.

For placeholder text, I would suggest "Find address or place" 

As for the query versus structured search, @katherinedm-usds has a good list of search terms that we can test and compare results.

@KameronKerger @glennettec @katherinedm-usds open to discussion on this, obvs.
