### ISSUE TITLE
Implement latest copy

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#908]
Any changes to any page other than Methodology and Data page. The copy is in the source of truth word doc "Living Copy of J40"

Also knock out a quick copy update to the 404 page (linked)

**Comment by vim-usds** [comment]
http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/974-22993b7/en/cejst/#3/32.47/-86.5
