### ISSUE TITLE
Add shortcuts for territories on map

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#910]
For MVP, we want to make sure territories are included and easy to navigate to. For now, let's add shortcuts in the same pattern we already have. Very soon we will update this with new designs so that we don't have one long list of shortcuts slapped to the side of the page. We know that this will also cause a poorer experience on mobile, hence prioritizing improving this very soon after adding the initial shortcuts.

The territories are 
- Puerto Rico (PR) already implemented
- Guam (GU)
- American Samoa (AS)
- Commonwealth of Northern Mariana Islands (MP)
- US Virgin Islands (VI)

**Comment by vim-usds** [comment]
Use #805 to as more info
