### ISSUE TITLE
FEMA_COMMUNITIES constant not previously defined and results in exception when running comparison tool

### ISSUE THREAD

**Issue by ahlusar1989** [usds/justice40-tool#914]
**Describe the bug**

FEMA_COMMUNITIES variable is not previously defined.

**To Reproduce**

In the following comparison tool notebook [notebook](https://github.com/usds/justice40-tool/blob/main/data/data-pipeline/data_pipeline/ipython/scoring_comparison.ipynb)

There is a variable, FEMA_COMMUNITIES, that does not appear to be used in any of the Index named tuples.
One can find this variable by searching (CMD + F) and enter into the search field FEMA_COMMUNITIES. 

One will notice it is defined as a keyword argument but not previously set.

**Expected behavior**

Workflow should output comparison tool without any exceptions

**Desktop (please complete the following information):**
 - OS: MacOS, Big Sur 11.6
 - Python Version: 3.7.4
 - data-pipeline 0.1.0
 - Poetry version 1.1.11

**Comment by lucasmbrown-usds** [comment]
Good catch @ahlusar1989 -- that was introduced by [this PR](https://github.com/usds/justice40-tool/pull/892/files), and we just need to delete that index. 

Deleting the lines: 

```
        Index(
            method_name=FEMA_COMMUNITIES,
            priority_communities_field=FEMA_COMMUNITIES,
            other_census_tract_fields_to_keep=[],
        ),
```

Should do the trick. Want to open a PR? Thank you!!

**Comment by ahlusar1989** [comment]
@lucasmbrown-usds sure thing - thanks for confirming and for clarifying.
