### ISSUE TITLE
As a data developer, I want to make updates to the FEMA measures, so they more accurately capture climate change risk.

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#920]
**Description**
Two tasks related to FEMA risk index. Data dictionary available online or here: [NRIDataDictionary.csv](https://github.com/usds/justice40-tool/files/7597458/NRIDataDictionary.csv).

~~First, drop the buildings and agriculture measures from Definition L, just leaving behind population (injuries and fatalities).~~

First, update to point to the *new* data we got from FEMA. 

Recalculate the measures in FEMA risk index to only include those natural disasters that have been linked in any association with climate change. So this means removing the following disaster types: 

* Earthquake 
* Tsunami
* Volcano 
* Lightning 

For all remaining disaster types, calculate a single combined population risk rate with the following formula: 
    
    numerator: the sum of each field "{disaster type}  - Expected Annual Loss - Population" such as field `AVLN_EALP`.
    
    denominator: "Population"

For all remaining disaster types, calculate a single combined agriculture value risk rate with the following formula: 

    numerator: the sum of each field "{disaster type}  - Expected Annual Loss - Agricultural Value" such as field `DRGT_EALA`.
    
    denominator: "Agricultural Value ($)" aka `AGRIVALUE`

For all remaining disaster types, calculate a single combined building value risk rate with the following formula: 

    numerator: the sum of each field "{disaster type}  - Expected Annual Loss - Building Value" such as field `EAL_VALB`.
    
    denominator: "Building Value ($)" aka `BUILDVALUE`

We may not use all of these, but we should go ahead and calculate them.

Note that not every disaster type has every loss type. E.g., avalanche may not have an agricultural value measure. This is fine and it can just be skipped.

**Comment by lucasmbrown-usds** [comment]
See https://github.com/usds/justice40-tool/pull/884/files#diff-1d736b03da36f353fae412a315e4a0d2379f40566b6f84c6eefbf1cef3760ed5L80 for an example of how to iterate through a list of the field names.

**Comment by switzersc-usds** [comment]
@lucasmbrown-usds just want to confirm - this is different from #883 and is still open?

**Comment by lucasmbrown-usds** [comment]
And yes, different than #883! That was round of updates v1, this is v2 😄

**Comment by ahlusar1989** [comment]
PR is [here] (https://github.com/usds/justice40-tool/pull/952).
