### ISSUE TITLE
As a score developer, I want to list the thresholds exceeded by a community in Definition L.

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#921]
**Description**
Right now definition L produces a single binary output variable. 

In addition to that, we want to identify the individual thresholds exceeded by a census tract. 

By individual threshold, we mean a criteria like `diabetes >= 90th percentile AND % low income >= 65th percentile`. For categories with more than one criteria in them, like health burdens which contains criteria related to diabetes, asthma, heart disease, and life expectancy, each criteria will be handled individually

Whether or not a census tract exceeds a threshold will need to be included in the .xls file, so there will need to be a column with a yes/no value for each individual threshold.

Design is still considering how this might be visualized in the UI.

List of all thresholds:
Climate Change:
- IF at or above the 90th percentile for FEMA’s expected population loss rate AND is low income 

Clean Energy and Energy Efficiency:
- IF at or above the 90th percentile for energy cost burden score And is low income
- PM2.5 and is low income 

Clean Transportation: 
- IF at or above the 90th percentile for diesel particulate matter And is low income
- traffic proximity and volume And is low income
 
Affordable and Sustainable Housing:
- IF at or above the 90th percentile for lead paint AND the median house value is less than 90th percentile
- IF at or above the 90th percentile for housing cost burden And is low income

Remediation and Reduction of Legacy Pollution :
- IF at or above the 90th percentile for proximity to RMP sites And is low income
- IF at or above 90th percentile for proximity to superfund sites And is low income
- IF at or above 90th percentile for proximity to hazardous waste facilities And is low income

Critical Clean Water and Waste Infrastructure:
- IF at or above the 90th percentile for wastewater discharge And is low income

Health Burdens:
-  IF at or above the 90th percentile for diabetes And is low income
- IF at or above the 90th percentile for asthma And is low income
- IF at or above the 90th percentile for heart disease And is low income
- lIF at or above the 90th percentile fo rife expectancy And is low income

Training and Workforce Development:
- IF at or above the 90th percentile for unemployment and Where the high school degree achievement rate for adults 25 years and older is less than 90%
- IF at or above the  90th percentile for Linguistic isolation and Where the high school degree achievement rate for adults 25 years and older is less than 90%
- IF at or above the 90th percentile for % households at or below 100% federal poverty level Where the high school degree achievement rate for adults 25 years and older is less than 90%
- IF at or below the 90th percentile for median income Where the high school degree achievement rate for adults 25 years and older is less than 90%

**Comment by switzersc-usds** [comment]
Next steps: design will come up with some options for this.

**Comment by lucasmbrown-usds** [comment]
Are we comfortable with a field name such as, for the first one, `Above the 90th percentile for energy cost burden score and is low income`?

**Comment by esfoobar-usds** [comment]
I feel like this whole decision tree should be in the repo's docs somewhere, it's super helpful to understand how we calculate the score.

**Comment by ahlusar1989** [comment]
@BethMattern - We should change the language here to "At or above...." for all of the thresholds

**Comment by ahlusar1989** [comment]
This is based on the changes made in #959

**Comment by lucasmbrown-usds** [comment]
we're also gonna need a *count* of total criteria exceeded (e.g., an int from 0 to 16 or whatever the total number of criteria is).

**Comment by ahlusar1989** [comment]
Yup - @lucasmbrown-usds I closed the 969 because there are way too many commits to wade through for resolving merge conflicts. I might as well start from scratch.

**Comment by lucasmbrown-usds** [comment]
For field names, idea is something like: 

```
    def _name_non_workforce_fields(self, percentile_field_name: str):
        field_name = (
            f"{percentile_field_name} >= "
            f"{self.ENVIRONMENTAL_BURDEN_THRESHOLD:2f} "
            f"and low income"
        )

        return field_name

    def _name_workforce_fields(self, percentile_field_name: str):
        field_name = (
            f"{percentile_field_name} >= "
            f"{self.ENVIRONMENTAL_BURDEN_THRESHOLD:2f} "
            f"and low HS education"
        )

        return field_name

    def _workforce_factor(self):
        # <blah blah blah>
        UNEMPLOYMENT_LOW_HS_FIELD = self._name_workforce_fields(
            percentile_field_name=field_names.UNEMPLOYMENT_FIELD
            + field_names.PERCENTILE_FIELD_SUFFIX
        )

    def _climate_factor(self):
        # <blah blah blah>
        BUILDING_LOSS_LOW_INCOME_FIELD = self._name_non_workforce_fields(
            percentile_field_name=field_names.EXPECTED_BUILDING_LOSS_RATE_FIELD
            + field_names.PERCENTILE_FIELD_SUFFIX
        )
```
