### ISSUE TITLE
Put CEJST header at top of separate survey tab

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#928]
## Describe the task
Task for @vim-usds  and @KameronKerger: figure out what's possible for SurveyMOnkey customization and implement something. If we want to do something more complicated in the future, create a new issue for it with more details.

## Acceptance Criteria

- [ ] Have some customization of surveymonkey survey page

## Additional context

* Because of moving survey to new tab, it no longer has a header. Vim and Kameron will work together to format SurveyMonkey template to figure out how to add our graphics in the best way.

**Comment by KameronKerger** [comment]
team approved the SurveyMonkey no code fix.
