### ISSUE TITLE
As a J40 team member, I want to be able to refer to a simplified spreadsheet or nontechnical communication document that reflects the EJ score components.

### ISSUE THREAD

**Issue by esfoobar-usds** [usds/justice40-tool#93]
**Description**
We need to determine a minimal representation of how we compute the EJ score we will compute when we add the different data sources.

**Solution**
Create a spreadsheet that represents each data feed component as a tab, a census tab and a score tab that expresses the formula in simple mathematical terms. Each row should represent the minimum viable census level available on most of the planned data sources.

(Inspired by [CalEnviroScreen 4.0 Doc](https://oehha.ca.gov/media/downloads/calenviroscreen/document/calenviroscreen40reportd12021.pdf) - Page 22)

For example:

Tab 1 - Census:
| Census Tract | 
| --- |
| 482012231001050 |

Tab 2 - Pollution Burden > Exposure Indicators:
| Tract | Indicator | Raw Value | Percentile |
| --- | --- | --- | --- | 
| 482012231001050 | Ozone | 0.06 | 84.51 |
| 482012231001050 | PM2.5 | 13.78 | 97.36 |

Tab 3 - Pollution Burden > Exposure Indicators > Average:
| Tract | Average |
| --- | --- |
| 482012231001050 | 80.69 | (the 80.69 is the output of a formula)

Tab 4 - Pollution Burden > Scaled Component Score
| Tract | Average |
| --- | --- |
| 482012231001050 | 8.408  | (the 8.408 is the output of a formula)

Tab 4 - EJScore
| Tract | Score |
| --- | --- |
| 482012231001050 | 72.77 | (the 72.77 is the output of a formula)

Using this sheet can allow us to start a conversation with domain experts to tweak the formula to improve it.

The whole sheet can also serve as a fixture for unit tests expected output.

**Tasks**
- Create Sheet/Doc
- Review internally
- Share with contributors

**Definition of "Done"**
- A spreadsheet or document for communicating methodology decisions for use in gathering feedback from contributors and advisors

![Draft CalEnviroScreen 4.0.png](https://images.zenhubusercontent.com/60a2945ed9da7b7abef702d6/a71b36de-08a2-4f08-8c92-2fc1408dda03)

**Comment by switzersc-usds** [comment]
Update: @lucasmbrown-usds will start this doc tonight.

**Comment by switzersc-usds** [comment]
We have this in a document now that we can use as the base for iteration, plus a spreadsheet with the initial scoring methodology. Marking this as closed.
