### ISSUE TITLE
Add proximity to hazardous waste sites to Remediation and reduction of legacy pollution formula for score L

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#936]
Change the formula for Remediation and reduction of legacy pollution in score L to be:

Proximity to RMP sites ≥ 90th OR
Proximity to NPL sites (superfund sites) ≥ 90th OR
Proximity to hazardous waste sites ≥ 90th

**Comment by ahlusar1989** [comment]
@BethMattern @lucasmbrown-usds @switzersc-usds 

For hazardous waste sites, it may be helpful to add this [reference](https://oehha.ca.gov/media/downloads/calenviroscreen/report/ces3report.pdf)
