### ISSUE TITLE
Reduce threshold for high school degree achievement rate to 90% in training and workforce development formula in score L

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#937]
Reduce threshold for high school degree achievement rate to 90% (from 95%) in training and workforce development formula in score L.

**Comment by saran-ahluwalia** [comment]
@lucasmbrown-usds @switzersc-usds, this appears to be a one line change on line 339 in `score_l.py` (0.05 --> 0.10). Is this all that is required or is there another facet to this that I am missing?

**Comment by switzersc-usds** [comment]
@sarah-saltiel I believe that's it!

**Comment by ahlusar1989** [comment]
Thanks @switzersc-usds. I'll address that shortly
