### ISSUE TITLE
Investigate college enrollment data as replacement for high school degree achievement rate

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#938]
The Census team suggested that we investigate college enrollment data as a replacement for high school degree achievement rate because it could be a better proxy for education.

We should do some analysis to see if this makes sense to do for Score L.

**Comment by saran-ahluwalia** [comment]
@BethMattern @lucasmbrown-usds I am investigating `DP02_0057PE` - percent who are currently enrolled in college or enrolled in graduate school and `DP02_0067PE`, percent with bachelors degree or higher

**Comment by saran-ahluwalia** [comment]
@BethMattern @lucasmbrown-usds  This work is contributing to informing this issue: https://github.com/ahlusar1989/justice40-tool/blob/ahlusar-1989-life-expectancy-es[…]_2_inference/spatial_analysis_2_11302021_version_economic.ipynb

**Comment by saran-ahluwalia** [comment]
@lucasmbrown-usds 

From the Census Tract, is the `B15003`, which contains educational attainment for the population 25 and older. You can specify the variables from that table `B15003_017` through `B15003_25` that represent the population with a HS diploma and above. To calculate the percentage, we can also grab the total population 25 and older to use as the denominator, which is `B15003_001`.
