### ISSUE TITLE
[SPIKE] Investigate impact of upstream data sources failing

### ISSUE THREAD

**Issue by sverchdotgov** [usds/justice40-tool#946]
## Describe the task

The pipeline pulls from live upstream endpoints, this would be an investigation into what would happen if they went down.

## Acceptance Criteria

- [ ] New or updated issues for addressing this problem
- [ ] Small document of the external dependencies that could fail and how they are mitigated

## Additional context

* TODO

**Comment by sverchdotgov** [comment]
# Impact Analysis: Upstream Data Source Failures
## Pipeline Stages

This is what I think the steps are in the pipeline (with links to the github actions that run them):

- [Pull Census Data, Upload to S3](https://github.com/usds/justice40-tool/blob/main/.github/workflows/generate-census.yml#L41)
- [Run All ETLs and Scoring, Upload Combined Results to S3](https://github.com/usds/justice40-tool/blob/main/.github/workflows/generate-score.yml#L42)
- [Pull Results Of Previous Jobs From S3, Generate Tileset and GEOJson and Upload Both To S3](https://github.com/usds/justice40-tool/blob/main/.github/workflows/combine-tilefy.yml#L58)

## Failure Scenarios

### Complete Upstream Outage

#### Pipeline Behavior

I believe if there is a complete upstream outage in a data source, the ETL job will fail, causing the github action to stop and not upload anything to s3.

#### Impact

Inability to update the data, but the version of the data as of the last run will still be present. However, even if we want to update the data for an unrelated upstream source, I believe one endpoint having an outage will cause the entire github action to fail.

#### Possibile Mitigation

Change the ETL pipeline to upload the scoring for each individual source to S3 as a first stage, and add an option for skipping sources that have errors rather than failing the whole job.

### Upstream Data Corruption/Inaccuracy

#### Pipeline Behavior

If there is corruption in the data upstream, the pipeline has no way of knowing this, and will clobber the existing datasets.

#### Impact

The data will be wrong, and running the pipeline will not restore it.

#### Possible Mitigations

Since [s3 bucket versioning](https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html) is enabled, in theory we can restore a previous version of the data. However, this is [not simple to do for an entire sub-path](https://serverfault.com/questions/754410/is-there-any-way-to-restore-an-entire-previous-version-of-a-folder-in-an-s3-buck/757566) so we would have to write some custom scripts.

An alternative approach would be to change the pipeline to upload to a path that has a timestamp in the path, and only clobber the path for the "latest". This would give us an archive of historical versions, and an obvious rollback option to the previous "good" data. This would add an extra upload step to the github actions workflows, and would require follow up work to come up with a deletion policy for old data.

**Comment by sverchdotgov** [comment]
Possible short term mitigation that insulates us from the worst case scenario would be to add a github action that:

1. Runs the etl for all the sources.
2. Uploads the results of running that etl for all the sources to a timestamped directory, does not combine the sources.

Then, if we update the [`generate-score-post`](https://github.com/usds/justice40-tool/blob/main/.github/workflows/generate-score.yml#L48) to allow overrides to pull specific sources from a specific data path. I think that will involve following [this configuration](https://github.com/usds/justice40-tool/blob/1b17af84c824e1836f461788b8aa32b37e47df28/data/data-pipeline/settings.toml#L2) all the way through the code and make it possible to override on a more granular level.

**Comment by switzersc-usds** [comment]
@sverchdotgov I updated #488 to capture the action item to make a Github Action for the data sources ETL.
