### ISSUE TITLE
Import updated DOE LEAD data

### ISSUE THREAD

**Issue by BethMattern** [usds/justice40-tool#951]
DOE provided an updated data file that has more precision than the one we originally used. This needs to be uploaded/used for launch. [https://app.zenhub.com/files/358242767/627c0897-e4a9-4058-9641-d35b0d1fc1ea/download](https://app.zenhub.com/files/358242767/627c0897-e4a9-4058-9641-d35b0d1fc1ea/download)

**Comment by lucasmbrown-usds** [comment]
New file path to s3: 

```
self.DOE_FILE_URL = (
            settings.AWS_JUSTICE40_DATASOURCES_URL
            + "/DOE_LEAD_AMI_TRACT_2018_ALL.csv.zip"
        )
```
