### ISSUE TITLE
When I open the csv or xlsx file, the prefixed 0s in census tract IDs are lost, causing usability issues.

### ISSUE THREAD

**Issue by switzersc-usds** [usds/justice40-tool#953]
**Describe the bug**
When I open the data file (either) in Excel, the first 0 of many of the census tract IDs is dropped and therefore the ID is made incorrect / unusable.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lucasmbrown-usds** [comment]
FYI, I'm not sure you'll be able to fix this in a CSV -- maybe writing strings around the cell like `"01234567890"` works? For excel, you may have to write `='01234567890`, if you try `"01234567890"` and it doesn't work there either.
