### ISSUE TITLE
As a data set developer, I want to implement a strategy for handling null values in territories data.

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#955]
**Description**
About 10% of the census tracts in the 4 territories Guam, Virgin Islands, American Samoa, and Northern Mariana Islands are missing data from decennial census. Decide on strategy for how to handle these tracts.

**Comment by ahlusar1989** [comment]
@lucasmbrown-usds This [document](https://www.census.gov/programs-surveys/cps/technical-documentation/methodology/imputation-of-unreported-data-items.html) may be of some help.

**Comment by vim-usds** [comment]
@lucasmbrown-usds - adding this as a data thing as the front-end handles this with a special icon now.

**Comment by BethMattern** [comment]
Duplicate of 1549
