### ISSUE TITLE
Bug - "Tell us how we're doing" survey link does not stay always visible at the bottom of screen

### ISSUE THREAD

**Issue by katherinedm-usds** [usds/justice40-tool#958]
**Describe the bug**
Yellow survey button "Tell us how we're doing" should always stay visible at the bottom of the CEJST page (About, Explore the tool, Methodology & data, Contact) even if you scroll up/down, but instead stays tied to the bottom of the footer.

**To Reproduce**
1. Go to staging URL
2. Scroll to footer / bottom of page, see "Tell us show we're doing" yellow button at the bottom
3. Scroll up
4. See that "Tell us how we're doing" stays with the footer - you scroll away from it

**Expected behavior**
"Tell us how we're doing" always stays visible at the bottom of the screen, regardless of how you scroll up/down. 

See tsp.gov that uses USWDS for expected behavior

![image.png](https://images.zenhubusercontent.com/609ab603576fa56647137b9e/da23dae1-f0d8-46e5-8e03-81f4af3158b8)

**Screenshots**
![image.png](https://images.zenhubusercontent.com/609ab603576fa56647137b9e/f11e8b6d-6b84-43c5-85d5-e345b3624a17)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
There's a big push to make sure the survey is easily seen/discovered, especially given that the other way of providing feedback for initial launch (the email address) is not ideal. I'm going ahead and putting this into the Sprint Backlog, but if it puts must-have for launch work at risk, then this could be moved back to Product Backlog.

**Comment by vim-usds** [comment]
create full width container with fixed pos. then create a main-content width container and place button in inner container.

**Comment by vim-usds** [comment]
easy fix would be to just change to fixed and not have it aligned to center content

**Comment by vim-usds** [comment]
http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/998-3ea5c1e/en/cejst/#8/0/0
