### ISSUE TITLE
As a data developer, I want to load and investigate college enrollment data from the ACS.

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#960]
**Description**
Investigate adding college enrollment data to the tool to help identify university neighborhoods.

**Comment by ahlusar1989** [comment]
Is this linked to this: #938 @lucasmbrown-usds?

**Comment by lucasmbrown-usds** [comment]
@ahlusar1989 -- oh wow, I had searched but not seen that. You're right, this is a duplicate. I'll close in favor of #938 .
