### ISSUE TITLE
Investigate potentially weighting criteria differently when adding them together.

### ISSUE THREAD

**Issue by lucasmbrown-usds** [usds/justice40-tool#968]
**Description**
In #921 , we add together the criteria to count the number of criteria thresholds exceeded (e.g., 14 of 16) in Definition L. This ticket is to explore potentially introducing for one or two variables a weighted coefficient, so that highly important criteria would count for, say, 1.5 or 2x the value of less important criteria.

**Comment by ahlusar1989** [comment]
@lucasmbrown-usds Regarding this statement "In #921, we add together the criteria to count the number of criteria thresholds exceeded" - we discussed that #921 was no longer counting the number of thresholds, but rather whether or not the criteria were met.

**Comment by ahlusar1989** [comment]
@lucasmbrown-usds  - Health factor weighting example can be found here: https://github.com/ahlusar1989/justice40-tool/blob/ahlusar-1989-life-expectancy-estimator/data/data-pipeline/data_pipeline/ipython/experiment_3_coi_12012021/testing_validation_12012021.ipynb
