### ISSUE TITLE
FIPS code 78 Virgin Islands leads to exception in `df.concat` stage

### ISSUE THREAD

**Issue by ahlusar1989** [usds/justice40-tool#988]
**Describe the bug**

No data for Virgin Islands ( FIPS code 78) yields an exception.

The issues is line 43 `df = pd.concat(dfs)` of `census_acs.etl_utils.py`

**To Reproduce**

1. Go to [Local Development Directions for Setup](https://github.com/usds/justice40-tool/blob/main/data/data-pipeline/README.md#local-development)
2. Execute all steps up to and including **Run both ETL and score generation processes**  - (`poetry run python3 data_pipeline/application.py  data-full-run`
3. Be patient and wait until.....
4. See attached.
<img width="1209" alt="Screen Shot 2021-12-06 at 7 20 28 AM" src="https://user-images.githubusercontent.com/7760225/144845213-248f3787-e7b9-49ec-909b-eaef9fa37f84.png">

ETL and score generation processes should complete successfully

**Desktop (please complete the following information):**
 - OS: MacOS, Big Sur 11.6
 - Python Version: 3.7.4
 - data-pipeline 0.1.0
 - Poetry version 1.1.11

**Comment by esfoobar-usds** [comment]
Have you tried adding the source aws if you haven't generated census locally? I.e.: `python3 -m data_pipeline.application data-full-run -s aws`, although I think that is the default behaviour.

**Comment by saran-ahluwalia** [comment]
Closing this as this may be exacerbated by rate limits - "500 queries per
You can include up to 50 variables in a single API query and can make up to 500 queries per IP address per day. More than 500 queries per IP address per day requires that you register for a Census key."
