### ISSUE TITLE
Investigate base maps from Mikel from OSG

### ISSUE THREAD

**Issue by vim-usds** [usds/justice40-tool#995]
https://api.mapbox.com/styles/v1/mapbox/streets-v11.html?title=true&access_token=pk.[…]ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA

https://api.mapbox.com/styles/v1/mapbox/streets-v11.html?title=true&access_token=pk.[…]ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA

may be able to make other changes in studio

- [x] create mapbox account justice40@ mailing list
- [x] enable other carto base maps
- [x] view MapBox basemaps via HTML in browser
- [x] view MapBox basemaps JSON in browser
- [x] create mapbox styles in account
- [x] list created styles using mapbox API
- [x] get styles from mapbox API
- [x] figure out exactly what's needed before reaching out to Mikel (message already drafted)
- [x] integrate into app (will require a major refactor I believe)
- [x] see if base layers can improve MP as right now it's sparse

**Comment by vim-usds** [comment]
When attempting to add these base layers, it notifies with the following message:

![Screen Shot 2021-12-06 at 8 39 55 PM](https://user-images.githubusercontent.com/86254807/144967511-691f7e94-cdbb-4820-97f0-39c56e29485b.png)

The link goes here:

https://visgl.github.io/react-map-gl/docs/get-started/mapbox-tokens

**Comment by vim-usds** [comment]
@BethMattern and/or @KameronKerger 

Gaining a better understanding of how the basemaps are working now.

Would it be possible to get some use cases around what we're trying to solve? Some theories are that

1. Some territories are lacking labels, eg. MP 
2. Some parts of the US are lacking labels, e.g. AK

Is this the main issue we're trying to solve with finding other basemaps? Is there anything else?

Thanks,

**Comment by KameronKerger** [comment]
@vim-usds I have an unsubstantiated theory that better a base map would improve search. they will also help with the census tract number problem since more / better labels will help people to figure out where the area is. it will also help when the user gets auto-zoomed in when selecting a tract since they would be more likely to have identifying information.

**Comment by vim-usds** [comment]
Beth and Kameron to add requested info on screenshots and associated URLs to provide objective goals for new basemap(s)

**Comment by BethMattern** [comment]
Here's an example comparing our map to the vaccines.gov map when you search for Selma Alabama:
CEJST - https://d29zfl8cj7y1zf.cloudfront.net/en/cejst#12.97/32.4143/-87.0322
![Screen Shot 2022-01-05 at 12.24.18 PM.png](https://images.zenhubusercontent.com/60b948a946294e688f91ba27/e6dd6e8e-fefd-430c-a181-b7a823191325)
vaccines.gov - https://www.vaccines.gov/results/?zipcode=36785&medications=25f1389c-5597-47cc-9a9d-3925d60d9c21&radius=25&appointments=true
![Screen Shot 2022-01-05 at 12.24.40 PM.png](https://images.zenhubusercontent.com/60b948a946294e688f91ba27/8b2b2da3-a32d-43ce-90f6-8ac2199b9818)

**Comment by vim-usds** [comment]
@Beth - thanks this is super helpful!

**Comment by KameronKerger** [comment]
south of traverse city Michigan - justice map.org vs. crust
<img width="563" alt="Screen Shot 2022-01-05 at 12 44 52 PM" src="https://user-images.githubusercontent.com/77702996/148286861-20ecd2e9-24be-4bd7-8fa9-475b2bff2cce.png">
<img width="594" alt="Screen Shot 2022-01-05 at 12 46 10 PM" src="https://user-images.githubusercontent.com/77702996/148286968-3cf817b3-c032-4dae-bc7d-b0ad1e0e5e21.png">

**Comment by KameronKerger** [comment]
south west of Montgomery Alabama (OpenStreetMap via treeequity score vs. cejst
<img width="720" alt="Screen Shot 2022-01-05 at 12 47 41 PM" src="https://user-images.githubusercontent.com/77702996/148287226-9b6efd98-9a6a-42f6-8376-80b3256fbd2c.png">
<img width="940" alt="Screen Shot 2022-01-05 at 12 47 59 PM" src="https://user-images.githubusercontent.com/77702996/148287249-2f25a546-4e91-4d14-939e-47580488461b.png">

**Comment by KameronKerger** [comment]
datahouston vs. cejst
<img width="769" alt="Screen Shot 2022-01-05 at 12 51 51 PM" src="https://user-images.githubusercontent.com/77702996/148287732-44ac8e52-291c-4f60-97e2-78597ab88691.png">
<img width="769" alt="Screen Shot 2022-01-05 at 12 51 51 PM" src="https://user-images.githubusercontent.com/77702996/148287776-41539540-92e9-4a5f-afce-b639593cf239.png">

**Comment by KameronKerger** [comment]
Brooklyn, blockmaps vs. cejst
<img width="1318" alt="Screen Shot 2022-01-05 at 12 55 51 PM" src="https://user-images.githubusercontent.com/77702996/148288363-63a4f5a6-f0f4-4dbc-a04f-6ab50aed1d34.png">
<img width="723" alt="Screen Shot 2022-01-05 at 12 56 59 PM" src="https://user-images.githubusercontent.com/77702996/148288425-c88b4efd-afeb-4f27-9e7c-673baba59e0b.png">

**Comment by KameronKerger** [comment]
saving these here for posterity as well
<img width="1318" alt="Screen Shot 2022-01-05 at 12 55 51 PM" src="https://user-images.githubusercontent.com/77702996/148288910-be3f49e3-5faf-4afd-bae5-18afbbee8b2f.png">
<img width="723" alt="Screen Shot 2022-01-05 at 12 56 59 PM" src="https://user-images.githubusercontent.com/77702996/148288928-cc82b431-f341-4454-a9a9-e46cb959347a.png">

**Comment by KameronKerger** [comment]
this inclusion of the surrounding census tract numbers is... something.
<img width="945" alt="Screen Shot 2022-01-05 at 1 46 07 PM" src="https://user-images.githubusercontent.com/77702996/148294314-b4f2033a-b2af-4600-83a8-f3594c4d9c0b.png">
<img width="720" alt="Screen Shot 2022-01-05 at 1 46 22 PM" src="https://user-images.githubusercontent.com/77702996/148294322-db09e332-d428-48de-bd45-cf63f3a22759.png">

**Comment by vim-usds** [comment]
@KameronKerger - thanks for the awesome data points!

**Comment by vim-usds** [comment]
Investigated MapBox Raster and Vector Tiles API. It seems that the Raster Tile API integrates well into our map. Unfortunately it doesn't have many labels. Finally sent a message to Mikel on getting more information.

Moving into looking how to disable the white overlay in High Zoom

**Comment by vim-usds** [comment]
Things left to do:

- [ ] remove white layer on non-prio features
- [ ] refactor comments and constants on map
- [ ] update PR with new findings from above
- [ ] Hear back from Mikel to see if other MapBox Tilesets are available (other than example)
- [ ] write up cost comparison between MapBox, MapTiler, GeoAmpify
- [ ] Try out other GeoAmpify tilesets
- [ ] make decision on how to move forward

**Comment by vim-usds** [comment]
Final task on this is to push forward with the paid MapBox base map and add the ability to switch from free to paid MapBox base map in the future #1133
